/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
	"context"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
)

// Linger please
var (
	_ context.Context
)

type LiveStreamApiGetLiveStreamKeysRequest struct {
	search  *string
	sortBy  *string
	orderBy *string
	offset  *int64
	limit   *int64
	type_   *string
}

func (r LiveStreamApiGetLiveStreamKeysRequest) Search(search string) LiveStreamApiGetLiveStreamKeysRequest {
	r.search = &search
	return r
}
func (r LiveStreamApiGetLiveStreamKeysRequest) SortBy(sortBy string) LiveStreamApiGetLiveStreamKeysRequest {
	r.sortBy = &sortBy
	return r
}
func (r LiveStreamApiGetLiveStreamKeysRequest) OrderBy(orderBy string) LiveStreamApiGetLiveStreamKeysRequest {
	r.orderBy = &orderBy
	return r
}
func (r LiveStreamApiGetLiveStreamKeysRequest) Offset(offset int64) LiveStreamApiGetLiveStreamKeysRequest {
	r.offset = &offset
	return r
}
func (r LiveStreamApiGetLiveStreamKeysRequest) Limit(limit int64) LiveStreamApiGetLiveStreamKeysRequest {
	r.limit = &limit
	return r
}
func (r LiveStreamApiGetLiveStreamKeysRequest) Type_(type_ string) LiveStreamApiGetLiveStreamKeysRequest {
	r.type_ = &type_
	return r
}

type LiveStreamApiGetStreamingsRequest struct {
	search *string
}

func (r LiveStreamApiGetStreamingsRequest) Search(search string) LiveStreamApiGetStreamingsRequest {
	r.search = &search
	return r
}

type LiveStreamApiGetUserStreamsUsageDetailRequest struct {
	from   *int64
	to     *int64
	offset *int64
	limit  *int64
}

func (r LiveStreamApiGetUserStreamsUsageDetailRequest) From(from int64) LiveStreamApiGetUserStreamsUsageDetailRequest {
	r.from = &from
	return r
}
func (r LiveStreamApiGetUserStreamsUsageDetailRequest) To(to int64) LiveStreamApiGetUserStreamsUsageDetailRequest {
	r.to = &to
	return r
}
func (r LiveStreamApiGetUserStreamsUsageDetailRequest) Offset(offset int64) LiveStreamApiGetUserStreamsUsageDetailRequest {
	r.offset = &offset
	return r
}
func (r LiveStreamApiGetUserStreamsUsageDetailRequest) Limit(limit int64) LiveStreamApiGetUserStreamsUsageDetailRequest {
	r.limit = &limit
	return r
}

type LiveStreamServiceI interface {
	/*
	 * UploadThumbnail Upload live stream media thumbnail
	 * @param id live stream media's id
	 * @return LiveStreamApiUploadThumbnailRequest
	 */
	UploadThumbnail(id string, fileName string, fileReader io.Reader) (*ResponseSuccess, error)
	/*
	 * UploadThumbnail Upload live stream media thumbnail
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id live stream media's id
	 * @return LiveStreamApiUploadThumbnailRequest
	 */
	UploadThumbnailWithContext(ctx context.Context, id string, fileName string, fileReader io.Reader) (*ResponseSuccess, error)

	/*
	 * DeleteThumbnail Delete live stream media thumbnail
	 * @param id live stream media's id
	 * @return LiveStreamApiDeleteThumbnailRequest
	 */

	DeleteThumbnail(id string) (*ResponseSuccess, error)

	/*
	 * DeleteThumbnail Delete live stream media thumbnail
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id live stream media's id
	 * @return LiveStreamApiDeleteThumbnailRequest
	 */

	DeleteThumbnailWithContext(ctx context.Context, id string) (*ResponseSuccess, error)

	/*
	 * AddLiveStreamMulticasts Add live stream multicast
	 * @param streamKey Live stream key. Use uuid
	 * @return LiveStreamApiAddLiveStreamMulticastsRequest
	 */

	AddLiveStreamMulticasts(streamKey string, upsertLiveStreamMulticastInput UpsertLiveStreamMulticastInput) (*GetLiveStreamMulticastResponse, error)

	/*
	 * AddLiveStreamMulticasts Add live stream multicast
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param streamKey Live stream key. Use uuid
	 * @return LiveStreamApiAddLiveStreamMulticastsRequest
	 */

	AddLiveStreamMulticastsWithContext(ctx context.Context, streamKey string, upsertLiveStreamMulticastInput UpsertLiveStreamMulticastInput) (*GetLiveStreamMulticastResponse, error)

	/*
	 * CreateLiveStreamKey Create live stream key
	 * @return LiveStreamApiCreateLiveStreamKeyRequest
	 */

	CreateLiveStreamKey(createLiveStreamKeyRequest CreateLiveStreamKeyRequest) (*CreateLiveStreamKeyResponse, error)

	/*
	 * CreateLiveStreamKey Create live stream key
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return LiveStreamApiCreateLiveStreamKeyRequest
	 */

	CreateLiveStreamKeyWithContext(ctx context.Context, createLiveStreamKeyRequest CreateLiveStreamKeyRequest) (*CreateLiveStreamKeyResponse, error)

	/*
	 * CreateStreaming Create a new live stream media
	 * @param id Live stream key ID
	 * @return LiveStreamApiCreateStreamingRequest
	 */

	CreateStreaming(id string, createStreamingRequest CreateStreamingRequest) (*CreateStreamingResponse, error)

	/*
	 * CreateStreaming Create a new live stream media
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiCreateStreamingRequest
	 */

	CreateStreamingWithContext(ctx context.Context, id string, createStreamingRequest CreateStreamingRequest) (*CreateStreamingResponse, error)

	/*
	 * DeleteLiveStreamKey Delete live stream key
	 * @param id Live stream key ID
	 * @return LiveStreamApiDeleteLiveStreamKeyRequest
	 */

	DeleteLiveStreamKey(id string) (*ResponseSuccess, error)

	/*
	 * DeleteLiveStreamKey Delete live stream key
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiDeleteLiveStreamKeyRequest
	 */

	DeleteLiveStreamKeyWithContext(ctx context.Context, id string) (*ResponseSuccess, error)

	/*
	 * DeleteLiveStreamMulticast Delete live stream multicast
	 * @param streamKey Live stream key. UUID string format
	 * @return LiveStreamApiDeleteLiveStreamMulticastRequest
	 */

	DeleteLiveStreamMulticast(streamKey string) (*ResponseSuccess, error)

	/*
	 * DeleteLiveStreamMulticast Delete live stream multicast
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param streamKey Live stream key. UUID string format
	 * @return LiveStreamApiDeleteLiveStreamMulticastRequest
	 */

	DeleteLiveStreamMulticastWithContext(ctx context.Context, streamKey string) (*ResponseSuccess, error)

	/*
	 * GetLiveStreamKey Get live stream key
	 * @param id ID
	 * @return LiveStreamApiGetLiveStreamKeyRequest
	 */

	GetLiveStreamKey(id string) (*GetLiveStreamKeyResponse, error)

	/*
	 * GetLiveStreamKey Get live stream key
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id ID
	 * @return LiveStreamApiGetLiveStreamKeyRequest
	 */

	GetLiveStreamKeyWithContext(ctx context.Context, id string) (*GetLiveStreamKeyResponse, error)

	/*
	 * GetLiveStreamKeys Get live stream key list
	 * @return LiveStreamApiGetLiveStreamKeysRequest
	 */

	GetLiveStreamKeys(r LiveStreamApiGetLiveStreamKeysRequest) (*GetLiveStreamKeysListResponse, error)

	/*
	 * GetLiveStreamKeys Get live stream key list
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return LiveStreamApiGetLiveStreamKeysRequest
	 */

	GetLiveStreamKeysWithContext(ctx context.Context, r LiveStreamApiGetLiveStreamKeysRequest) (*GetLiveStreamKeysListResponse, error)

	/*
	 * GetLiveStreamMedia Get live stream media
	 * @param id Live stream media ID
	 * @return LiveStreamApiGetLiveStreamMediaRequest
	 */

	GetLiveStreamMedia(id string) (*GetLiveStreamMediaResponse, error)

	/*
	 * GetLiveStreamMedia Get live stream media
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream media ID
	 * @return LiveStreamApiGetLiveStreamMediaRequest
	 */

	GetLiveStreamMediaWithContext(ctx context.Context, id string) (*GetLiveStreamMediaResponse, error)

	/*
	 * GetLiveStreamMedias Get live stream media
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetLiveStreamMediasRequest
	 */

	GetLiveStreamMedias(id string, getLiveStreamMediasRequest GetLiveStreamMediasRequest) (*GetLiveStreamMediasResponse, error)

	/*
	 * GetLiveStreamMedias Get live stream media
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetLiveStreamMediasRequest
	 */

	GetLiveStreamMediasWithContext(ctx context.Context, id string, getLiveStreamMediasRequest GetLiveStreamMediasRequest) (*GetLiveStreamMediasResponse, error)

	/*
	 * GetLiveStreamMulticastByStreamKey Get live stream multicast by stream key
	 * @param streamKey Live stream key. UUID string format
	 * @return LiveStreamApiGetLiveStreamMulticastByStreamKeyRequest
	 */

	GetLiveStreamMulticastByStreamKey(streamKey string) (*GetLiveStreamMulticastResponse, error)

	/*
	 * GetLiveStreamMulticastByStreamKey Get live stream multicast by stream key
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param streamKey Live stream key. UUID string format
	 * @return LiveStreamApiGetLiveStreamMulticastByStreamKeyRequest
	 */

	GetLiveStreamMulticastByStreamKeyWithContext(ctx context.Context, streamKey string) (*GetLiveStreamMulticastResponse, error)

	/*
	 * GetLiveStreamPlayerInfo Get live stream media public
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetLiveStreamPlayerInfoRequest
	 */

	GetLiveStreamPlayerInfo(id string) (*GetLiveStreamMediaPublicResponse, error)

	/*
	 * GetLiveStreamPlayerInfo Get live stream media public
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetLiveStreamPlayerInfoRequest
	 */

	GetLiveStreamPlayerInfoWithContext(ctx context.Context, id string) (*GetLiveStreamMediaPublicResponse, error)

	/*
	 * GetLiveStreamStatisticByStreamMediaId Get live stream statistic by stream media id
	 * @param streamMediaId Live stream media ID
	 * @return LiveStreamApiGetLiveStreamStatisticByStreamMediaIdRequest
	 */

	GetLiveStreamStatisticByStreamMediaId(streamMediaId string) (*GetLiveStreamStatisticResponse, error)

	/*
	 * GetLiveStreamStatisticByStreamMediaId Get live stream statistic by stream media id
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param streamMediaId Live stream media ID
	 * @return LiveStreamApiGetLiveStreamStatisticByStreamMediaIdRequest
	 */

	GetLiveStreamStatisticByStreamMediaIdWithContext(ctx context.Context, streamMediaId string) (*GetLiveStreamStatisticResponse, error)

	/*
	 * GetLiveStreamUsage Get usage details for a specific live stream
	 * @param streamId Stream ID (LiveStreamMedia ID)
	 * @return LiveStreamApiGetLiveStreamUsageRequest
	 */

	GetLiveStreamUsage(streamId string) (*GetStreamUsageResponse, error)

	/*
	 * GetLiveStreamUsage Get usage details for a specific live stream
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param streamId Stream ID (LiveStreamMedia ID)
	 * @return LiveStreamApiGetLiveStreamUsageRequest
	 */

	GetLiveStreamUsageWithContext(ctx context.Context, streamId string) (*GetStreamUsageResponse, error)

	/*
	 * GetStreaming Get live stream media streaming
	 * @param id Live stream key ID
	 * @param streamId Stream ID
	 * @return LiveStreamApiGetStreamingRequest
	 */

	GetStreaming(id string, streamId string) (*GetStreamingResponse, error)

	/*
	 * GetStreaming Get live stream media streaming
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @param streamId Stream ID
	 * @return LiveStreamApiGetStreamingRequest
	 */

	GetStreamingWithContext(ctx context.Context, id string, streamId string) (*GetStreamingResponse, error)

	/*
	 * GetStreamings Get live stream media streamings
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetStreamingsRequest
	 */

	GetStreamings(id string, r LiveStreamApiGetStreamingsRequest) (*GetStreamingsResponse, error)

	/*
	 * GetStreamings Get live stream media streamings
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetStreamingsRequest
	 */

	GetStreamingsWithContext(ctx context.Context, id string, r LiveStreamApiGetStreamingsRequest) (*GetStreamingsResponse, error)

	/*
	 * GetUserStreamsUsageDetail Get paginated list of streams with usage details for current user
	 * @return LiveStreamApiGetUserStreamsUsageDetailRequest
	 */

	GetUserStreamsUsageDetail(r LiveStreamApiGetUserStreamsUsageDetailRequest) (*GetUserStreamsUsageDetailResponse, error)

	/*
	 * GetUserStreamsUsageDetail Get paginated list of streams with usage details for current user
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return LiveStreamApiGetUserStreamsUsageDetailRequest
	 */

	GetUserStreamsUsageDetailWithContext(ctx context.Context, r LiveStreamApiGetUserStreamsUsageDetailRequest) (*GetUserStreamsUsageDetailResponse, error)

	/*
	 * UpdateLiveStreamKey Update live stream key
	 * @param id Live stream key ID
	 * @return LiveStreamApiUpdateLiveStreamKeyRequest
	 */

	UpdateLiveStreamKey(id string, updateLiveStreamKeyRequest UpdateLiveStreamKeyRequest) (*UpdateLiveStreamKeyResponse, error)

	/*
	 * UpdateLiveStreamKey Update live stream key
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiUpdateLiveStreamKeyRequest
	 */

	UpdateLiveStreamKeyWithContext(ctx context.Context, id string, updateLiveStreamKeyRequest UpdateLiveStreamKeyRequest) (*UpdateLiveStreamKeyResponse, error)

	/*
	 * UpdateLiveStreamMedia Update live stream media
	 * @param id Live stream key ID
	 * @return LiveStreamApiUpdateLiveStreamMediaRequest
	 */

	UpdateLiveStreamMedia(id string, updateLiveStreamMediaRequest UpdateLiveStreamMediaRequest) (*ResponseSuccess, error)

	/*
	 * UpdateLiveStreamMedia Update live stream media
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiUpdateLiveStreamMediaRequest
	 */

	UpdateLiveStreamMediaWithContext(ctx context.Context, id string, updateLiveStreamMediaRequest UpdateLiveStreamMediaRequest) (*ResponseSuccess, error)
}

// LiveStreamService communicating with the LiveStream
// endpoints of the AIOZ Stream API
type LiveStreamService struct {
	client *Client
}

/*
 * UploadThumbnail Upload live stream media thumbnail

 * @param id live stream media's id
 * @return LiveStreamApiUploadThumbnailRequest
 */

func (s *LiveStreamService) UploadThumbnailFile(id string, file *os.File) (*ResponseSuccess, error) {
	return s.UploadThumbnailFileWithContext(context.Background(), id, file)
}

/*
 * UploadThumbnail Upload live stream media thumbnail
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id live stream media's id
 * @return LiveStreamApiUploadThumbnailRequest
 */

func (s *LiveStreamService) UploadThumbnailFileWithContext(ctx context.Context, id string, file *os.File) (*ResponseSuccess, error) {
	// A nil file sends no file part, for an endpoint whose file is optional.
	var fileName string
	var fileReader io.Reader
	if file != nil {
		fileName, fileReader = file.Name(), file
	}

	return s.UploadThumbnailWithContext(ctx, id, fileName, fileReader)
}

/*
* UploadThumbnail Upload live stream media thumbnail

* @param id live stream media's id
* @return LiveStreamApiUploadThumbnailRequest
 */
func (s *LiveStreamService) UploadThumbnail(id string, fileName string, fileReader io.Reader) (*ResponseSuccess, error) {
	return s.UploadThumbnailWithContext(context.Background(), id, fileName, fileReader)
}

/*
 * UploadThumbnail Upload live stream media thumbnail
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id live stream media's id
 * @return LiveStreamApiUploadThumbnailRequest
 */
func (s *LiveStreamService) UploadThumbnailWithContext(ctx context.Context, id string, fileName string, fileReader io.Reader) (*ResponseSuccess, error) {
	localVarPath := "/live_streams/{id}/thumbnail"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := make(map[string]string)

	req, err := s.client.prepareUploadRequest(ctx, http.MethodPost, localVarPath, fileName, fileReader, localVarHeaderParams, localVarQueryParams, localVarFormParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * DeleteThumbnail Delete live stream media thumbnail

 * @param id live stream media's id
 * @return LiveStreamApiDeleteThumbnailRequest
 */

func (s *LiveStreamService) DeleteThumbnail(id string) (*ResponseSuccess, error) {

	return s.DeleteThumbnailWithContext(context.Background(), id)

}

/*
 * DeleteThumbnail Delete live stream media thumbnail
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id live stream media's id
 * @return LiveStreamApiDeleteThumbnailRequest
 */

func (s *LiveStreamService) DeleteThumbnailWithContext(ctx context.Context, id string) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/thumbnail"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodDelete, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * AddLiveStreamMulticasts Add live stream multicast
 * Add live stream multicast

 * @param streamKey Live stream key. Use uuid
 * @return LiveStreamApiAddLiveStreamMulticastsRequest
 */

func (s *LiveStreamService) AddLiveStreamMulticasts(streamKey string, upsertLiveStreamMulticastInput UpsertLiveStreamMulticastInput) (*GetLiveStreamMulticastResponse, error) {

	return s.AddLiveStreamMulticastsWithContext(context.Background(), streamKey, upsertLiveStreamMulticastInput)

}

/*
 * AddLiveStreamMulticasts Add live stream multicast
 * Add live stream multicast
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param streamKey Live stream key. Use uuid
 * @return LiveStreamApiAddLiveStreamMulticastsRequest
 */

func (s *LiveStreamService) AddLiveStreamMulticastsWithContext(ctx context.Context, streamKey string, upsertLiveStreamMulticastInput UpsertLiveStreamMulticastInput) (*GetLiveStreamMulticastResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/multicast/{stream_key}"
	localVarPath = strings.Replace(localVarPath, "{"+"stream_key"+"}", url.PathEscape(parameterToString(streamKey, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = upsertLiveStreamMulticastInput

	req, err := s.client.prepareRequest(ctx, http.MethodPost, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamMulticastResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * CreateLiveStreamKey Create live stream key
 * Create live stream key

 * @return LiveStreamApiCreateLiveStreamKeyRequest
 */

func (s *LiveStreamService) CreateLiveStreamKey(createLiveStreamKeyRequest CreateLiveStreamKeyRequest) (*CreateLiveStreamKeyResponse, error) {

	return s.CreateLiveStreamKeyWithContext(context.Background(), createLiveStreamKeyRequest)

}

/*
 * CreateLiveStreamKey Create live stream key
 * Create live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return LiveStreamApiCreateLiveStreamKeyRequest
 */

func (s *LiveStreamService) CreateLiveStreamKeyWithContext(ctx context.Context, createLiveStreamKeyRequest CreateLiveStreamKeyRequest) (*CreateLiveStreamKeyResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = createLiveStreamKeyRequest

	req, err := s.client.prepareRequest(ctx, http.MethodPost, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(CreateLiveStreamKeyResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * CreateStreaming Create a new live stream media
 * Creates a new live stream media with the provided details

 * @param id Live stream key ID
 * @return LiveStreamApiCreateStreamingRequest
 */

func (s *LiveStreamService) CreateStreaming(id string, createStreamingRequest CreateStreamingRequest) (*CreateStreamingResponse, error) {

	return s.CreateStreamingWithContext(context.Background(), id, createStreamingRequest)

}

/*
 * CreateStreaming Create a new live stream media
 * Creates a new live stream media with the provided details
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiCreateStreamingRequest
 */

func (s *LiveStreamService) CreateStreamingWithContext(ctx context.Context, id string, createStreamingRequest CreateStreamingRequest) (*CreateStreamingResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/streamings"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = createStreamingRequest

	req, err := s.client.prepareRequest(ctx, http.MethodPost, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(CreateStreamingResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * DeleteLiveStreamKey Delete live stream key
 * Delete a live stream key by ID

 * @param id Live stream key ID
 * @return LiveStreamApiDeleteLiveStreamKeyRequest
 */

func (s *LiveStreamService) DeleteLiveStreamKey(id string) (*ResponseSuccess, error) {

	return s.DeleteLiveStreamKeyWithContext(context.Background(), id)

}

/*
 * DeleteLiveStreamKey Delete live stream key
 * Delete a live stream key by ID
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiDeleteLiveStreamKeyRequest
 */

func (s *LiveStreamService) DeleteLiveStreamKeyWithContext(ctx context.Context, id string) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodDelete, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * DeleteLiveStreamMulticast Delete live stream multicast
 * Delete live stream multicast

 * @param streamKey Live stream key. UUID string format
 * @return LiveStreamApiDeleteLiveStreamMulticastRequest
 */

func (s *LiveStreamService) DeleteLiveStreamMulticast(streamKey string) (*ResponseSuccess, error) {

	return s.DeleteLiveStreamMulticastWithContext(context.Background(), streamKey)

}

/*
 * DeleteLiveStreamMulticast Delete live stream multicast
 * Delete live stream multicast
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param streamKey Live stream key. UUID string format
 * @return LiveStreamApiDeleteLiveStreamMulticastRequest
 */

func (s *LiveStreamService) DeleteLiveStreamMulticastWithContext(ctx context.Context, streamKey string) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/multicast/{stream_key}"
	localVarPath = strings.Replace(localVarPath, "{"+"stream_key"+"}", url.PathEscape(parameterToString(streamKey, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodDelete, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamKey Get live stream key
 * Get live stream key

 * @param id ID
 * @return LiveStreamApiGetLiveStreamKeyRequest
 */

func (s *LiveStreamService) GetLiveStreamKey(id string) (*GetLiveStreamKeyResponse, error) {

	return s.GetLiveStreamKeyWithContext(context.Background(), id)

}

/*
 * GetLiveStreamKey Get live stream key
 * Get live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id ID
 * @return LiveStreamApiGetLiveStreamKeyRequest
 */

func (s *LiveStreamService) GetLiveStreamKeyWithContext(ctx context.Context, id string) (*GetLiveStreamKeyResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamKeyResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamKeys Get live stream key list
 * Get live stream key list

 * @return LiveStreamApiGetLiveStreamKeysRequest
 */

func (s *LiveStreamService) GetLiveStreamKeys(r LiveStreamApiGetLiveStreamKeysRequest) (*GetLiveStreamKeysListResponse, error) {

	return s.GetLiveStreamKeysWithContext(context.Background(), r)

}

/*
 * GetLiveStreamKeys Get live stream key list
 * Get live stream key list
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return LiveStreamApiGetLiveStreamKeysRequest
 */

func (s *LiveStreamService) GetLiveStreamKeysWithContext(ctx context.Context, r LiveStreamApiGetLiveStreamKeysRequest) (*GetLiveStreamKeysListResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	if r.search != nil {
		localVarQueryParams.Add("search", parameterToString(*r.search, ""))
	}
	if r.sortBy != nil {
		localVarQueryParams.Add("sort_by", parameterToString(*r.sortBy, ""))
	}
	if r.orderBy != nil {
		localVarQueryParams.Add("order_by", parameterToString(*r.orderBy, ""))
	}
	if r.offset != nil {
		localVarQueryParams.Add("offset", parameterToString(*r.offset, ""))
	}
	if r.limit != nil {
		localVarQueryParams.Add("limit", parameterToString(*r.limit, ""))
	}
	if r.type_ != nil {
		localVarQueryParams.Add("type", parameterToString(*r.type_, ""))
	}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamKeysListResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamMedia Get live stream media
 * Get a specific live stream media by ID

 * @param id Live stream media ID
 * @return LiveStreamApiGetLiveStreamMediaRequest
 */

func (s *LiveStreamService) GetLiveStreamMedia(id string) (*GetLiveStreamMediaResponse, error) {

	return s.GetLiveStreamMediaWithContext(context.Background(), id)

}

/*
 * GetLiveStreamMedia Get live stream media
 * Get a specific live stream media by ID
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream media ID
 * @return LiveStreamApiGetLiveStreamMediaRequest
 */

func (s *LiveStreamService) GetLiveStreamMediaWithContext(ctx context.Context, id string) (*GetLiveStreamMediaResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/media"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamMediaResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamMedias Get live stream media
 * Get live stream media for a specific live stream key

 * @param id Live stream key ID
 * @return LiveStreamApiGetLiveStreamMediasRequest
 */

func (s *LiveStreamService) GetLiveStreamMedias(id string, getLiveStreamMediasRequest GetLiveStreamMediasRequest) (*GetLiveStreamMediasResponse, error) {

	return s.GetLiveStreamMediasWithContext(context.Background(), id, getLiveStreamMediasRequest)

}

/*
 * GetLiveStreamMedias Get live stream media
 * Get live stream media for a specific live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiGetLiveStreamMediasRequest
 */

func (s *LiveStreamService) GetLiveStreamMediasWithContext(ctx context.Context, id string, getLiveStreamMediasRequest GetLiveStreamMediasRequest) (*GetLiveStreamMediasResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/media"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = getLiveStreamMediasRequest

	req, err := s.client.prepareRequest(ctx, http.MethodPost, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamMediasResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamMulticastByStreamKey Get live stream multicast by stream key
 * Get live stream multicast by stream key

 * @param streamKey Live stream key. UUID string format
 * @return LiveStreamApiGetLiveStreamMulticastByStreamKeyRequest
 */

func (s *LiveStreamService) GetLiveStreamMulticastByStreamKey(streamKey string) (*GetLiveStreamMulticastResponse, error) {

	return s.GetLiveStreamMulticastByStreamKeyWithContext(context.Background(), streamKey)

}

/*
 * GetLiveStreamMulticastByStreamKey Get live stream multicast by stream key
 * Get live stream multicast by stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param streamKey Live stream key. UUID string format
 * @return LiveStreamApiGetLiveStreamMulticastByStreamKeyRequest
 */

func (s *LiveStreamService) GetLiveStreamMulticastByStreamKeyWithContext(ctx context.Context, streamKey string) (*GetLiveStreamMulticastResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/multicast/{stream_key}"
	localVarPath = strings.Replace(localVarPath, "{"+"stream_key"+"}", url.PathEscape(parameterToString(streamKey, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamMulticastResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamPlayerInfo Get live stream media public
 * Get live stream media public for a specific live stream key

 * @param id Live stream key ID
 * @return LiveStreamApiGetLiveStreamPlayerInfoRequest
 */

func (s *LiveStreamService) GetLiveStreamPlayerInfo(id string) (*GetLiveStreamMediaPublicResponse, error) {

	return s.GetLiveStreamPlayerInfoWithContext(context.Background(), id)

}

/*
 * GetLiveStreamPlayerInfo Get live stream media public
 * Get live stream media public for a specific live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiGetLiveStreamPlayerInfoRequest
 */

func (s *LiveStreamService) GetLiveStreamPlayerInfoWithContext(ctx context.Context, id string) (*GetLiveStreamMediaPublicResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/player/{id}/media"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamMediaPublicResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamStatisticByStreamMediaId Get live stream statistic by stream media id
 * Get live stream statistic by stream media id

 * @param streamMediaId Live stream media ID
 * @return LiveStreamApiGetLiveStreamStatisticByStreamMediaIdRequest
 */

func (s *LiveStreamService) GetLiveStreamStatisticByStreamMediaId(streamMediaId string) (*GetLiveStreamStatisticResponse, error) {

	return s.GetLiveStreamStatisticByStreamMediaIdWithContext(context.Background(), streamMediaId)

}

/*
 * GetLiveStreamStatisticByStreamMediaId Get live stream statistic by stream media id
 * Get live stream statistic by stream media id
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param streamMediaId Live stream media ID
 * @return LiveStreamApiGetLiveStreamStatisticByStreamMediaIdRequest
 */

func (s *LiveStreamService) GetLiveStreamStatisticByStreamMediaIdWithContext(ctx context.Context, streamMediaId string) (*GetLiveStreamStatisticResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/statistic/{stream_media_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"stream_media_id"+"}", url.PathEscape(parameterToString(streamMediaId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamStatisticResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamUsage Get usage details for a specific live stream
 * Returns transcoding duration, storage, and per-rendition breakdown for a stream

 * @param streamId Stream ID (LiveStreamMedia ID)
 * @return LiveStreamApiGetLiveStreamUsageRequest
 */

func (s *LiveStreamService) GetLiveStreamUsage(streamId string) (*GetStreamUsageResponse, error) {

	return s.GetLiveStreamUsageWithContext(context.Background(), streamId)

}

/*
 * GetLiveStreamUsage Get usage details for a specific live stream
 * Returns transcoding duration, storage, and per-rendition breakdown for a stream
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param streamId Stream ID (LiveStreamMedia ID)
 * @return LiveStreamApiGetLiveStreamUsageRequest
 */

func (s *LiveStreamService) GetLiveStreamUsageWithContext(ctx context.Context, streamId string) (*GetStreamUsageResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/usage/{stream_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"stream_id"+"}", url.PathEscape(parameterToString(streamId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetStreamUsageResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetStreaming Get live stream media streaming
 * Get live stream media streaming for a specific live stream key

 * @param id Live stream key ID
 * @param streamId Stream ID
 * @return LiveStreamApiGetStreamingRequest
 */

func (s *LiveStreamService) GetStreaming(id string, streamId string) (*GetStreamingResponse, error) {

	return s.GetStreamingWithContext(context.Background(), id, streamId)

}

/*
 * GetStreaming Get live stream media streaming
 * Get live stream media streaming for a specific live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @param streamId Stream ID
 * @return LiveStreamApiGetStreamingRequest
 */

func (s *LiveStreamService) GetStreamingWithContext(ctx context.Context, id string, streamId string) (*GetStreamingResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/streamings/{stream_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"stream_id"+"}", url.PathEscape(parameterToString(streamId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetStreamingResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetStreamings Get live stream media streamings
 * Get live stream media streamings for a specific live stream key

 * @param id Live stream key ID
 * @return LiveStreamApiGetStreamingsRequest
 */

func (s *LiveStreamService) GetStreamings(id string, r LiveStreamApiGetStreamingsRequest) (*GetStreamingsResponse, error) {

	return s.GetStreamingsWithContext(context.Background(), id, r)

}

/*
 * GetStreamings Get live stream media streamings
 * Get live stream media streamings for a specific live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiGetStreamingsRequest
 */

func (s *LiveStreamService) GetStreamingsWithContext(ctx context.Context, id string, r LiveStreamApiGetStreamingsRequest) (*GetStreamingsResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/streamings"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	if r.search != nil {
		localVarQueryParams.Add("search", parameterToString(*r.search, ""))
	}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetStreamingsResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetUserStreamsUsageDetail Get paginated list of streams with usage details for current user
 * Returns list of streams with their transcoding duration, storage, and renditions

 * @return LiveStreamApiGetUserStreamsUsageDetailRequest
 */

func (s *LiveStreamService) GetUserStreamsUsageDetail(r LiveStreamApiGetUserStreamsUsageDetailRequest) (*GetUserStreamsUsageDetailResponse, error) {

	return s.GetUserStreamsUsageDetailWithContext(context.Background(), r)

}

/*
 * GetUserStreamsUsageDetail Get paginated list of streams with usage details for current user
 * Returns list of streams with their transcoding duration, storage, and renditions
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return LiveStreamApiGetUserStreamsUsageDetailRequest
 */

func (s *LiveStreamService) GetUserStreamsUsageDetailWithContext(ctx context.Context, r LiveStreamApiGetUserStreamsUsageDetailRequest) (*GetUserStreamsUsageDetailResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/usage/streams"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	if r.from != nil {
		localVarQueryParams.Add("from", parameterToString(*r.from, ""))
	}
	if r.to != nil {
		localVarQueryParams.Add("to", parameterToString(*r.to, ""))
	}
	if r.offset != nil {
		localVarQueryParams.Add("offset", parameterToString(*r.offset, ""))
	}
	if r.limit != nil {
		localVarQueryParams.Add("limit", parameterToString(*r.limit, ""))
	}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetUserStreamsUsageDetailResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * UpdateLiveStreamKey Update live stream key
 * Update a live stream key by ID

 * @param id Live stream key ID
 * @return LiveStreamApiUpdateLiveStreamKeyRequest
 */

func (s *LiveStreamService) UpdateLiveStreamKey(id string, updateLiveStreamKeyRequest UpdateLiveStreamKeyRequest) (*UpdateLiveStreamKeyResponse, error) {

	return s.UpdateLiveStreamKeyWithContext(context.Background(), id, updateLiveStreamKeyRequest)

}

/*
 * UpdateLiveStreamKey Update live stream key
 * Update a live stream key by ID
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiUpdateLiveStreamKeyRequest
 */

func (s *LiveStreamService) UpdateLiveStreamKeyWithContext(ctx context.Context, id string, updateLiveStreamKeyRequest UpdateLiveStreamKeyRequest) (*UpdateLiveStreamKeyResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = updateLiveStreamKeyRequest

	req, err := s.client.prepareRequest(ctx, http.MethodPut, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(UpdateLiveStreamKeyResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * UpdateLiveStreamMedia Update live stream media
 * Update live stream media. You can only update while live streaming.

 * @param id Live stream key ID
 * @return LiveStreamApiUpdateLiveStreamMediaRequest
 */

func (s *LiveStreamService) UpdateLiveStreamMedia(id string, updateLiveStreamMediaRequest UpdateLiveStreamMediaRequest) (*ResponseSuccess, error) {

	return s.UpdateLiveStreamMediaWithContext(context.Background(), id, updateLiveStreamMediaRequest)

}

/*
 * UpdateLiveStreamMedia Update live stream media
 * Update live stream media. You can only update while live streaming.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiUpdateLiveStreamMediaRequest
 */

func (s *LiveStreamService) UpdateLiveStreamMediaWithContext(ctx context.Context, id string, updateLiveStreamMediaRequest UpdateLiveStreamMediaRequest) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/streamings"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = updateLiveStreamMediaRequest

	req, err := s.client.prepareRequest(ctx, http.MethodPut, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}
