/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
	"context"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
)

// Linger please
var (
	_ context.Context
)

// VideosService communicating with the Videos
// endpoints of the Aioz Stream API
type IUploadStream interface {
	UploadPart(fileName string, fileReader io.Reader, fileSize int64) (*Media, error)
	UploadPartWithContext(ctx context.Context, fileName string, fileReader io.Reader, fileSize int64) (*Media, error)
}

type MediaApiGetCaptionsRequest struct {
	offset *int32
	limit  *int32
}

func (r MediaApiGetCaptionsRequest) Offset(offset int32) MediaApiGetCaptionsRequest {
	r.offset = &offset
	return r
}
func (r MediaApiGetCaptionsRequest) Limit(limit int32) MediaApiGetCaptionsRequest {
	r.limit = &limit
	return r
}

type MediaApiGetMediaPlayerInfoRequest struct {
	token *string
}

func (r MediaApiGetMediaPlayerInfoRequest) Token(token string) MediaApiGetMediaPlayerInfoRequest {
	r.token = &token
	return r
}

type MediaServiceI interface {
	/*
	 * Create Create media object
	 * @return MediaApiCreateRequest
	 */

	Create(request CreateMediaRequest) (*CreateMediaResponse, error)

	/*
	 * Create Create media object
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return MediaApiCreateRequest
	 */

	CreateWithContext(ctx context.Context, request CreateMediaRequest) (*CreateMediaResponse, error)

	/*
	 * Update update media info
	 * @param id media's id
	 * @return MediaApiUpdateRequest
	 */

	Update(id string, input UpdateMediaInfoRequest) (*ResponseSuccess, error)

	/*
	 * Update update media info
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id media's id
	 * @return MediaApiUpdateRequest
	 */

	UpdateWithContext(ctx context.Context, id string, input UpdateMediaInfoRequest) (*ResponseSuccess, error)

	/*
	 * Delete Delete media
	 * @param id Media ID
	 * @return MediaApiDeleteRequest
	 */

	Delete(id string) (*ResponseSuccess, error)

	/*
	 * Delete Delete media
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Media ID
	 * @return MediaApiDeleteRequest
	 */

	DeleteWithContext(ctx context.Context, id string) (*ResponseSuccess, error)

	/*
	 * UploadThumbnail Upload media thumbnail
	 * @param id media's id
	 * @return MediaApiUploadThumbnailRequest
	 */
	UploadThumbnail(id string, fileName string, fileReader io.Reader) (*ResponseSuccess, error)
	/*
	 * UploadThumbnail Upload media thumbnail
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id media's id
	 * @return MediaApiUploadThumbnailRequest
	 */
	UploadThumbnailWithContext(ctx context.Context, id string, fileName string, fileReader io.Reader) (*ResponseSuccess, error)

	/*
	 * DeleteThumbnail Delete media thumbnail
	 * @param id media's id
	 * @return MediaApiDeleteThumbnailRequest
	 */

	DeleteThumbnail(id string) (*ResponseSuccess, error)

	/*
	 * DeleteThumbnail Delete media thumbnail
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id media's id
	 * @return MediaApiDeleteThumbnailRequest
	 */

	DeleteThumbnailWithContext(ctx context.Context, id string) (*ResponseSuccess, error)

	/*
	 * CreateCaption Create a new media caption
	 * @param id Media ID
	 * @param lan Language
	 * @return MediaApiCreateCaptionRequest
	 */
	CreateCaption(id string, lan string, fileName string, fileReader io.Reader) (*CreateMediaCaptionResponse, error)
	/*
	 * CreateCaption Create a new media caption
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Media ID
	 * @param lan Language
	 * @return MediaApiCreateCaptionRequest
	 */
	CreateCaptionWithContext(ctx context.Context, id string, lan string, fileName string, fileReader io.Reader) (*CreateMediaCaptionResponse, error)

	/*
	 * DeleteCaption Delete a media caption
	 * @param id Media ID
	 * @param lan Language
	 * @return MediaApiDeleteCaptionRequest
	 */

	DeleteCaption(id string, lan string) (*ResponseSuccess, error)

	/*
	 * DeleteCaption Delete a media caption
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Media ID
	 * @param lan Language
	 * @return MediaApiDeleteCaptionRequest
	 */

	DeleteCaptionWithContext(ctx context.Context, id string, lan string) (*ResponseSuccess, error)

	/*
	 * GetCaptions Get media captions
	 * @param id Media ID
	 * @return MediaApiGetCaptionsRequest
	 */

	GetCaptions(id string, r MediaApiGetCaptionsRequest) (*GetMediaCaptionsResponse, error)

	/*
	 * GetCaptions Get media captions
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Media ID
	 * @return MediaApiGetCaptionsRequest
	 */

	GetCaptionsWithContext(ctx context.Context, id string, r MediaApiGetCaptionsRequest) (*GetMediaCaptionsResponse, error)

	/*
	 * GetCost get media transcoding cost
	 * @return MediaApiGetCostRequest
	 */

	GetCost(qualities string, type_ string, duration float32) (*GetTranscodeCostResponse, error)

	/*
	 * GetCost get media transcoding cost
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return MediaApiGetCostRequest
	 */

	GetCostWithContext(ctx context.Context, qualities string, type_ string, duration float32) (*GetTranscodeCostResponse, error)

	/*
	 * GetDetail get media detail
	 * @param id mediav's id
	 * @return MediaApiGetDetailRequest
	 */

	GetDetail(id string) (*GetMediaDetailResponse, error)

	/*
	 * GetDetail get media detail
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id mediav's id
	 * @return MediaApiGetDetailRequest
	 */

	GetDetailWithContext(ctx context.Context, id string) (*GetMediaDetailResponse, error)

	/*
	 * GetMediaList Get user videos list
	 * @return MediaApiGetMediaListRequest
	 */

	GetMediaList(request GetMediaListRequest) (*GetMediaListResponse, error)

	/*
	 * GetMediaList Get user videos list
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return MediaApiGetMediaListRequest
	 */

	GetMediaListWithContext(ctx context.Context, request GetMediaListRequest) (*GetMediaListResponse, error)

	/*
	 * GetMediaPlayerInfo Get media object
	 * @param id media ID
	 * @return MediaApiGetMediaPlayerInfoRequest
	 */

	GetMediaPlayerInfo(id string, r MediaApiGetMediaPlayerInfoRequest) (*GetMediaPlayerInfoResponse, error)

	/*
	 * GetMediaPlayerInfo Get media object
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id media ID
	 * @return MediaApiGetMediaPlayerInfoRequest
	 */

	GetMediaPlayerInfoWithContext(ctx context.Context, id string, r MediaApiGetMediaPlayerInfoRequest) (*GetMediaPlayerInfoResponse, error)

	/*
	 * SetDefaultCaption Set default caption
	 * @param id Media ID
	 * @param lan Language
	 * @return MediaApiSetDefaultCaptionRequest
	 */

	SetDefaultCaption(id string, lan string) (*ResponseSuccess, error)

	/*
	 * SetDefaultCaption Set default caption
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Media ID
	 * @param lan Language
	 * @return MediaApiSetDefaultCaptionRequest
	 */

	SetDefaultCaptionWithContext(ctx context.Context, id string, lan string) (*ResponseSuccess, error)

	/*
	 * UploadMediaComplete Get upload media when complete
	 * @param id media's id
	 * @return MediaApiUploadMediaCompleteRequest
	 */

	UploadMediaComplete(id string) (*ResponseSuccess, error)

	/*
	 * UploadMediaComplete Get upload media when complete
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id media's id
	 * @return MediaApiUploadMediaCompleteRequest
	 */

	UploadMediaCompleteWithContext(ctx context.Context, id string) (*ResponseSuccess, error)

	/*
	 * UploadPart Upload part of media
	 * @param id video's id
	 * @return MediaApiUploadPartRequest
	 */
	UploadPart(id string, hash *string, index *string, fileName string, fileReader io.Reader, fileSize int64) (*ResponseSuccess, error)
	/*
	 * UploadPart Upload part of media
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id video's id
	 * @return MediaApiUploadPartRequest
	 */
	UploadPartWithContext(ctx context.Context, id string, hash *string, index *string, fileName string, fileReader io.Reader, fileSize int64) (*ResponseSuccess, error)
}

// MediaService communicating with the Media
// endpoints of the AIOZ Stream API
type MediaService struct {
	client *Client
}

/*
 * Create Create media object
 * Create a media object

 * @return MediaApiCreateRequest
 */

func (s *MediaService) Create(request CreateMediaRequest) (*CreateMediaResponse, error) {

	return s.CreateWithContext(context.Background(), request)

}

/*
 * Create Create media object
 * Create a media object
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return MediaApiCreateRequest
 */

func (s *MediaService) CreateWithContext(ctx context.Context, request CreateMediaRequest) (*CreateMediaResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/media/create"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = request

	req, err := s.client.prepareRequest(ctx, http.MethodPost, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(CreateMediaResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * Update update media info

 * @param id media's id
 * @return MediaApiUpdateRequest
 */

func (s *MediaService) Update(id string, input UpdateMediaInfoRequest) (*ResponseSuccess, error) {

	return s.UpdateWithContext(context.Background(), id, input)

}

/*
 * Update update media info
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id media's id
 * @return MediaApiUpdateRequest
 */

func (s *MediaService) UpdateWithContext(ctx context.Context, id string, input UpdateMediaInfoRequest) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/media/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = input

	req, err := s.client.prepareRequest(ctx, http.MethodPatch, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * Delete Delete media
 * Delete a media by media ID.

 * @param id Media ID
 * @return MediaApiDeleteRequest
 */

func (s *MediaService) Delete(id string) (*ResponseSuccess, error) {

	return s.DeleteWithContext(context.Background(), id)

}

/*
 * Delete Delete media
 * Delete a media by media ID.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Media ID
 * @return MediaApiDeleteRequest
 */

func (s *MediaService) DeleteWithContext(ctx context.Context, id string) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/media/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodDelete, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * UploadThumbnail Upload media thumbnail

 * @param id media's id
 * @return MediaApiUploadThumbnailRequest
 */

func (s *MediaService) UploadThumbnailFile(id string, file *os.File) (*ResponseSuccess, error) {
	return s.UploadThumbnailFileWithContext(context.Background(), id, file)
}

/*
 * UploadThumbnail Upload media thumbnail
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id media's id
 * @return MediaApiUploadThumbnailRequest
 */

func (s *MediaService) UploadThumbnailFileWithContext(ctx context.Context, id string, file *os.File) (*ResponseSuccess, error) {
	return s.UploadThumbnailWithContext(ctx, id, file.Name(), io.Reader(file))
}

/*
* UploadThumbnail Upload media thumbnail

* @param id media's id
* @return MediaApiUploadThumbnailRequest
 */
func (s *MediaService) UploadThumbnail(id string, fileName string, fileReader io.Reader) (*ResponseSuccess, error) {
	return s.UploadThumbnailWithContext(context.Background(), id, fileName, fileReader)
}

/*
 * UploadThumbnail Upload media thumbnail
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id media's id
 * @return MediaApiUploadThumbnailRequest
 */
func (s *MediaService) UploadThumbnailWithContext(ctx context.Context, id string, fileName string, fileReader io.Reader) (*ResponseSuccess, error) {
	localVarPath := "/media/{id}/thumbnail"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := make(map[string]string)

	req, err := s.client.prepareUploadRequest(ctx, http.MethodPost, localVarPath, fileName, fileReader, localVarHeaderParams, localVarQueryParams, localVarFormParams)

	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * DeleteThumbnail Delete media thumbnail

 * @param id media's id
 * @return MediaApiDeleteThumbnailRequest
 */

func (s *MediaService) DeleteThumbnail(id string) (*ResponseSuccess, error) {

	return s.DeleteThumbnailWithContext(context.Background(), id)

}

/*
 * DeleteThumbnail Delete media thumbnail
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id media's id
 * @return MediaApiDeleteThumbnailRequest
 */

func (s *MediaService) DeleteThumbnailWithContext(ctx context.Context, id string) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/media/{id}/thumbnail"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodDelete, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * CreateCaption Create a new media caption
 * Uploads a VTT file and creates a new media caption for the specified media.

 * @param id Media ID
 * @param lan Language
 * @return MediaApiCreateCaptionRequest
 */

func (s *MediaService) CreateCaptionFile(id string, lan string, file *os.File) (*CreateMediaCaptionResponse, error) {
	return s.CreateCaptionFileWithContext(context.Background(), id, lan, file)
}

/*
 * CreateCaption Create a new media caption
 * Uploads a VTT file and creates a new media caption for the specified media.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Media ID
 * @param lan Language
 * @return MediaApiCreateCaptionRequest
 */

func (s *MediaService) CreateCaptionFileWithContext(ctx context.Context, id string, lan string, file *os.File) (*CreateMediaCaptionResponse, error) {
	return s.CreateCaptionWithContext(ctx, id, lan, file.Name(), io.Reader(file))
}

/*
* CreateCaption Create a new media caption
* Uploads a VTT file and creates a new media caption for the specified media.

* @param id Media ID
* @param lan Language
* @return MediaApiCreateCaptionRequest
 */
func (s *MediaService) CreateCaption(id string, lan string, fileName string, fileReader io.Reader) (*CreateMediaCaptionResponse, error) {
	return s.CreateCaptionWithContext(context.Background(), id, lan, fileName, fileReader)
}

/*
 * CreateCaption Create a new media caption
 * Uploads a VTT file and creates a new media caption for the specified media.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Media ID
 * @param lan Language
 * @return MediaApiCreateCaptionRequest
 */
func (s *MediaService) CreateCaptionWithContext(ctx context.Context, id string, lan string, fileName string, fileReader io.Reader) (*CreateMediaCaptionResponse, error) {
	localVarPath := "/media/{id}/captions/{lan}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"lan"+"}", url.PathEscape(parameterToString(lan, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := make(map[string]string)

	req, err := s.client.prepareUploadRequest(ctx, http.MethodPost, localVarPath, fileName, fileReader, localVarHeaderParams, localVarQueryParams, localVarFormParams)

	if err != nil {
		return nil, err
	}

	res := new(CreateMediaCaptionResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * DeleteCaption Delete a media caption
 * Delete a caption in a specific language by providing the media ID for the media you want to delete the caption from and the language the caption is in.

 * @param id Media ID
 * @param lan Language
 * @return MediaApiDeleteCaptionRequest
 */

func (s *MediaService) DeleteCaption(id string, lan string) (*ResponseSuccess, error) {

	return s.DeleteCaptionWithContext(context.Background(), id, lan)

}

/*
 * DeleteCaption Delete a media caption
 * Delete a caption in a specific language by providing the media ID for the media you want to delete the caption from and the language the caption is in.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Media ID
 * @param lan Language
 * @return MediaApiDeleteCaptionRequest
 */

func (s *MediaService) DeleteCaptionWithContext(ctx context.Context, id string, lan string) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/media/{id}/captions/{lan}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"lan"+"}", url.PathEscape(parameterToString(lan, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodDelete, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetCaptions Get media captions
 * Retrieves a list of media captions for the specified media.

 * @param id Media ID
 * @return MediaApiGetCaptionsRequest
 */

func (s *MediaService) GetCaptions(id string, r MediaApiGetCaptionsRequest) (*GetMediaCaptionsResponse, error) {

	return s.GetCaptionsWithContext(context.Background(), id, r)

}

/*
 * GetCaptions Get media captions
 * Retrieves a list of media captions for the specified media.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Media ID
 * @return MediaApiGetCaptionsRequest
 */

func (s *MediaService) GetCaptionsWithContext(ctx context.Context, id string, r MediaApiGetCaptionsRequest) (*GetMediaCaptionsResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/media/{id}/captions"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	if r.offset != nil {
		localVarQueryParams.Add("offset", parameterToString(*r.offset, ""))
	}
	if r.limit != nil {
		localVarQueryParams.Add("limit", parameterToString(*r.limit, ""))
	}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetMediaCaptionsResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetCost get media transcoding cost
 * get media transcoding cost

 * @return MediaApiGetCostRequest
 */

func (s *MediaService) GetCost(qualities string, type_ string, duration float32) (*GetTranscodeCostResponse, error) {

	return s.GetCostWithContext(context.Background(), qualities, type_, duration)

}

/*
 * GetCost get media transcoding cost
 * get media transcoding cost
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return MediaApiGetCostRequest
 */

func (s *MediaService) GetCostWithContext(ctx context.Context, qualities string, type_ string, duration float32) (*GetTranscodeCostResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/media/cost"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	localVarQueryParams.Add("qualities", parameterToString(qualities, ""))
	localVarQueryParams.Add("type", parameterToString(type_, ""))
	localVarQueryParams.Add("duration", parameterToString(duration, ""))

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetTranscodeCostResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetDetail get media detail
 * Retrieve the media details by media id.

 * @param id mediav's id
 * @return MediaApiGetDetailRequest
 */

func (s *MediaService) GetDetail(id string) (*GetMediaDetailResponse, error) {

	return s.GetDetailWithContext(context.Background(), id)

}

/*
 * GetDetail get media detail
 * Retrieve the media details by media id.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id mediav's id
 * @return MediaApiGetDetailRequest
 */

func (s *MediaService) GetDetailWithContext(ctx context.Context, id string) (*GetMediaDetailResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/media/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetMediaDetailResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetMediaList Get user videos list
 * Retrieve a list of videos for the authenticated user.

 * @return MediaApiGetMediaListRequest
 */

func (s *MediaService) GetMediaList(request GetMediaListRequest) (*GetMediaListResponse, error) {

	return s.GetMediaListWithContext(context.Background(), request)

}

/*
 * GetMediaList Get user videos list
 * Retrieve a list of videos for the authenticated user.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return MediaApiGetMediaListRequest
 */

func (s *MediaService) GetMediaListWithContext(ctx context.Context, request GetMediaListRequest) (*GetMediaListResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/media"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = request

	req, err := s.client.prepareRequest(ctx, http.MethodPost, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetMediaListResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetMediaPlayerInfo Get media object
 * Get media object

 * @param id media ID
 * @return MediaApiGetMediaPlayerInfoRequest
 */

func (s *MediaService) GetMediaPlayerInfo(id string, r MediaApiGetMediaPlayerInfoRequest) (*GetMediaPlayerInfoResponse, error) {

	return s.GetMediaPlayerInfoWithContext(context.Background(), id, r)

}

/*
 * GetMediaPlayerInfo Get media object
 * Get media object
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id media ID
 * @return MediaApiGetMediaPlayerInfoRequest
 */

func (s *MediaService) GetMediaPlayerInfoWithContext(ctx context.Context, id string, r MediaApiGetMediaPlayerInfoRequest) (*GetMediaPlayerInfoResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/media/{id}/player.json"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	if r.token != nil {
		localVarQueryParams.Add("token", parameterToString(*r.token, ""))
	}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetMediaPlayerInfoResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * SetDefaultCaption Set default caption
 * Set default caption for a media

 * @param id Media ID
 * @param lan Language
 * @return MediaApiSetDefaultCaptionRequest
 */

func (s *MediaService) SetDefaultCaption(id string, lan string) (*ResponseSuccess, error) {

	return s.SetDefaultCaptionWithContext(context.Background(), id, lan)

}

/*
 * SetDefaultCaption Set default caption
 * Set default caption for a media
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Media ID
 * @param lan Language
 * @return MediaApiSetDefaultCaptionRequest
 */

func (s *MediaService) SetDefaultCaptionWithContext(ctx context.Context, id string, lan string) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/media/{id}/captions/{lan}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"lan"+"}", url.PathEscape(parameterToString(lan, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodPatch, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * UploadMediaComplete Get upload media when complete
 * Get upload media when complete.

 * @param id media's id
 * @return MediaApiUploadMediaCompleteRequest
 */

func (s *MediaService) UploadMediaComplete(id string) (*ResponseSuccess, error) {

	return s.UploadMediaCompleteWithContext(context.Background(), id)

}

/*
 * UploadMediaComplete Get upload media when complete
 * Get upload media when complete.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id media's id
 * @return MediaApiUploadMediaCompleteRequest
 */

func (s *MediaService) UploadMediaCompleteWithContext(ctx context.Context, id string) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/media/{id}/complete"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * UploadPart Upload part of media
 * Upload part of media

 * @param id video's id
 * @return MediaApiUploadPartRequest
 */

func (s *MediaService) UploadPartFile(id string, file *os.File, hash *string, index *string) (*ResponseSuccess, error) {
	return s.UploadPartFileWithContext(context.Background(), id, file, hash, index)
}

/*
 * UploadPart Upload part of media
 * Upload part of media
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id video's id
 * @return MediaApiUploadPartRequest
 */

func (s *MediaService) UploadPartFileWithContext(ctx context.Context, id string, file *os.File, hash *string, index *string) (*ResponseSuccess, error) {
	fileInfo, _ := file.Stat()
	fileSize := fileInfo.Size()

	return s.UploadPartWithContext(ctx, id, hash, index, file.Name(), io.Reader(file), fileSize)
}

// VideosService communicating with the Videos
// endpoints of the AIOZ Stream API
type UploadPartStream struct {
	client *Client
	id     string
	hash   *string
	index  *string
	part   int32
}

func (s *MediaService) CreateUploadPartStream(id string, hash *string, index *string) (IUploadStream, error) {
	return &UploadPartStream{client: s.client, id: id, hash: hash, index: index, part: 1}, nil
}

func (s *UploadPartStream) UploadAPart(ctx context.Context, fileName string, fileReader io.Reader, fileSize int64, isLast bool) (*Media, error) {
	localVarPath := "/media/{id}/part"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(s.id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := make(map[string]string)

	request, err := s.client.prepareProgressiveUploadRequest(context.Background(), localVarPath, fileName, fileReader, fileSize, localVarHeaderParams, localVarQueryParams, localVarFormParams, s.part, isLast)

	if err != nil {
		return nil, err
	}

	s.part = s.part + 1

	res := new(Media)

	_, err = s.client.do(request, res)
	if err != nil {
		return nil, err
	}

	return res, nil
}
func (s *UploadPartStream) UploadPartWithContext(ctx context.Context, fileName string, fileReader io.Reader, fileSize int64) (*Media, error) {
	return s.UploadAPart(ctx, fileName, fileReader, fileSize, false)
}
func (s *UploadPartStream) UploadLastPartWithContext(ctx context.Context, fileName string, fileReader io.Reader, fileSize int64) (*Media, error) {
	return s.UploadAPart(ctx, fileName, fileReader, fileSize, true)
}
func (s *UploadPartStream) UploadPart(fileName string, fileReader io.Reader, fileSize int64) (*Media, error) {
	return s.UploadPartWithContext(context.Background(), fileName, fileReader, fileSize)
}
func (s *UploadPartStream) UploadPartFile(file *os.File) (*Media, error) {
	return s.UploadPartWithContextFile(context.Background(), file)
}
func (s *UploadPartStream) UploadPartWithContextFile(ctx context.Context, file *os.File) (*Media, error) {
	fileInfo, _ := file.Stat()
	fileSize := fileInfo.Size()

	return s.UploadPartWithContext(ctx, file.Name(), io.Reader(file), fileSize)
}
func (s *UploadPartStream) UploadLastPart(fileName string, fileReader io.Reader, fileSize int64) (*Media, error) {
	return s.UploadLastPartWithContext(context.Background(), fileName, fileReader, fileSize)
}
func (s *UploadPartStream) UploadLastPartFile(file *os.File) (*Media, error) {
	return s.UploadLastPartWithContextFile(context.Background(), file)
}
func (s *UploadPartStream) UploadLastPartWithContextFile(ctx context.Context, file *os.File) (*Media, error) {
	fileInfo, _ := file.Stat()
	fileSize := fileInfo.Size()

	return s.UploadLastPartWithContext(ctx, file.Name(), io.Reader(file), fileSize)
}

/*
* UploadPart Upload part of media
* Upload part of media

* @param id video's id
* @return MediaApiUploadPartRequest
 */
func (s *MediaService) UploadPart(id string, hash *string, index *string, fileName string, fileReader io.Reader, fileSize int64) (*ResponseSuccess, error) {
	return s.UploadPartWithContext(context.Background(), id, hash, index, fileName, fileReader, fileSize)
}

/*
 * UploadPart Upload part of media
 * Upload part of media
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id video's id
 * @return MediaApiUploadPartRequest
 */
func (s *MediaService) UploadPartWithContext(ctx context.Context, id string, hash *string, index *string, fileName string, fileReader io.Reader, fileSize int64) (*ResponseSuccess, error) {
	localVarPath := "/media/{id}/part"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := make(map[string]string)

	if hash != nil {
		localVarFormParams["hash"] = parameterToString(*hash, "")
	}
	if index != nil {
		localVarFormParams["index"] = parameterToString(*index, "")
	}

	requests, err := s.client.prepareRangeRequests(ctx, localVarPath, fileName, fileReader, fileSize, localVarHeaderParams, localVarQueryParams, localVarFormParams)

	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	for _, req := range requests {
		_, err = s.client.do(req, res)

		if err != nil {
			return nil, err
		}
	}

	return res, nil

}
