/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// DataUsage struct for DataUsage
type DataUsage struct {
	CreatedAt *string `json:"created_at,omitempty"`
	Delivery  *int32  `json:"delivery,omitempty"`
	UserId    *string `json:"user_id,omitempty"`
}

// NewDataUsage instantiates a new DataUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataUsage() *DataUsage {
	this := DataUsage{}
	return &this
}

// NewDataUsageWithDefaults instantiates a new DataUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataUsageWithDefaults() *DataUsage {
	this := DataUsage{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DataUsage) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataUsage) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DataUsage) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *DataUsage) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDelivery returns the Delivery field value if set, zero value otherwise.
func (o *DataUsage) GetDelivery() int32 {
	if o == nil || o.Delivery == nil {
		var ret int32
		return ret
	}
	return *o.Delivery
}

// GetDeliveryOk returns a tuple with the Delivery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataUsage) GetDeliveryOk() (*int32, bool) {
	if o == nil || o.Delivery == nil {
		return nil, false
	}
	return o.Delivery, true
}

// HasDelivery returns a boolean if a field has been set.
func (o *DataUsage) HasDelivery() bool {
	if o != nil && o.Delivery != nil {
		return true
	}

	return false
}

// SetDelivery gets a reference to the given int32 and assigns it to the Delivery field.
func (o *DataUsage) SetDelivery(v int32) {
	o.Delivery = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *DataUsage) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataUsage) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *DataUsage) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *DataUsage) SetUserId(v string) {
	o.UserId = &v
}

type NullableDataUsage struct {
	value *DataUsage
	isSet bool
}

func (v NullableDataUsage) Get() *DataUsage {
	return v.value
}

func (v *NullableDataUsage) Set(val *DataUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableDataUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableDataUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataUsage(val *DataUsage) *NullableDataUsage {
	return &NullableDataUsage{value: val, isSet: true}
}
