/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// MeData struct for MeData
type MeData struct {
	User *User `json:"user,omitempty"`
}

// NewMeData instantiates a new MeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeData() *MeData {
	this := MeData{}
	return &this
}

// NewMeDataWithDefaults instantiates a new MeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeDataWithDefaults() *MeData {
	this := MeData{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *MeData) GetUser() User {
	if o == nil || o.User == nil {
		var ret User
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeData) GetUserOk() (*User, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *MeData) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given User and assigns it to the User field.
func (o *MeData) SetUser(v User) {
	o.User = &v
}

type NullableMeData struct {
	value *MeData
	isSet bool
}

func (v NullableMeData) Get() *MeData {
	return v.value
}

func (v *NullableMeData) Set(val *MeData) {
	v.value = val
	v.isSet = true
}

func (v NullableMeData) IsSet() bool {
	return v.isSet
}

func (v *NullableMeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeData(val *MeData) *NullableMeData {
	return &NullableMeData{value: val, isSet: true}
}
