/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// GetBreakdownMetricsData struct for GetBreakdownMetricsData
type GetBreakdownMetricsData struct {
	Context *MetricsContext `json:"context,omitempty"`
	Data    *[]MetricItem   `json:"data,omitempty"`
	Total   *int32          `json:"total,omitempty"`
}

// NewGetBreakdownMetricsData instantiates a new GetBreakdownMetricsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBreakdownMetricsData() *GetBreakdownMetricsData {
	this := GetBreakdownMetricsData{}
	return &this
}

// NewGetBreakdownMetricsDataWithDefaults instantiates a new GetBreakdownMetricsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBreakdownMetricsDataWithDefaults() *GetBreakdownMetricsData {
	this := GetBreakdownMetricsData{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *GetBreakdownMetricsData) GetContext() MetricsContext {
	if o == nil || o.Context == nil {
		var ret MetricsContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsData) GetContextOk() (*MetricsContext, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *GetBreakdownMetricsData) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given MetricsContext and assigns it to the Context field.
func (o *GetBreakdownMetricsData) SetContext(v MetricsContext) {
	o.Context = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetBreakdownMetricsData) GetData() []MetricItem {
	if o == nil || o.Data == nil {
		var ret []MetricItem
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsData) GetDataOk() (*[]MetricItem, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetBreakdownMetricsData) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []MetricItem and assigns it to the Data field.
func (o *GetBreakdownMetricsData) SetData(v []MetricItem) {
	o.Data = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetBreakdownMetricsData) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsData) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetBreakdownMetricsData) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetBreakdownMetricsData) SetTotal(v int32) {
	o.Total = &v
}

type NullableGetBreakdownMetricsData struct {
	value *GetBreakdownMetricsData
	isSet bool
}

func (v NullableGetBreakdownMetricsData) Get() *GetBreakdownMetricsData {
	return v.value
}

func (v *NullableGetBreakdownMetricsData) Set(val *GetBreakdownMetricsData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBreakdownMetricsData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBreakdownMetricsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBreakdownMetricsData(val *GetBreakdownMetricsData) *NullableGetBreakdownMetricsData {
	return &NullableGetBreakdownMetricsData{value: val, isSet: true}
}
