/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// HighlightManifest struct for HighlightManifest
type HighlightManifest struct {
	CreatedAt    *string                 `json:"created_at,omitempty"`
	DeletedAt    *DeletedAt              `json:"deleted_at,omitempty"`
	Id           *string                 `json:"id,omitempty"`
	ManifestType *ManifestType           `json:"manifest_type,omitempty"`
	MediaId      *string                 `json:"media_id,omitempty"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	UpdatedAt    *string                 `json:"updated_at,omitempty"`
}

// NewHighlightManifest instantiates a new HighlightManifest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHighlightManifest() *HighlightManifest {
	this := HighlightManifest{}
	return &this
}

// NewHighlightManifestWithDefaults instantiates a new HighlightManifest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHighlightManifestWithDefaults() *HighlightManifest {
	this := HighlightManifest{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *HighlightManifest) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighlightManifest) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *HighlightManifest) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *HighlightManifest) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *HighlightManifest) GetDeletedAt() DeletedAt {
	if o == nil || o.DeletedAt == nil {
		var ret DeletedAt
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighlightManifest) GetDeletedAtOk() (*DeletedAt, bool) {
	if o == nil || o.DeletedAt == nil {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *HighlightManifest) HasDeletedAt() bool {
	if o != nil && o.DeletedAt != nil {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given DeletedAt and assigns it to the DeletedAt field.
func (o *HighlightManifest) SetDeletedAt(v DeletedAt) {
	o.DeletedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *HighlightManifest) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighlightManifest) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *HighlightManifest) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *HighlightManifest) SetId(v string) {
	o.Id = &v
}

// GetManifestType returns the ManifestType field value if set, zero value otherwise.
func (o *HighlightManifest) GetManifestType() ManifestType {
	if o == nil || o.ManifestType == nil {
		var ret ManifestType
		return ret
	}
	return *o.ManifestType
}

// GetManifestTypeOk returns a tuple with the ManifestType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighlightManifest) GetManifestTypeOk() (*ManifestType, bool) {
	if o == nil || o.ManifestType == nil {
		return nil, false
	}
	return o.ManifestType, true
}

// HasManifestType returns a boolean if a field has been set.
func (o *HighlightManifest) HasManifestType() bool {
	if o != nil && o.ManifestType != nil {
		return true
	}

	return false
}

// SetManifestType gets a reference to the given ManifestType and assigns it to the ManifestType field.
func (o *HighlightManifest) SetManifestType(v ManifestType) {
	o.ManifestType = &v
}

// GetMediaId returns the MediaId field value if set, zero value otherwise.
func (o *HighlightManifest) GetMediaId() string {
	if o == nil || o.MediaId == nil {
		var ret string
		return ret
	}
	return *o.MediaId
}

// GetMediaIdOk returns a tuple with the MediaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighlightManifest) GetMediaIdOk() (*string, bool) {
	if o == nil || o.MediaId == nil {
		return nil, false
	}
	return o.MediaId, true
}

// HasMediaId returns a boolean if a field has been set.
func (o *HighlightManifest) HasMediaId() bool {
	if o != nil && o.MediaId != nil {
		return true
	}

	return false
}

// SetMediaId gets a reference to the given string and assigns it to the MediaId field.
func (o *HighlightManifest) SetMediaId(v string) {
	o.MediaId = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *HighlightManifest) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighlightManifest) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *HighlightManifest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *HighlightManifest) SetMetadata(v map[string]interface{}) {
	o.Metadata = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *HighlightManifest) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighlightManifest) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *HighlightManifest) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *HighlightManifest) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

type NullableHighlightManifest struct {
	value *HighlightManifest
	isSet bool
}

func (v NullableHighlightManifest) Get() *HighlightManifest {
	return v.value
}

func (v *NullableHighlightManifest) Set(val *HighlightManifest) {
	v.value = val
	v.isSet = true
}

func (v NullableHighlightManifest) IsSet() bool {
	return v.isSet
}

func (v *NullableHighlightManifest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHighlightManifest(val *HighlightManifest) *NullableHighlightManifest {
	return &NullableHighlightManifest{value: val, isSet: true}
}
