/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// GetDataUsageData struct for GetDataUsageData
type GetDataUsageData struct {
	Data  *[]DataUsage `json:"data,omitempty"`
	Total *int32       `json:"total,omitempty"`
}

// NewGetDataUsageData instantiates a new GetDataUsageData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDataUsageData() *GetDataUsageData {
	this := GetDataUsageData{}
	return &this
}

// NewGetDataUsageDataWithDefaults instantiates a new GetDataUsageData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDataUsageDataWithDefaults() *GetDataUsageData {
	this := GetDataUsageData{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetDataUsageData) GetData() []DataUsage {
	if o == nil || o.Data == nil {
		var ret []DataUsage
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDataUsageData) GetDataOk() (*[]DataUsage, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetDataUsageData) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []DataUsage and assigns it to the Data field.
func (o *GetDataUsageData) SetData(v []DataUsage) {
	o.Data = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetDataUsageData) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDataUsageData) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetDataUsageData) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetDataUsageData) SetTotal(v int32) {
	o.Total = &v
}

type NullableGetDataUsageData struct {
	value *GetDataUsageData
	isSet bool
}

func (v NullableGetDataUsageData) Get() *GetDataUsageData {
	return v.value
}

func (v *NullableGetDataUsageData) Set(val *GetDataUsageData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDataUsageData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDataUsageData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDataUsageData(val *GetDataUsageData) *NullableGetDataUsageData {
	return &NullableGetDataUsageData{value: val, isSet: true}
}
