/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// GetBreakdownMetricsRequest struct for GetBreakdownMetricsRequest
type GetBreakdownMetricsRequest struct {
	FilterBy  *MetricFilter `json:"filter_by,omitempty"`
	From      *int32        `json:"from,omitempty"`
	Limit     *int32        `json:"limit,omitempty"`
	Offset    *int32        `json:"offset,omitempty"`
	OrderBy   *string       `json:"order_by,omitempty"`
	SortBy    *string       `json:"sort_by,omitempty"`
	SumOthers *bool         `json:"sum_others,omitempty"`
	To        *int32        `json:"to,omitempty"`
}

// NewGetBreakdownMetricsRequest instantiates a new GetBreakdownMetricsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBreakdownMetricsRequest() *GetBreakdownMetricsRequest {
	this := GetBreakdownMetricsRequest{}
	return &this
}

// NewGetBreakdownMetricsRequestWithDefaults instantiates a new GetBreakdownMetricsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBreakdownMetricsRequestWithDefaults() *GetBreakdownMetricsRequest {
	this := GetBreakdownMetricsRequest{}
	return &this
}

// GetFilterBy returns the FilterBy field value if set, zero value otherwise.
func (o *GetBreakdownMetricsRequest) GetFilterBy() MetricFilter {
	if o == nil || o.FilterBy == nil {
		var ret MetricFilter
		return ret
	}
	return *o.FilterBy
}

// GetFilterByOk returns a tuple with the FilterBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsRequest) GetFilterByOk() (*MetricFilter, bool) {
	if o == nil || o.FilterBy == nil {
		return nil, false
	}
	return o.FilterBy, true
}

// HasFilterBy returns a boolean if a field has been set.
func (o *GetBreakdownMetricsRequest) HasFilterBy() bool {
	if o != nil && o.FilterBy != nil {
		return true
	}

	return false
}

// SetFilterBy gets a reference to the given MetricFilter and assigns it to the FilterBy field.
func (o *GetBreakdownMetricsRequest) SetFilterBy(v MetricFilter) {
	o.FilterBy = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *GetBreakdownMetricsRequest) GetFrom() int32 {
	if o == nil || o.From == nil {
		var ret int32
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsRequest) GetFromOk() (*int32, bool) {
	if o == nil || o.From == nil {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *GetBreakdownMetricsRequest) HasFrom() bool {
	if o != nil && o.From != nil {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int32 and assigns it to the From field.
func (o *GetBreakdownMetricsRequest) SetFrom(v int32) {
	o.From = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *GetBreakdownMetricsRequest) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsRequest) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *GetBreakdownMetricsRequest) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *GetBreakdownMetricsRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *GetBreakdownMetricsRequest) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *GetBreakdownMetricsRequest) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *GetBreakdownMetricsRequest) SetOffset(v int32) {
	o.Offset = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *GetBreakdownMetricsRequest) GetOrderBy() string {
	if o == nil || o.OrderBy == nil {
		var ret string
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsRequest) GetOrderByOk() (*string, bool) {
	if o == nil || o.OrderBy == nil {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *GetBreakdownMetricsRequest) HasOrderBy() bool {
	if o != nil && o.OrderBy != nil {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given string and assigns it to the OrderBy field.
func (o *GetBreakdownMetricsRequest) SetOrderBy(v string) {
	o.OrderBy = &v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *GetBreakdownMetricsRequest) GetSortBy() string {
	if o == nil || o.SortBy == nil {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsRequest) GetSortByOk() (*string, bool) {
	if o == nil || o.SortBy == nil {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *GetBreakdownMetricsRequest) HasSortBy() bool {
	if o != nil && o.SortBy != nil {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *GetBreakdownMetricsRequest) SetSortBy(v string) {
	o.SortBy = &v
}

// GetSumOthers returns the SumOthers field value if set, zero value otherwise.
func (o *GetBreakdownMetricsRequest) GetSumOthers() bool {
	if o == nil || o.SumOthers == nil {
		var ret bool
		return ret
	}
	return *o.SumOthers
}

// GetSumOthersOk returns a tuple with the SumOthers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsRequest) GetSumOthersOk() (*bool, bool) {
	if o == nil || o.SumOthers == nil {
		return nil, false
	}
	return o.SumOthers, true
}

// HasSumOthers returns a boolean if a field has been set.
func (o *GetBreakdownMetricsRequest) HasSumOthers() bool {
	if o != nil && o.SumOthers != nil {
		return true
	}

	return false
}

// SetSumOthers gets a reference to the given bool and assigns it to the SumOthers field.
func (o *GetBreakdownMetricsRequest) SetSumOthers(v bool) {
	o.SumOthers = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *GetBreakdownMetricsRequest) GetTo() int32 {
	if o == nil || o.To == nil {
		var ret int32
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsRequest) GetToOk() (*int32, bool) {
	if o == nil || o.To == nil {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *GetBreakdownMetricsRequest) HasTo() bool {
	if o != nil && o.To != nil {
		return true
	}

	return false
}

// SetTo gets a reference to the given int32 and assigns it to the To field.
func (o *GetBreakdownMetricsRequest) SetTo(v int32) {
	o.To = &v
}

type NullableGetBreakdownMetricsRequest struct {
	value *GetBreakdownMetricsRequest
	isSet bool
}

func (v NullableGetBreakdownMetricsRequest) Get() *GetBreakdownMetricsRequest {
	return v.value
}

func (v *NullableGetBreakdownMetricsRequest) Set(val *GetBreakdownMetricsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBreakdownMetricsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBreakdownMetricsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBreakdownMetricsRequest(val *GetBreakdownMetricsRequest) *NullableGetBreakdownMetricsRequest {
	return &NullableGetBreakdownMetricsRequest{value: val, isSet: true}
}
