/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// AddMediaRequest struct for AddMediaRequest
type AddMediaRequest struct {
	MediaId         *string   `json:"media_id,omitempty"`
	OptionMediaIds  *[]string `json:"option_media_ids,omitempty"`
	OptionPlaylists *[]string `json:"option_playlists,omitempty"`
}

// NewAddMediaRequest instantiates a new AddMediaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddMediaRequest() *AddMediaRequest {
	this := AddMediaRequest{}
	return &this
}

// NewAddMediaRequestWithDefaults instantiates a new AddMediaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddMediaRequestWithDefaults() *AddMediaRequest {
	this := AddMediaRequest{}
	return &this
}

// GetMediaId returns the MediaId field value if set, zero value otherwise.
func (o *AddMediaRequest) GetMediaId() string {
	if o == nil || o.MediaId == nil {
		var ret string
		return ret
	}
	return *o.MediaId
}

// GetMediaIdOk returns a tuple with the MediaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddMediaRequest) GetMediaIdOk() (*string, bool) {
	if o == nil || o.MediaId == nil {
		return nil, false
	}
	return o.MediaId, true
}

// HasMediaId returns a boolean if a field has been set.
func (o *AddMediaRequest) HasMediaId() bool {
	if o != nil && o.MediaId != nil {
		return true
	}

	return false
}

// SetMediaId gets a reference to the given string and assigns it to the MediaId field.
func (o *AddMediaRequest) SetMediaId(v string) {
	o.MediaId = &v
}

// GetOptionMediaIds returns the OptionMediaIds field value if set, zero value otherwise.
func (o *AddMediaRequest) GetOptionMediaIds() []string {
	if o == nil || o.OptionMediaIds == nil {
		var ret []string
		return ret
	}
	return *o.OptionMediaIds
}

// GetOptionMediaIdsOk returns a tuple with the OptionMediaIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddMediaRequest) GetOptionMediaIdsOk() (*[]string, bool) {
	if o == nil || o.OptionMediaIds == nil {
		return nil, false
	}
	return o.OptionMediaIds, true
}

// HasOptionMediaIds returns a boolean if a field has been set.
func (o *AddMediaRequest) HasOptionMediaIds() bool {
	if o != nil && o.OptionMediaIds != nil {
		return true
	}

	return false
}

// SetOptionMediaIds gets a reference to the given []string and assigns it to the OptionMediaIds field.
func (o *AddMediaRequest) SetOptionMediaIds(v []string) {
	o.OptionMediaIds = &v
}

// GetOptionPlaylists returns the OptionPlaylists field value if set, zero value otherwise.
func (o *AddMediaRequest) GetOptionPlaylists() []string {
	if o == nil || o.OptionPlaylists == nil {
		var ret []string
		return ret
	}
	return *o.OptionPlaylists
}

// GetOptionPlaylistsOk returns a tuple with the OptionPlaylists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddMediaRequest) GetOptionPlaylistsOk() (*[]string, bool) {
	if o == nil || o.OptionPlaylists == nil {
		return nil, false
	}
	return o.OptionPlaylists, true
}

// HasOptionPlaylists returns a boolean if a field has been set.
func (o *AddMediaRequest) HasOptionPlaylists() bool {
	if o != nil && o.OptionPlaylists != nil {
		return true
	}

	return false
}

// SetOptionPlaylists gets a reference to the given []string and assigns it to the OptionPlaylists field.
func (o *AddMediaRequest) SetOptionPlaylists(v []string) {
	o.OptionPlaylists = &v
}

type NullableAddMediaRequest struct {
	value *AddMediaRequest
	isSet bool
}

func (v NullableAddMediaRequest) Get() *AddMediaRequest {
	return v.value
}

func (v *NullableAddMediaRequest) Set(val *AddMediaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddMediaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddMediaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddMediaRequest(val *AddMediaRequest) *NullableAddMediaRequest {
	return &NullableAddMediaRequest{value: val, isSet: true}
}
