/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// GetMediaCaptionsData struct for GetMediaCaptionsData
type GetMediaCaptionsData struct {
	MediaCaptions *[]MediaCaption `json:"media_captions,omitempty"`
	Total         *int32          `json:"total,omitempty"`
}

// NewGetMediaCaptionsData instantiates a new GetMediaCaptionsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMediaCaptionsData() *GetMediaCaptionsData {
	this := GetMediaCaptionsData{}
	return &this
}

// NewGetMediaCaptionsDataWithDefaults instantiates a new GetMediaCaptionsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMediaCaptionsDataWithDefaults() *GetMediaCaptionsData {
	this := GetMediaCaptionsData{}
	return &this
}

// GetMediaCaptions returns the MediaCaptions field value if set, zero value otherwise.
func (o *GetMediaCaptionsData) GetMediaCaptions() []MediaCaption {
	if o == nil || o.MediaCaptions == nil {
		var ret []MediaCaption
		return ret
	}
	return *o.MediaCaptions
}

// GetMediaCaptionsOk returns a tuple with the MediaCaptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaCaptionsData) GetMediaCaptionsOk() (*[]MediaCaption, bool) {
	if o == nil || o.MediaCaptions == nil {
		return nil, false
	}
	return o.MediaCaptions, true
}

// HasMediaCaptions returns a boolean if a field has been set.
func (o *GetMediaCaptionsData) HasMediaCaptions() bool {
	if o != nil && o.MediaCaptions != nil {
		return true
	}

	return false
}

// SetMediaCaptions gets a reference to the given []MediaCaption and assigns it to the MediaCaptions field.
func (o *GetMediaCaptionsData) SetMediaCaptions(v []MediaCaption) {
	o.MediaCaptions = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetMediaCaptionsData) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaCaptionsData) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetMediaCaptionsData) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetMediaCaptionsData) SetTotal(v int32) {
	o.Total = &v
}

type NullableGetMediaCaptionsData struct {
	value *GetMediaCaptionsData
	isSet bool
}

func (v NullableGetMediaCaptionsData) Get() *GetMediaCaptionsData {
	return v.value
}

func (v *NullableGetMediaCaptionsData) Set(val *GetMediaCaptionsData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMediaCaptionsData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMediaCaptionsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMediaCaptionsData(val *GetMediaCaptionsData) *NullableGetMediaCaptionsData {
	return &NullableGetMediaCaptionsData{value: val, isSet: true}
}
