/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// VideoCropInfo struct for VideoCropInfo
type VideoCropInfo struct {
	Height *int64 `json:"height,omitempty"`
	Width  *int64 `json:"width,omitempty"`
	X      *int64 `json:"x,omitempty"`
	Y      *int64 `json:"y,omitempty"`
}

// NewVideoCropInfo instantiates a new VideoCropInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoCropInfo() *VideoCropInfo {
	this := VideoCropInfo{}
	return &this
}

// NewVideoCropInfoWithDefaults instantiates a new VideoCropInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoCropInfoWithDefaults() *VideoCropInfo {
	this := VideoCropInfo{}
	return &this
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *VideoCropInfo) GetHeight() int64 {
	if o == nil || o.Height == nil {
		var ret int64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCropInfo) GetHeightOk() (*int64, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *VideoCropInfo) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int64 and assigns it to the Height field.
func (o *VideoCropInfo) SetHeight(v int64) {
	o.Height = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *VideoCropInfo) GetWidth() int64 {
	if o == nil || o.Width == nil {
		var ret int64
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCropInfo) GetWidthOk() (*int64, bool) {
	if o == nil || o.Width == nil {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *VideoCropInfo) HasWidth() bool {
	if o != nil && o.Width != nil {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int64 and assigns it to the Width field.
func (o *VideoCropInfo) SetWidth(v int64) {
	o.Width = &v
}

// GetX returns the X field value if set, zero value otherwise.
func (o *VideoCropInfo) GetX() int64 {
	if o == nil || o.X == nil {
		var ret int64
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCropInfo) GetXOk() (*int64, bool) {
	if o == nil || o.X == nil {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *VideoCropInfo) HasX() bool {
	if o != nil && o.X != nil {
		return true
	}

	return false
}

// SetX gets a reference to the given int64 and assigns it to the X field.
func (o *VideoCropInfo) SetX(v int64) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *VideoCropInfo) GetY() int64 {
	if o == nil || o.Y == nil {
		var ret int64
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoCropInfo) GetYOk() (*int64, bool) {
	if o == nil || o.Y == nil {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *VideoCropInfo) HasY() bool {
	if o != nil && o.Y != nil {
		return true
	}

	return false
}

// SetY gets a reference to the given int64 and assigns it to the Y field.
func (o *VideoCropInfo) SetY(v int64) {
	o.Y = &v
}

type NullableVideoCropInfo struct {
	value *VideoCropInfo
	isSet bool
}

func (v NullableVideoCropInfo) Get() *VideoCropInfo {
	return v.value
}

func (v *NullableVideoCropInfo) Set(val *VideoCropInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoCropInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoCropInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoCropInfo(val *VideoCropInfo) *NullableVideoCropInfo {
	return &NullableVideoCropInfo{value: val, isSet: true}
}
