/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// GetMediaChaptersData struct for GetMediaChaptersData
type GetMediaChaptersData struct {
	MediaChapters *[]MediaChapter `json:"media_chapters,omitempty"`
	Total         *int64          `json:"total,omitempty"`
}

// NewGetMediaChaptersData instantiates a new GetMediaChaptersData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMediaChaptersData() *GetMediaChaptersData {
	this := GetMediaChaptersData{}
	return &this
}

// NewGetMediaChaptersDataWithDefaults instantiates a new GetMediaChaptersData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMediaChaptersDataWithDefaults() *GetMediaChaptersData {
	this := GetMediaChaptersData{}
	return &this
}

// GetMediaChapters returns the MediaChapters field value if set, zero value otherwise.
func (o *GetMediaChaptersData) GetMediaChapters() []MediaChapter {
	if o == nil || o.MediaChapters == nil {
		var ret []MediaChapter
		return ret
	}
	return *o.MediaChapters
}

// GetMediaChaptersOk returns a tuple with the MediaChapters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaChaptersData) GetMediaChaptersOk() (*[]MediaChapter, bool) {
	if o == nil || o.MediaChapters == nil {
		return nil, false
	}
	return o.MediaChapters, true
}

// HasMediaChapters returns a boolean if a field has been set.
func (o *GetMediaChaptersData) HasMediaChapters() bool {
	if o != nil && o.MediaChapters != nil {
		return true
	}

	return false
}

// SetMediaChapters gets a reference to the given []MediaChapter and assigns it to the MediaChapters field.
func (o *GetMediaChaptersData) SetMediaChapters(v []MediaChapter) {
	o.MediaChapters = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetMediaChaptersData) GetTotal() int64 {
	if o == nil || o.Total == nil {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaChaptersData) GetTotalOk() (*int64, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetMediaChaptersData) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *GetMediaChaptersData) SetTotal(v int64) {
	o.Total = &v
}

type NullableGetMediaChaptersData struct {
	value *GetMediaChaptersData
	isSet bool
}

func (v NullableGetMediaChaptersData) Get() *GetMediaChaptersData {
	return v.value
}

func (v *NullableGetMediaChaptersData) Set(val *GetMediaChaptersData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMediaChaptersData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMediaChaptersData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMediaChaptersData(val *GetMediaChaptersData) *NullableGetMediaChaptersData {
	return &NullableGetMediaChaptersData{value: val, isSet: true}
}
