/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// VideoAssets struct for VideoAssets
type VideoAssets struct {
	DashIframe    *string `json:"dash_iframe,omitempty"`
	DashPlayerUrl *string `json:"dash_player_url,omitempty"`
	DashUrl       *string `json:"dash_url,omitempty"`
	HlsIframe     *string `json:"hls_iframe,omitempty"`
	HlsPlayerUrl  *string `json:"hls_player_url,omitempty"`
	HlsUrl        *string `json:"hls_url,omitempty"`
	Mp4Url        *string `json:"mp4_url,omitempty"`
	SourceUrl     *string `json:"source_url,omitempty"`
	ThumbnailUrl  *string `json:"thumbnail_url,omitempty"`
}

// NewVideoAssets instantiates a new VideoAssets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoAssets() *VideoAssets {
	this := VideoAssets{}
	return &this
}

// NewVideoAssetsWithDefaults instantiates a new VideoAssets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoAssetsWithDefaults() *VideoAssets {
	this := VideoAssets{}
	return &this
}

// GetDashIframe returns the DashIframe field value if set, zero value otherwise.
func (o *VideoAssets) GetDashIframe() string {
	if o == nil || o.DashIframe == nil {
		var ret string
		return ret
	}
	return *o.DashIframe
}

// GetDashIframeOk returns a tuple with the DashIframe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoAssets) GetDashIframeOk() (*string, bool) {
	if o == nil || o.DashIframe == nil {
		return nil, false
	}
	return o.DashIframe, true
}

// HasDashIframe returns a boolean if a field has been set.
func (o *VideoAssets) HasDashIframe() bool {
	if o != nil && o.DashIframe != nil {
		return true
	}

	return false
}

// SetDashIframe gets a reference to the given string and assigns it to the DashIframe field.
func (o *VideoAssets) SetDashIframe(v string) {
	o.DashIframe = &v
}

// GetDashPlayerUrl returns the DashPlayerUrl field value if set, zero value otherwise.
func (o *VideoAssets) GetDashPlayerUrl() string {
	if o == nil || o.DashPlayerUrl == nil {
		var ret string
		return ret
	}
	return *o.DashPlayerUrl
}

// GetDashPlayerUrlOk returns a tuple with the DashPlayerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoAssets) GetDashPlayerUrlOk() (*string, bool) {
	if o == nil || o.DashPlayerUrl == nil {
		return nil, false
	}
	return o.DashPlayerUrl, true
}

// HasDashPlayerUrl returns a boolean if a field has been set.
func (o *VideoAssets) HasDashPlayerUrl() bool {
	if o != nil && o.DashPlayerUrl != nil {
		return true
	}

	return false
}

// SetDashPlayerUrl gets a reference to the given string and assigns it to the DashPlayerUrl field.
func (o *VideoAssets) SetDashPlayerUrl(v string) {
	o.DashPlayerUrl = &v
}

// GetDashUrl returns the DashUrl field value if set, zero value otherwise.
func (o *VideoAssets) GetDashUrl() string {
	if o == nil || o.DashUrl == nil {
		var ret string
		return ret
	}
	return *o.DashUrl
}

// GetDashUrlOk returns a tuple with the DashUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoAssets) GetDashUrlOk() (*string, bool) {
	if o == nil || o.DashUrl == nil {
		return nil, false
	}
	return o.DashUrl, true
}

// HasDashUrl returns a boolean if a field has been set.
func (o *VideoAssets) HasDashUrl() bool {
	if o != nil && o.DashUrl != nil {
		return true
	}

	return false
}

// SetDashUrl gets a reference to the given string and assigns it to the DashUrl field.
func (o *VideoAssets) SetDashUrl(v string) {
	o.DashUrl = &v
}

// GetHlsIframe returns the HlsIframe field value if set, zero value otherwise.
func (o *VideoAssets) GetHlsIframe() string {
	if o == nil || o.HlsIframe == nil {
		var ret string
		return ret
	}
	return *o.HlsIframe
}

// GetHlsIframeOk returns a tuple with the HlsIframe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoAssets) GetHlsIframeOk() (*string, bool) {
	if o == nil || o.HlsIframe == nil {
		return nil, false
	}
	return o.HlsIframe, true
}

// HasHlsIframe returns a boolean if a field has been set.
func (o *VideoAssets) HasHlsIframe() bool {
	if o != nil && o.HlsIframe != nil {
		return true
	}

	return false
}

// SetHlsIframe gets a reference to the given string and assigns it to the HlsIframe field.
func (o *VideoAssets) SetHlsIframe(v string) {
	o.HlsIframe = &v
}

// GetHlsPlayerUrl returns the HlsPlayerUrl field value if set, zero value otherwise.
func (o *VideoAssets) GetHlsPlayerUrl() string {
	if o == nil || o.HlsPlayerUrl == nil {
		var ret string
		return ret
	}
	return *o.HlsPlayerUrl
}

// GetHlsPlayerUrlOk returns a tuple with the HlsPlayerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoAssets) GetHlsPlayerUrlOk() (*string, bool) {
	if o == nil || o.HlsPlayerUrl == nil {
		return nil, false
	}
	return o.HlsPlayerUrl, true
}

// HasHlsPlayerUrl returns a boolean if a field has been set.
func (o *VideoAssets) HasHlsPlayerUrl() bool {
	if o != nil && o.HlsPlayerUrl != nil {
		return true
	}

	return false
}

// SetHlsPlayerUrl gets a reference to the given string and assigns it to the HlsPlayerUrl field.
func (o *VideoAssets) SetHlsPlayerUrl(v string) {
	o.HlsPlayerUrl = &v
}

// GetHlsUrl returns the HlsUrl field value if set, zero value otherwise.
func (o *VideoAssets) GetHlsUrl() string {
	if o == nil || o.HlsUrl == nil {
		var ret string
		return ret
	}
	return *o.HlsUrl
}

// GetHlsUrlOk returns a tuple with the HlsUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoAssets) GetHlsUrlOk() (*string, bool) {
	if o == nil || o.HlsUrl == nil {
		return nil, false
	}
	return o.HlsUrl, true
}

// HasHlsUrl returns a boolean if a field has been set.
func (o *VideoAssets) HasHlsUrl() bool {
	if o != nil && o.HlsUrl != nil {
		return true
	}

	return false
}

// SetHlsUrl gets a reference to the given string and assigns it to the HlsUrl field.
func (o *VideoAssets) SetHlsUrl(v string) {
	o.HlsUrl = &v
}

// GetMp4Url returns the Mp4Url field value if set, zero value otherwise.
func (o *VideoAssets) GetMp4Url() string {
	if o == nil || o.Mp4Url == nil {
		var ret string
		return ret
	}
	return *o.Mp4Url
}

// GetMp4UrlOk returns a tuple with the Mp4Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoAssets) GetMp4UrlOk() (*string, bool) {
	if o == nil || o.Mp4Url == nil {
		return nil, false
	}
	return o.Mp4Url, true
}

// HasMp4Url returns a boolean if a field has been set.
func (o *VideoAssets) HasMp4Url() bool {
	if o != nil && o.Mp4Url != nil {
		return true
	}

	return false
}

// SetMp4Url gets a reference to the given string and assigns it to the Mp4Url field.
func (o *VideoAssets) SetMp4Url(v string) {
	o.Mp4Url = &v
}

// GetSourceUrl returns the SourceUrl field value if set, zero value otherwise.
func (o *VideoAssets) GetSourceUrl() string {
	if o == nil || o.SourceUrl == nil {
		var ret string
		return ret
	}
	return *o.SourceUrl
}

// GetSourceUrlOk returns a tuple with the SourceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoAssets) GetSourceUrlOk() (*string, bool) {
	if o == nil || o.SourceUrl == nil {
		return nil, false
	}
	return o.SourceUrl, true
}

// HasSourceUrl returns a boolean if a field has been set.
func (o *VideoAssets) HasSourceUrl() bool {
	if o != nil && o.SourceUrl != nil {
		return true
	}

	return false
}

// SetSourceUrl gets a reference to the given string and assigns it to the SourceUrl field.
func (o *VideoAssets) SetSourceUrl(v string) {
	o.SourceUrl = &v
}

// GetThumbnailUrl returns the ThumbnailUrl field value if set, zero value otherwise.
func (o *VideoAssets) GetThumbnailUrl() string {
	if o == nil || o.ThumbnailUrl == nil {
		var ret string
		return ret
	}
	return *o.ThumbnailUrl
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoAssets) GetThumbnailUrlOk() (*string, bool) {
	if o == nil || o.ThumbnailUrl == nil {
		return nil, false
	}
	return o.ThumbnailUrl, true
}

// HasThumbnailUrl returns a boolean if a field has been set.
func (o *VideoAssets) HasThumbnailUrl() bool {
	if o != nil && o.ThumbnailUrl != nil {
		return true
	}

	return false
}

// SetThumbnailUrl gets a reference to the given string and assigns it to the ThumbnailUrl field.
func (o *VideoAssets) SetThumbnailUrl(v string) {
	o.ThumbnailUrl = &v
}

type NullableVideoAssets struct {
	value *VideoAssets
	isSet bool
}

func (v NullableVideoAssets) Get() *VideoAssets {
	return v.value
}

func (v *NullableVideoAssets) Set(val *VideoAssets) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoAssets) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoAssets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoAssets(val *VideoAssets) *NullableVideoAssets {
	return &NullableVideoAssets{value: val, isSet: true}
}
