/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// Media struct for Media
type Media struct {
	Assets        *VideoAssets     `json:"assets,omitempty"`
	Captions      *[]VideoCaption  `json:"captions,omitempty"`
	Chapters      *[]VideoChapter  `json:"chapters,omitempty"`
	CreatedAt     *string          `json:"created_at,omitempty"`
	Description   *string          `json:"description,omitempty"`
	Duration      *float32         `json:"duration,omitempty"`
	Id            *string          `json:"id,omitempty"`
	IsMp4         *bool            `json:"is_mp4,omitempty"`
	IsPublic      *bool            `json:"is_public,omitempty"`
	Metadata      *[]Metadata      `json:"metadata,omitempty"`
	PlayerTheme   *PlayerTheme     `json:"player_theme,omitempty"`
	PlayerThemeId *string          `json:"player_theme_id,omitempty"`
	Qualities     *[]QualityObject `json:"qualities,omitempty"`
	Size          *int32           `json:"size,omitempty"`
	Status        *string          `json:"status,omitempty"`
	Tags          *[]string        `json:"tags,omitempty"`
	Title         *string          `json:"title,omitempty"`
	UpdatedAt     *string          `json:"updated_at,omitempty"`
	UserId        *string          `json:"user_id,omitempty"`
	View          *int32           `json:"view,omitempty"`
}

// NewMedia instantiates a new Media object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMedia() *Media {
	this := Media{}
	return &this
}

// NewMediaWithDefaults instantiates a new Media object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaWithDefaults() *Media {
	this := Media{}
	return &this
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *Media) GetAssets() VideoAssets {
	if o == nil || o.Assets == nil {
		var ret VideoAssets
		return ret
	}
	return *o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetAssetsOk() (*VideoAssets, bool) {
	if o == nil || o.Assets == nil {
		return nil, false
	}
	return o.Assets, true
}

// HasAssets returns a boolean if a field has been set.
func (o *Media) HasAssets() bool {
	if o != nil && o.Assets != nil {
		return true
	}

	return false
}

// SetAssets gets a reference to the given VideoAssets and assigns it to the Assets field.
func (o *Media) SetAssets(v VideoAssets) {
	o.Assets = &v
}

// GetCaptions returns the Captions field value if set, zero value otherwise.
func (o *Media) GetCaptions() []VideoCaption {
	if o == nil || o.Captions == nil {
		var ret []VideoCaption
		return ret
	}
	return *o.Captions
}

// GetCaptionsOk returns a tuple with the Captions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetCaptionsOk() (*[]VideoCaption, bool) {
	if o == nil || o.Captions == nil {
		return nil, false
	}
	return o.Captions, true
}

// HasCaptions returns a boolean if a field has been set.
func (o *Media) HasCaptions() bool {
	if o != nil && o.Captions != nil {
		return true
	}

	return false
}

// SetCaptions gets a reference to the given []VideoCaption and assigns it to the Captions field.
func (o *Media) SetCaptions(v []VideoCaption) {
	o.Captions = &v
}

// GetChapters returns the Chapters field value if set, zero value otherwise.
func (o *Media) GetChapters() []VideoChapter {
	if o == nil || o.Chapters == nil {
		var ret []VideoChapter
		return ret
	}
	return *o.Chapters
}

// GetChaptersOk returns a tuple with the Chapters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetChaptersOk() (*[]VideoChapter, bool) {
	if o == nil || o.Chapters == nil {
		return nil, false
	}
	return o.Chapters, true
}

// HasChapters returns a boolean if a field has been set.
func (o *Media) HasChapters() bool {
	if o != nil && o.Chapters != nil {
		return true
	}

	return false
}

// SetChapters gets a reference to the given []VideoChapter and assigns it to the Chapters field.
func (o *Media) SetChapters(v []VideoChapter) {
	o.Chapters = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Media) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Media) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *Media) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Media) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Media) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Media) SetDescription(v string) {
	o.Description = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *Media) GetDuration() float32 {
	if o == nil || o.Duration == nil {
		var ret float32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetDurationOk() (*float32, bool) {
	if o == nil || o.Duration == nil {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *Media) HasDuration() bool {
	if o != nil && o.Duration != nil {
		return true
	}

	return false
}

// SetDuration gets a reference to the given float32 and assigns it to the Duration field.
func (o *Media) SetDuration(v float32) {
	o.Duration = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Media) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Media) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Media) SetId(v string) {
	o.Id = &v
}

// GetIsMp4 returns the IsMp4 field value if set, zero value otherwise.
func (o *Media) GetIsMp4() bool {
	if o == nil || o.IsMp4 == nil {
		var ret bool
		return ret
	}
	return *o.IsMp4
}

// GetIsMp4Ok returns a tuple with the IsMp4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetIsMp4Ok() (*bool, bool) {
	if o == nil || o.IsMp4 == nil {
		return nil, false
	}
	return o.IsMp4, true
}

// HasIsMp4 returns a boolean if a field has been set.
func (o *Media) HasIsMp4() bool {
	if o != nil && o.IsMp4 != nil {
		return true
	}

	return false
}

// SetIsMp4 gets a reference to the given bool and assigns it to the IsMp4 field.
func (o *Media) SetIsMp4(v bool) {
	o.IsMp4 = &v
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *Media) GetIsPublic() bool {
	if o == nil || o.IsPublic == nil {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetIsPublicOk() (*bool, bool) {
	if o == nil || o.IsPublic == nil {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *Media) HasIsPublic() bool {
	if o != nil && o.IsPublic != nil {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *Media) SetIsPublic(v bool) {
	o.IsPublic = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Media) GetMetadata() []Metadata {
	if o == nil || o.Metadata == nil {
		var ret []Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetMetadataOk() (*[]Metadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Media) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []Metadata and assigns it to the Metadata field.
func (o *Media) SetMetadata(v []Metadata) {
	o.Metadata = &v
}

// GetPlayerTheme returns the PlayerTheme field value if set, zero value otherwise.
func (o *Media) GetPlayerTheme() PlayerTheme {
	if o == nil || o.PlayerTheme == nil {
		var ret PlayerTheme
		return ret
	}
	return *o.PlayerTheme
}

// GetPlayerThemeOk returns a tuple with the PlayerTheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetPlayerThemeOk() (*PlayerTheme, bool) {
	if o == nil || o.PlayerTheme == nil {
		return nil, false
	}
	return o.PlayerTheme, true
}

// HasPlayerTheme returns a boolean if a field has been set.
func (o *Media) HasPlayerTheme() bool {
	if o != nil && o.PlayerTheme != nil {
		return true
	}

	return false
}

// SetPlayerTheme gets a reference to the given PlayerTheme and assigns it to the PlayerTheme field.
func (o *Media) SetPlayerTheme(v PlayerTheme) {
	o.PlayerTheme = &v
}

// GetPlayerThemeId returns the PlayerThemeId field value if set, zero value otherwise.
func (o *Media) GetPlayerThemeId() string {
	if o == nil || o.PlayerThemeId == nil {
		var ret string
		return ret
	}
	return *o.PlayerThemeId
}

// GetPlayerThemeIdOk returns a tuple with the PlayerThemeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetPlayerThemeIdOk() (*string, bool) {
	if o == nil || o.PlayerThemeId == nil {
		return nil, false
	}
	return o.PlayerThemeId, true
}

// HasPlayerThemeId returns a boolean if a field has been set.
func (o *Media) HasPlayerThemeId() bool {
	if o != nil && o.PlayerThemeId != nil {
		return true
	}

	return false
}

// SetPlayerThemeId gets a reference to the given string and assigns it to the PlayerThemeId field.
func (o *Media) SetPlayerThemeId(v string) {
	o.PlayerThemeId = &v
}

// GetQualities returns the Qualities field value if set, zero value otherwise.
func (o *Media) GetQualities() []QualityObject {
	if o == nil || o.Qualities == nil {
		var ret []QualityObject
		return ret
	}
	return *o.Qualities
}

// GetQualitiesOk returns a tuple with the Qualities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetQualitiesOk() (*[]QualityObject, bool) {
	if o == nil || o.Qualities == nil {
		return nil, false
	}
	return o.Qualities, true
}

// HasQualities returns a boolean if a field has been set.
func (o *Media) HasQualities() bool {
	if o != nil && o.Qualities != nil {
		return true
	}

	return false
}

// SetQualities gets a reference to the given []QualityObject and assigns it to the Qualities field.
func (o *Media) SetQualities(v []QualityObject) {
	o.Qualities = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *Media) GetSize() int32 {
	if o == nil || o.Size == nil {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetSizeOk() (*int32, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *Media) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *Media) SetSize(v int32) {
	o.Size = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Media) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Media) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Media) SetStatus(v string) {
	o.Status = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Media) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Media) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Media) SetTags(v []string) {
	o.Tags = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Media) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Media) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Media) SetTitle(v string) {
	o.Title = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Media) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Media) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *Media) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *Media) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *Media) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *Media) SetUserId(v string) {
	o.UserId = &v
}

// GetView returns the View field value if set, zero value otherwise.
func (o *Media) GetView() int32 {
	if o == nil || o.View == nil {
		var ret int32
		return ret
	}
	return *o.View
}

// GetViewOk returns a tuple with the View field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Media) GetViewOk() (*int32, bool) {
	if o == nil || o.View == nil {
		return nil, false
	}
	return o.View, true
}

// HasView returns a boolean if a field has been set.
func (o *Media) HasView() bool {
	if o != nil && o.View != nil {
		return true
	}

	return false
}

// SetView gets a reference to the given int32 and assigns it to the View field.
func (o *Media) SetView(v int32) {
	o.View = &v
}

type NullableMedia struct {
	value *Media
	isSet bool
}

func (v NullableMedia) Get() *Media {
	return v.value
}

func (v *NullableMedia) Set(val *Media) {
	v.value = val
	v.isSet = true
}

func (v NullableMedia) IsSet() bool {
	return v.isSet
}

func (v *NullableMedia) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMedia(val *Media) *NullableMedia {
	return &NullableMedia{value: val, isSet: true}
}
