/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// GetLiveStreamMediasRequest struct for GetLiveStreamMediasRequest
type GetLiveStreamMediasRequest struct {
	Limit           *int32  `json:"limit,omitempty"`
	LiveStreamKeyId *string `json:"live_stream_key_id,omitempty"`
	MediaStatus     *string `json:"media_status,omitempty"`
	Offset          *int32  `json:"offset,omitempty"`
	OrderBy         *string `json:"order_by,omitempty"`
	Search          *string `json:"search,omitempty"`
	SortBy          *string `json:"sort_by,omitempty"`
	Status          *string `json:"status,omitempty"`
}

// NewGetLiveStreamMediasRequest instantiates a new GetLiveStreamMediasRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLiveStreamMediasRequest() *GetLiveStreamMediasRequest {
	this := GetLiveStreamMediasRequest{}
	return &this
}

// NewGetLiveStreamMediasRequestWithDefaults instantiates a new GetLiveStreamMediasRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLiveStreamMediasRequestWithDefaults() *GetLiveStreamMediasRequest {
	this := GetLiveStreamMediasRequest{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *GetLiveStreamMediasRequest) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamMediasRequest) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *GetLiveStreamMediasRequest) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *GetLiveStreamMediasRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetLiveStreamKeyId returns the LiveStreamKeyId field value if set, zero value otherwise.
func (o *GetLiveStreamMediasRequest) GetLiveStreamKeyId() string {
	if o == nil || o.LiveStreamKeyId == nil {
		var ret string
		return ret
	}
	return *o.LiveStreamKeyId
}

// GetLiveStreamKeyIdOk returns a tuple with the LiveStreamKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamMediasRequest) GetLiveStreamKeyIdOk() (*string, bool) {
	if o == nil || o.LiveStreamKeyId == nil {
		return nil, false
	}
	return o.LiveStreamKeyId, true
}

// HasLiveStreamKeyId returns a boolean if a field has been set.
func (o *GetLiveStreamMediasRequest) HasLiveStreamKeyId() bool {
	if o != nil && o.LiveStreamKeyId != nil {
		return true
	}

	return false
}

// SetLiveStreamKeyId gets a reference to the given string and assigns it to the LiveStreamKeyId field.
func (o *GetLiveStreamMediasRequest) SetLiveStreamKeyId(v string) {
	o.LiveStreamKeyId = &v
}

// GetMediaStatus returns the MediaStatus field value if set, zero value otherwise.
func (o *GetLiveStreamMediasRequest) GetMediaStatus() string {
	if o == nil || o.MediaStatus == nil {
		var ret string
		return ret
	}
	return *o.MediaStatus
}

// GetMediaStatusOk returns a tuple with the MediaStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamMediasRequest) GetMediaStatusOk() (*string, bool) {
	if o == nil || o.MediaStatus == nil {
		return nil, false
	}
	return o.MediaStatus, true
}

// HasMediaStatus returns a boolean if a field has been set.
func (o *GetLiveStreamMediasRequest) HasMediaStatus() bool {
	if o != nil && o.MediaStatus != nil {
		return true
	}

	return false
}

// SetMediaStatus gets a reference to the given string and assigns it to the MediaStatus field.
func (o *GetLiveStreamMediasRequest) SetMediaStatus(v string) {
	o.MediaStatus = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *GetLiveStreamMediasRequest) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamMediasRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *GetLiveStreamMediasRequest) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *GetLiveStreamMediasRequest) SetOffset(v int32) {
	o.Offset = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *GetLiveStreamMediasRequest) GetOrderBy() string {
	if o == nil || o.OrderBy == nil {
		var ret string
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamMediasRequest) GetOrderByOk() (*string, bool) {
	if o == nil || o.OrderBy == nil {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *GetLiveStreamMediasRequest) HasOrderBy() bool {
	if o != nil && o.OrderBy != nil {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given string and assigns it to the OrderBy field.
func (o *GetLiveStreamMediasRequest) SetOrderBy(v string) {
	o.OrderBy = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *GetLiveStreamMediasRequest) GetSearch() string {
	if o == nil || o.Search == nil {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamMediasRequest) GetSearchOk() (*string, bool) {
	if o == nil || o.Search == nil {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *GetLiveStreamMediasRequest) HasSearch() bool {
	if o != nil && o.Search != nil {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *GetLiveStreamMediasRequest) SetSearch(v string) {
	o.Search = &v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *GetLiveStreamMediasRequest) GetSortBy() string {
	if o == nil || o.SortBy == nil {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamMediasRequest) GetSortByOk() (*string, bool) {
	if o == nil || o.SortBy == nil {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *GetLiveStreamMediasRequest) HasSortBy() bool {
	if o != nil && o.SortBy != nil {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *GetLiveStreamMediasRequest) SetSortBy(v string) {
	o.SortBy = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetLiveStreamMediasRequest) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamMediasRequest) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetLiveStreamMediasRequest) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetLiveStreamMediasRequest) SetStatus(v string) {
	o.Status = &v
}

type NullableGetLiveStreamMediasRequest struct {
	value *GetLiveStreamMediasRequest
	isSet bool
}

func (v NullableGetLiveStreamMediasRequest) Get() *GetLiveStreamMediasRequest {
	return v.value
}

func (v *NullableGetLiveStreamMediasRequest) Set(val *GetLiveStreamMediasRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLiveStreamMediasRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLiveStreamMediasRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLiveStreamMediasRequest(val *GetLiveStreamMediasRequest) *NullableGetLiveStreamMediasRequest {
	return &NullableGetLiveStreamMediasRequest{value: val, isSet: true}
}
