/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// GetMediaListData struct for GetMediaListData
type GetMediaListData struct {
	Media *[]Media `json:"media,omitempty"`
	Total *int32   `json:"total,omitempty"`
}

// NewGetMediaListData instantiates a new GetMediaListData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMediaListData() *GetMediaListData {
	this := GetMediaListData{}
	return &this
}

// NewGetMediaListDataWithDefaults instantiates a new GetMediaListData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMediaListDataWithDefaults() *GetMediaListData {
	this := GetMediaListData{}
	return &this
}

// GetMedia returns the Media field value if set, zero value otherwise.
func (o *GetMediaListData) GetMedia() []Media {
	if o == nil || o.Media == nil {
		var ret []Media
		return ret
	}
	return *o.Media
}

// GetMediaOk returns a tuple with the Media field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaListData) GetMediaOk() (*[]Media, bool) {
	if o == nil || o.Media == nil {
		return nil, false
	}
	return o.Media, true
}

// HasMedia returns a boolean if a field has been set.
func (o *GetMediaListData) HasMedia() bool {
	if o != nil && o.Media != nil {
		return true
	}

	return false
}

// SetMedia gets a reference to the given []Media and assigns it to the Media field.
func (o *GetMediaListData) SetMedia(v []Media) {
	o.Media = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetMediaListData) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaListData) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetMediaListData) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetMediaListData) SetTotal(v int32) {
	o.Total = &v
}

type NullableGetMediaListData struct {
	value *GetMediaListData
	isSet bool
}

func (v NullableGetMediaListData) Get() *GetMediaListData {
	return v.value
}

func (v *NullableGetMediaListData) Set(val *GetMediaListData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMediaListData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMediaListData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMediaListData(val *GetMediaListData) *NullableGetMediaListData {
	return &NullableGetMediaListData{value: val, isSet: true}
}
