/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// PlaylistResponse struct for PlaylistResponse
type PlaylistResponse struct {
	Data      *PlaylistData `json:"data,omitempty"`
	RequestId *string       `json:"request_id,omitempty"`
	Status    *string       `json:"status,omitempty"`
}

// NewPlaylistResponse instantiates a new PlaylistResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaylistResponse() *PlaylistResponse {
	this := PlaylistResponse{}
	return &this
}

// NewPlaylistResponseWithDefaults instantiates a new PlaylistResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaylistResponseWithDefaults() *PlaylistResponse {
	this := PlaylistResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PlaylistResponse) GetData() PlaylistData {
	if o == nil || o.Data == nil {
		var ret PlaylistData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistResponse) GetDataOk() (*PlaylistData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PlaylistResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given PlaylistData and assigns it to the Data field.
func (o *PlaylistResponse) SetData(v PlaylistData) {
	o.Data = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *PlaylistResponse) GetRequestId() string {
	if o == nil || o.RequestId == nil {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || o.RequestId == nil {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *PlaylistResponse) HasRequestId() bool {
	if o != nil && o.RequestId != nil {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *PlaylistResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PlaylistResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PlaylistResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PlaylistResponse) SetStatus(v string) {
	o.Status = &v
}

type NullablePlaylistResponse struct {
	value *PlaylistResponse
	isSet bool
}

func (v NullablePlaylistResponse) Get() *PlaylistResponse {
	return v.value
}

func (v *NullablePlaylistResponse) Set(val *PlaylistResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaylistResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaylistResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaylistResponse(val *PlaylistResponse) *NullablePlaylistResponse {
	return &NullablePlaylistResponse{value: val, isSet: true}
}
