/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// RemovePlayerThemesFromMediaRequest struct for RemovePlayerThemesFromMediaRequest
type RemovePlayerThemesFromMediaRequest struct {
	MediaId       *string `json:"media_id,omitempty"`
	PlayerThemeId *string `json:"player_theme_id,omitempty"`
}

// NewRemovePlayerThemesFromMediaRequest instantiates a new RemovePlayerThemesFromMediaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemovePlayerThemesFromMediaRequest() *RemovePlayerThemesFromMediaRequest {
	this := RemovePlayerThemesFromMediaRequest{}
	return &this
}

// NewRemovePlayerThemesFromMediaRequestWithDefaults instantiates a new RemovePlayerThemesFromMediaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemovePlayerThemesFromMediaRequestWithDefaults() *RemovePlayerThemesFromMediaRequest {
	this := RemovePlayerThemesFromMediaRequest{}
	return &this
}

// GetMediaId returns the MediaId field value if set, zero value otherwise.
func (o *RemovePlayerThemesFromMediaRequest) GetMediaId() string {
	if o == nil || o.MediaId == nil {
		var ret string
		return ret
	}
	return *o.MediaId
}

// GetMediaIdOk returns a tuple with the MediaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemovePlayerThemesFromMediaRequest) GetMediaIdOk() (*string, bool) {
	if o == nil || o.MediaId == nil {
		return nil, false
	}
	return o.MediaId, true
}

// HasMediaId returns a boolean if a field has been set.
func (o *RemovePlayerThemesFromMediaRequest) HasMediaId() bool {
	if o != nil && o.MediaId != nil {
		return true
	}

	return false
}

// SetMediaId gets a reference to the given string and assigns it to the MediaId field.
func (o *RemovePlayerThemesFromMediaRequest) SetMediaId(v string) {
	o.MediaId = &v
}

// GetPlayerThemeId returns the PlayerThemeId field value if set, zero value otherwise.
func (o *RemovePlayerThemesFromMediaRequest) GetPlayerThemeId() string {
	if o == nil || o.PlayerThemeId == nil {
		var ret string
		return ret
	}
	return *o.PlayerThemeId
}

// GetPlayerThemeIdOk returns a tuple with the PlayerThemeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemovePlayerThemesFromMediaRequest) GetPlayerThemeIdOk() (*string, bool) {
	if o == nil || o.PlayerThemeId == nil {
		return nil, false
	}
	return o.PlayerThemeId, true
}

// HasPlayerThemeId returns a boolean if a field has been set.
func (o *RemovePlayerThemesFromMediaRequest) HasPlayerThemeId() bool {
	if o != nil && o.PlayerThemeId != nil {
		return true
	}

	return false
}

// SetPlayerThemeId gets a reference to the given string and assigns it to the PlayerThemeId field.
func (o *RemovePlayerThemesFromMediaRequest) SetPlayerThemeId(v string) {
	o.PlayerThemeId = &v
}

type NullableRemovePlayerThemesFromMediaRequest struct {
	value *RemovePlayerThemesFromMediaRequest
	isSet bool
}

func (v NullableRemovePlayerThemesFromMediaRequest) Get() *RemovePlayerThemesFromMediaRequest {
	return v.value
}

func (v *NullableRemovePlayerThemesFromMediaRequest) Set(val *RemovePlayerThemesFromMediaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRemovePlayerThemesFromMediaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRemovePlayerThemesFromMediaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemovePlayerThemesFromMediaRequest(val *RemovePlayerThemesFromMediaRequest) *NullableRemovePlayerThemesFromMediaRequest {
	return &NullableRemovePlayerThemesFromMediaRequest{value: val, isSet: true}
}
