/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// UserStreamsUsageResponse struct for UserStreamsUsageResponse
type UserStreamsUsageResponse struct {
	Streams *[]StreamUsageSummary `json:"streams,omitempty"`
	Total   *int64                `json:"total,omitempty"`
}

// NewUserStreamsUsageResponse instantiates a new UserStreamsUsageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserStreamsUsageResponse() *UserStreamsUsageResponse {
	this := UserStreamsUsageResponse{}
	return &this
}

// NewUserStreamsUsageResponseWithDefaults instantiates a new UserStreamsUsageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserStreamsUsageResponseWithDefaults() *UserStreamsUsageResponse {
	this := UserStreamsUsageResponse{}
	return &this
}

// GetStreams returns the Streams field value if set, zero value otherwise.
func (o *UserStreamsUsageResponse) GetStreams() []StreamUsageSummary {
	if o == nil || o.Streams == nil {
		var ret []StreamUsageSummary
		return ret
	}
	return *o.Streams
}

// GetStreamsOk returns a tuple with the Streams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserStreamsUsageResponse) GetStreamsOk() (*[]StreamUsageSummary, bool) {
	if o == nil || o.Streams == nil {
		return nil, false
	}
	return o.Streams, true
}

// HasStreams returns a boolean if a field has been set.
func (o *UserStreamsUsageResponse) HasStreams() bool {
	if o != nil && o.Streams != nil {
		return true
	}

	return false
}

// SetStreams gets a reference to the given []StreamUsageSummary and assigns it to the Streams field.
func (o *UserStreamsUsageResponse) SetStreams(v []StreamUsageSummary) {
	o.Streams = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *UserStreamsUsageResponse) GetTotal() int64 {
	if o == nil || o.Total == nil {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserStreamsUsageResponse) GetTotalOk() (*int64, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *UserStreamsUsageResponse) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *UserStreamsUsageResponse) SetTotal(v int64) {
	o.Total = &v
}

type NullableUserStreamsUsageResponse struct {
	value *UserStreamsUsageResponse
	isSet bool
}

func (v NullableUserStreamsUsageResponse) Get() *UserStreamsUsageResponse {
	return v.value
}

func (v *NullableUserStreamsUsageResponse) Set(val *UserStreamsUsageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserStreamsUsageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserStreamsUsageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserStreamsUsageResponse(val *UserStreamsUsageResponse) *NullableUserStreamsUsageResponse {
	return &NullableUserStreamsUsageResponse{value: val, isSet: true}
}
