/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// MetricsRequest struct for MetricsRequest
type MetricsRequest struct {
	FilterBy  *MetricFilter `json:"filter_by,omitempty"`
	From      *int64        `json:"from,omitempty"`
	Limit     *int64        `json:"limit,omitempty"`
	Offset    *int64        `json:"offset,omitempty"`
	OrderBy   *string       `json:"order_by,omitempty"`
	SortBy    *string       `json:"sort_by,omitempty"`
	SumOthers *bool         `json:"sum_others,omitempty"`
	To        *int64        `json:"to,omitempty"`
}

// NewMetricsRequest instantiates a new MetricsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricsRequest() *MetricsRequest {
	this := MetricsRequest{}
	var limit int64 = 25
	this.Limit = &limit
	return &this
}

// NewMetricsRequestWithDefaults instantiates a new MetricsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricsRequestWithDefaults() *MetricsRequest {
	this := MetricsRequest{}
	var limit int64 = 25
	this.Limit = &limit
	return &this
}

// GetFilterBy returns the FilterBy field value if set, zero value otherwise.
func (o *MetricsRequest) GetFilterBy() MetricFilter {
	if o == nil || o.FilterBy == nil {
		var ret MetricFilter
		return ret
	}
	return *o.FilterBy
}

// GetFilterByOk returns a tuple with the FilterBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsRequest) GetFilterByOk() (*MetricFilter, bool) {
	if o == nil || o.FilterBy == nil {
		return nil, false
	}
	return o.FilterBy, true
}

// HasFilterBy returns a boolean if a field has been set.
func (o *MetricsRequest) HasFilterBy() bool {
	if o != nil && o.FilterBy != nil {
		return true
	}

	return false
}

// SetFilterBy gets a reference to the given MetricFilter and assigns it to the FilterBy field.
func (o *MetricsRequest) SetFilterBy(v MetricFilter) {
	o.FilterBy = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *MetricsRequest) GetFrom() int64 {
	if o == nil || o.From == nil {
		var ret int64
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsRequest) GetFromOk() (*int64, bool) {
	if o == nil || o.From == nil {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *MetricsRequest) HasFrom() bool {
	if o != nil && o.From != nil {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int64 and assigns it to the From field.
func (o *MetricsRequest) SetFrom(v int64) {
	o.From = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *MetricsRequest) GetLimit() int64 {
	if o == nil || o.Limit == nil {
		var ret int64
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsRequest) GetLimitOk() (*int64, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *MetricsRequest) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int64 and assigns it to the Limit field.
func (o *MetricsRequest) SetLimit(v int64) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *MetricsRequest) GetOffset() int64 {
	if o == nil || o.Offset == nil {
		var ret int64
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsRequest) GetOffsetOk() (*int64, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *MetricsRequest) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int64 and assigns it to the Offset field.
func (o *MetricsRequest) SetOffset(v int64) {
	o.Offset = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *MetricsRequest) GetOrderBy() string {
	if o == nil || o.OrderBy == nil {
		var ret string
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsRequest) GetOrderByOk() (*string, bool) {
	if o == nil || o.OrderBy == nil {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *MetricsRequest) HasOrderBy() bool {
	if o != nil && o.OrderBy != nil {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given string and assigns it to the OrderBy field.
func (o *MetricsRequest) SetOrderBy(v string) {
	o.OrderBy = &v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *MetricsRequest) GetSortBy() string {
	if o == nil || o.SortBy == nil {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsRequest) GetSortByOk() (*string, bool) {
	if o == nil || o.SortBy == nil {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *MetricsRequest) HasSortBy() bool {
	if o != nil && o.SortBy != nil {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *MetricsRequest) SetSortBy(v string) {
	o.SortBy = &v
}

// GetSumOthers returns the SumOthers field value if set, zero value otherwise.
func (o *MetricsRequest) GetSumOthers() bool {
	if o == nil || o.SumOthers == nil {
		var ret bool
		return ret
	}
	return *o.SumOthers
}

// GetSumOthersOk returns a tuple with the SumOthers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsRequest) GetSumOthersOk() (*bool, bool) {
	if o == nil || o.SumOthers == nil {
		return nil, false
	}
	return o.SumOthers, true
}

// HasSumOthers returns a boolean if a field has been set.
func (o *MetricsRequest) HasSumOthers() bool {
	if o != nil && o.SumOthers != nil {
		return true
	}

	return false
}

// SetSumOthers gets a reference to the given bool and assigns it to the SumOthers field.
func (o *MetricsRequest) SetSumOthers(v bool) {
	o.SumOthers = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *MetricsRequest) GetTo() int64 {
	if o == nil || o.To == nil {
		var ret int64
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsRequest) GetToOk() (*int64, bool) {
	if o == nil || o.To == nil {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *MetricsRequest) HasTo() bool {
	if o != nil && o.To != nil {
		return true
	}

	return false
}

// SetTo gets a reference to the given int64 and assigns it to the To field.
func (o *MetricsRequest) SetTo(v int64) {
	o.To = &v
}

type NullableMetricsRequest struct {
	value *MetricsRequest
	isSet bool
}

func (v NullableMetricsRequest) Get() *MetricsRequest {
	return v.value
}

func (v *NullableMetricsRequest) Set(val *MetricsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricsRequest(val *MetricsRequest) *NullableMetricsRequest {
	return &NullableMetricsRequest{value: val, isSet: true}
}
