/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// GetMediaPlayerInfoResponse struct for GetMediaPlayerInfoResponse
type GetMediaPlayerInfoResponse struct {
	Assets        *MediaAssets     `json:"assets,omitempty"`
	Captions      *[]MediaCaption  `json:"captions,omitempty"`
	Chapters      *[]MediaChapter  `json:"chapters,omitempty"`
	CreatedAt     *string          `json:"created_at,omitempty"`
	Description   *string          `json:"description,omitempty"`
	Duration      *float32         `json:"duration,omitempty"`
	Id            *string          `json:"id,omitempty"`
	IsMp4         *bool            `json:"is_mp4,omitempty"`
	IsPublic      *bool            `json:"is_public,omitempty"`
	Metadata      *[]Metadata      `json:"metadata,omitempty"`
	PlayerTheme   *PlayerTheme     `json:"player_theme,omitempty"`
	PlayerThemeId *string          `json:"player_theme_id,omitempty"`
	Qualities     *[]QualityObject `json:"qualities,omitempty"`
	Size          *int64           `json:"size,omitempty"`
	Status        *string          `json:"status,omitempty"`
	Tags          *[]string        `json:"tags,omitempty"`
	Title         *string          `json:"title,omitempty"`
	UpdatedAt     *string          `json:"updated_at,omitempty"`
	UserId        *string          `json:"user_id,omitempty"`
}

// NewGetMediaPlayerInfoResponse instantiates a new GetMediaPlayerInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMediaPlayerInfoResponse() *GetMediaPlayerInfoResponse {
	this := GetMediaPlayerInfoResponse{}
	return &this
}

// NewGetMediaPlayerInfoResponseWithDefaults instantiates a new GetMediaPlayerInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMediaPlayerInfoResponseWithDefaults() *GetMediaPlayerInfoResponse {
	this := GetMediaPlayerInfoResponse{}
	return &this
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetAssets() MediaAssets {
	if o == nil || o.Assets == nil {
		var ret MediaAssets
		return ret
	}
	return *o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetAssetsOk() (*MediaAssets, bool) {
	if o == nil || o.Assets == nil {
		return nil, false
	}
	return o.Assets, true
}

// HasAssets returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasAssets() bool {
	if o != nil && o.Assets != nil {
		return true
	}

	return false
}

// SetAssets gets a reference to the given MediaAssets and assigns it to the Assets field.
func (o *GetMediaPlayerInfoResponse) SetAssets(v MediaAssets) {
	o.Assets = &v
}

// GetCaptions returns the Captions field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetCaptions() []MediaCaption {
	if o == nil || o.Captions == nil {
		var ret []MediaCaption
		return ret
	}
	return *o.Captions
}

// GetCaptionsOk returns a tuple with the Captions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetCaptionsOk() (*[]MediaCaption, bool) {
	if o == nil || o.Captions == nil {
		return nil, false
	}
	return o.Captions, true
}

// HasCaptions returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasCaptions() bool {
	if o != nil && o.Captions != nil {
		return true
	}

	return false
}

// SetCaptions gets a reference to the given []MediaCaption and assigns it to the Captions field.
func (o *GetMediaPlayerInfoResponse) SetCaptions(v []MediaCaption) {
	o.Captions = &v
}

// GetChapters returns the Chapters field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetChapters() []MediaChapter {
	if o == nil || o.Chapters == nil {
		var ret []MediaChapter
		return ret
	}
	return *o.Chapters
}

// GetChaptersOk returns a tuple with the Chapters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetChaptersOk() (*[]MediaChapter, bool) {
	if o == nil || o.Chapters == nil {
		return nil, false
	}
	return o.Chapters, true
}

// HasChapters returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasChapters() bool {
	if o != nil && o.Chapters != nil {
		return true
	}

	return false
}

// SetChapters gets a reference to the given []MediaChapter and assigns it to the Chapters field.
func (o *GetMediaPlayerInfoResponse) SetChapters(v []MediaChapter) {
	o.Chapters = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetMediaPlayerInfoResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetMediaPlayerInfoResponse) SetDescription(v string) {
	o.Description = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetDuration() float32 {
	if o == nil || o.Duration == nil {
		var ret float32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetDurationOk() (*float32, bool) {
	if o == nil || o.Duration == nil {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasDuration() bool {
	if o != nil && o.Duration != nil {
		return true
	}

	return false
}

// SetDuration gets a reference to the given float32 and assigns it to the Duration field.
func (o *GetMediaPlayerInfoResponse) SetDuration(v float32) {
	o.Duration = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetMediaPlayerInfoResponse) SetId(v string) {
	o.Id = &v
}

// GetIsMp4 returns the IsMp4 field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetIsMp4() bool {
	if o == nil || o.IsMp4 == nil {
		var ret bool
		return ret
	}
	return *o.IsMp4
}

// GetIsMp4Ok returns a tuple with the IsMp4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetIsMp4Ok() (*bool, bool) {
	if o == nil || o.IsMp4 == nil {
		return nil, false
	}
	return o.IsMp4, true
}

// HasIsMp4 returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasIsMp4() bool {
	if o != nil && o.IsMp4 != nil {
		return true
	}

	return false
}

// SetIsMp4 gets a reference to the given bool and assigns it to the IsMp4 field.
func (o *GetMediaPlayerInfoResponse) SetIsMp4(v bool) {
	o.IsMp4 = &v
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetIsPublic() bool {
	if o == nil || o.IsPublic == nil {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetIsPublicOk() (*bool, bool) {
	if o == nil || o.IsPublic == nil {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasIsPublic() bool {
	if o != nil && o.IsPublic != nil {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *GetMediaPlayerInfoResponse) SetIsPublic(v bool) {
	o.IsPublic = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetMetadata() []Metadata {
	if o == nil || o.Metadata == nil {
		var ret []Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetMetadataOk() (*[]Metadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []Metadata and assigns it to the Metadata field.
func (o *GetMediaPlayerInfoResponse) SetMetadata(v []Metadata) {
	o.Metadata = &v
}

// GetPlayerTheme returns the PlayerTheme field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetPlayerTheme() PlayerTheme {
	if o == nil || o.PlayerTheme == nil {
		var ret PlayerTheme
		return ret
	}
	return *o.PlayerTheme
}

// GetPlayerThemeOk returns a tuple with the PlayerTheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetPlayerThemeOk() (*PlayerTheme, bool) {
	if o == nil || o.PlayerTheme == nil {
		return nil, false
	}
	return o.PlayerTheme, true
}

// HasPlayerTheme returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasPlayerTheme() bool {
	if o != nil && o.PlayerTheme != nil {
		return true
	}

	return false
}

// SetPlayerTheme gets a reference to the given PlayerTheme and assigns it to the PlayerTheme field.
func (o *GetMediaPlayerInfoResponse) SetPlayerTheme(v PlayerTheme) {
	o.PlayerTheme = &v
}

// GetPlayerThemeId returns the PlayerThemeId field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetPlayerThemeId() string {
	if o == nil || o.PlayerThemeId == nil {
		var ret string
		return ret
	}
	return *o.PlayerThemeId
}

// GetPlayerThemeIdOk returns a tuple with the PlayerThemeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetPlayerThemeIdOk() (*string, bool) {
	if o == nil || o.PlayerThemeId == nil {
		return nil, false
	}
	return o.PlayerThemeId, true
}

// HasPlayerThemeId returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasPlayerThemeId() bool {
	if o != nil && o.PlayerThemeId != nil {
		return true
	}

	return false
}

// SetPlayerThemeId gets a reference to the given string and assigns it to the PlayerThemeId field.
func (o *GetMediaPlayerInfoResponse) SetPlayerThemeId(v string) {
	o.PlayerThemeId = &v
}

// GetQualities returns the Qualities field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetQualities() []QualityObject {
	if o == nil || o.Qualities == nil {
		var ret []QualityObject
		return ret
	}
	return *o.Qualities
}

// GetQualitiesOk returns a tuple with the Qualities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetQualitiesOk() (*[]QualityObject, bool) {
	if o == nil || o.Qualities == nil {
		return nil, false
	}
	return o.Qualities, true
}

// HasQualities returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasQualities() bool {
	if o != nil && o.Qualities != nil {
		return true
	}

	return false
}

// SetQualities gets a reference to the given []QualityObject and assigns it to the Qualities field.
func (o *GetMediaPlayerInfoResponse) SetQualities(v []QualityObject) {
	o.Qualities = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetSize() int64 {
	if o == nil || o.Size == nil {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetSizeOk() (*int64, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *GetMediaPlayerInfoResponse) SetSize(v int64) {
	o.Size = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetMediaPlayerInfoResponse) SetStatus(v string) {
	o.Status = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *GetMediaPlayerInfoResponse) SetTags(v []string) {
	o.Tags = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetMediaPlayerInfoResponse) SetTitle(v string) {
	o.Title = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GetMediaPlayerInfoResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *GetMediaPlayerInfoResponse) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaPlayerInfoResponse) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *GetMediaPlayerInfoResponse) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *GetMediaPlayerInfoResponse) SetUserId(v string) {
	o.UserId = &v
}

type NullableGetMediaPlayerInfoResponse struct {
	value *GetMediaPlayerInfoResponse
	isSet bool
}

func (v NullableGetMediaPlayerInfoResponse) Get() *GetMediaPlayerInfoResponse {
	return v.value
}

func (v *NullableGetMediaPlayerInfoResponse) Set(val *GetMediaPlayerInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMediaPlayerInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMediaPlayerInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMediaPlayerInfoResponse(val *GetMediaPlayerInfoResponse) *NullableGetMediaPlayerInfoResponse {
	return &NullableGetMediaPlayerInfoResponse{value: val, isSet: true}
}
