/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// AttachThemeRequest struct for AttachThemeRequest
type AttachThemeRequest struct {
	MediaId       *string `json:"media_id,omitempty"`
	PlayerThemeId *string `json:"player_theme_id,omitempty"`
}

// NewAttachThemeRequest instantiates a new AttachThemeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachThemeRequest() *AttachThemeRequest {
	this := AttachThemeRequest{}
	return &this
}

// NewAttachThemeRequestWithDefaults instantiates a new AttachThemeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachThemeRequestWithDefaults() *AttachThemeRequest {
	this := AttachThemeRequest{}
	return &this
}

// GetMediaId returns the MediaId field value if set, zero value otherwise.
func (o *AttachThemeRequest) GetMediaId() string {
	if o == nil || o.MediaId == nil {
		var ret string
		return ret
	}
	return *o.MediaId
}

// GetMediaIdOk returns a tuple with the MediaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachThemeRequest) GetMediaIdOk() (*string, bool) {
	if o == nil || o.MediaId == nil {
		return nil, false
	}
	return o.MediaId, true
}

// HasMediaId returns a boolean if a field has been set.
func (o *AttachThemeRequest) HasMediaId() bool {
	if o != nil && o.MediaId != nil {
		return true
	}

	return false
}

// SetMediaId gets a reference to the given string and assigns it to the MediaId field.
func (o *AttachThemeRequest) SetMediaId(v string) {
	o.MediaId = &v
}

// GetPlayerThemeId returns the PlayerThemeId field value if set, zero value otherwise.
func (o *AttachThemeRequest) GetPlayerThemeId() string {
	if o == nil || o.PlayerThemeId == nil {
		var ret string
		return ret
	}
	return *o.PlayerThemeId
}

// GetPlayerThemeIdOk returns a tuple with the PlayerThemeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttachThemeRequest) GetPlayerThemeIdOk() (*string, bool) {
	if o == nil || o.PlayerThemeId == nil {
		return nil, false
	}
	return o.PlayerThemeId, true
}

// HasPlayerThemeId returns a boolean if a field has been set.
func (o *AttachThemeRequest) HasPlayerThemeId() bool {
	if o != nil && o.PlayerThemeId != nil {
		return true
	}

	return false
}

// SetPlayerThemeId gets a reference to the given string and assigns it to the PlayerThemeId field.
func (o *AttachThemeRequest) SetPlayerThemeId(v string) {
	o.PlayerThemeId = &v
}

type NullableAttachThemeRequest struct {
	value *AttachThemeRequest
	isSet bool
}

func (v NullableAttachThemeRequest) Get() *AttachThemeRequest {
	return v.value
}

func (v *NullableAttachThemeRequest) Set(val *AttachThemeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachThemeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachThemeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachThemeRequest(val *AttachThemeRequest) *NullableAttachThemeRequest {
	return &NullableAttachThemeRequest{value: val, isSet: true}
}
