/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// ListApiKeysResponse struct for ListApiKeysResponse
type ListApiKeysResponse struct {
	Data      *ListApiKeysData `json:"data,omitempty"`
	RequestId *string          `json:"request_id,omitempty"`
	Status    *string          `json:"status,omitempty"`
}

// NewListApiKeysResponse instantiates a new ListApiKeysResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListApiKeysResponse() *ListApiKeysResponse {
	this := ListApiKeysResponse{}
	return &this
}

// NewListApiKeysResponseWithDefaults instantiates a new ListApiKeysResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListApiKeysResponseWithDefaults() *ListApiKeysResponse {
	this := ListApiKeysResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListApiKeysResponse) GetData() ListApiKeysData {
	if o == nil || o.Data == nil {
		var ret ListApiKeysData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListApiKeysResponse) GetDataOk() (*ListApiKeysData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListApiKeysResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given ListApiKeysData and assigns it to the Data field.
func (o *ListApiKeysResponse) SetData(v ListApiKeysData) {
	o.Data = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ListApiKeysResponse) GetRequestId() string {
	if o == nil || o.RequestId == nil {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListApiKeysResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || o.RequestId == nil {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ListApiKeysResponse) HasRequestId() bool {
	if o != nil && o.RequestId != nil {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ListApiKeysResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ListApiKeysResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListApiKeysResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ListApiKeysResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ListApiKeysResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableListApiKeysResponse struct {
	value *ListApiKeysResponse
	isSet bool
}

func (v NullableListApiKeysResponse) Get() *ListApiKeysResponse {
	return v.value
}

func (v *NullableListApiKeysResponse) Set(val *ListApiKeysResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListApiKeysResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListApiKeysResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListApiKeysResponse(val *ListApiKeysResponse) *NullableListApiKeysResponse {
	return &NullableListApiKeysResponse{value: val, isSet: true}
}
