/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// CreateMediaResponse struct for CreateMediaResponse
type CreateMediaResponse struct {
	Data   *Media  `json:"data,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewCreateMediaResponse instantiates a new CreateMediaResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMediaResponse() *CreateMediaResponse {
	this := CreateMediaResponse{}
	return &this
}

// NewCreateMediaResponseWithDefaults instantiates a new CreateMediaResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMediaResponseWithDefaults() *CreateMediaResponse {
	this := CreateMediaResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateMediaResponse) GetData() Media {
	if o == nil || o.Data == nil {
		var ret Media
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMediaResponse) GetDataOk() (*Media, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateMediaResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given Media and assigns it to the Data field.
func (o *CreateMediaResponse) SetData(v Media) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateMediaResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMediaResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateMediaResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreateMediaResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableCreateMediaResponse struct {
	value *CreateMediaResponse
	isSet bool
}

func (v NullableCreateMediaResponse) Get() *CreateMediaResponse {
	return v.value
}

func (v *NullableCreateMediaResponse) Set(val *CreateMediaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMediaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMediaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMediaResponse(val *CreateMediaResponse) *NullableCreateMediaResponse {
	return &NullableCreateMediaResponse{value: val, isSet: true}
}
