/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// GetDataUsageResponse struct for GetDataUsageResponse
type GetDataUsageResponse struct {
	Data   *GetDataUsageData `json:"data,omitempty"`
	Status *string           `json:"status,omitempty"`
}

// NewGetDataUsageResponse instantiates a new GetDataUsageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDataUsageResponse() *GetDataUsageResponse {
	this := GetDataUsageResponse{}
	return &this
}

// NewGetDataUsageResponseWithDefaults instantiates a new GetDataUsageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDataUsageResponseWithDefaults() *GetDataUsageResponse {
	this := GetDataUsageResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetDataUsageResponse) GetData() GetDataUsageData {
	if o == nil || o.Data == nil {
		var ret GetDataUsageData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDataUsageResponse) GetDataOk() (*GetDataUsageData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetDataUsageResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetDataUsageData and assigns it to the Data field.
func (o *GetDataUsageResponse) SetData(v GetDataUsageData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetDataUsageResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDataUsageResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetDataUsageResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetDataUsageResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetDataUsageResponse struct {
	value *GetDataUsageResponse
	isSet bool
}

func (v NullableGetDataUsageResponse) Get() *GetDataUsageResponse {
	return v.value
}

func (v *NullableGetDataUsageResponse) Set(val *GetDataUsageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDataUsageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDataUsageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDataUsageResponse(val *GetDataUsageResponse) *NullableGetDataUsageResponse {
	return &NullableGetDataUsageResponse{value: val, isSet: true}
}
