/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// ListPlaylistsRequest struct for ListPlaylistsRequest
type ListPlaylistsRequest struct {
	Limit        *int32      `json:"limit,omitempty"`
	Metadata     *[]Metadata `json:"metadata,omitempty"`
	Offset       *int32      `json:"offset,omitempty"`
	OrderBy      *string     `json:"order_by,omitempty"`
	PlaylistType *string     `json:"playlist_type,omitempty"`
	Search       *string     `json:"search,omitempty"`
	SortBy       *string     `json:"sort_by,omitempty"`
	Tags         *[]string   `json:"tags,omitempty"`
}

// NewListPlaylistsRequest instantiates a new ListPlaylistsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPlaylistsRequest() *ListPlaylistsRequest {
	this := ListPlaylistsRequest{}
	var limit int32 = 25
	this.Limit = &limit
	return &this
}

// NewListPlaylistsRequestWithDefaults instantiates a new ListPlaylistsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPlaylistsRequestWithDefaults() *ListPlaylistsRequest {
	this := ListPlaylistsRequest{}
	var limit int32 = 25
	this.Limit = &limit
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ListPlaylistsRequest) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsRequest) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ListPlaylistsRequest) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *ListPlaylistsRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ListPlaylistsRequest) GetMetadata() []Metadata {
	if o == nil || o.Metadata == nil {
		var ret []Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsRequest) GetMetadataOk() (*[]Metadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ListPlaylistsRequest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []Metadata and assigns it to the Metadata field.
func (o *ListPlaylistsRequest) SetMetadata(v []Metadata) {
	o.Metadata = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *ListPlaylistsRequest) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *ListPlaylistsRequest) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *ListPlaylistsRequest) SetOffset(v int32) {
	o.Offset = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *ListPlaylistsRequest) GetOrderBy() string {
	if o == nil || o.OrderBy == nil {
		var ret string
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsRequest) GetOrderByOk() (*string, bool) {
	if o == nil || o.OrderBy == nil {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *ListPlaylistsRequest) HasOrderBy() bool {
	if o != nil && o.OrderBy != nil {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given string and assigns it to the OrderBy field.
func (o *ListPlaylistsRequest) SetOrderBy(v string) {
	o.OrderBy = &v
}

// GetPlaylistType returns the PlaylistType field value if set, zero value otherwise.
func (o *ListPlaylistsRequest) GetPlaylistType() string {
	if o == nil || o.PlaylistType == nil {
		var ret string
		return ret
	}
	return *o.PlaylistType
}

// GetPlaylistTypeOk returns a tuple with the PlaylistType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsRequest) GetPlaylistTypeOk() (*string, bool) {
	if o == nil || o.PlaylistType == nil {
		return nil, false
	}
	return o.PlaylistType, true
}

// HasPlaylistType returns a boolean if a field has been set.
func (o *ListPlaylistsRequest) HasPlaylistType() bool {
	if o != nil && o.PlaylistType != nil {
		return true
	}

	return false
}

// SetPlaylistType gets a reference to the given string and assigns it to the PlaylistType field.
func (o *ListPlaylistsRequest) SetPlaylistType(v string) {
	o.PlaylistType = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *ListPlaylistsRequest) GetSearch() string {
	if o == nil || o.Search == nil {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsRequest) GetSearchOk() (*string, bool) {
	if o == nil || o.Search == nil {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *ListPlaylistsRequest) HasSearch() bool {
	if o != nil && o.Search != nil {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *ListPlaylistsRequest) SetSearch(v string) {
	o.Search = &v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *ListPlaylistsRequest) GetSortBy() string {
	if o == nil || o.SortBy == nil {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsRequest) GetSortByOk() (*string, bool) {
	if o == nil || o.SortBy == nil {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *ListPlaylistsRequest) HasSortBy() bool {
	if o != nil && o.SortBy != nil {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *ListPlaylistsRequest) SetSortBy(v string) {
	o.SortBy = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ListPlaylistsRequest) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsRequest) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ListPlaylistsRequest) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *ListPlaylistsRequest) SetTags(v []string) {
	o.Tags = &v
}

type NullableListPlaylistsRequest struct {
	value *ListPlaylistsRequest
	isSet bool
}

func (v NullableListPlaylistsRequest) Get() *ListPlaylistsRequest {
	return v.value
}

func (v *NullableListPlaylistsRequest) Set(val *ListPlaylistsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListPlaylistsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListPlaylistsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPlaylistsRequest(val *ListPlaylistsRequest) *NullableListPlaylistsRequest {
	return &NullableListPlaylistsRequest{value: val, isSet: true}
}
