/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// PlaylistItemMedia struct for PlaylistItemMedia
type PlaylistItemMedia struct {
	Captions     *[]MediaCaption `json:"captions,omitempty"`
	Chapters     *[]MediaChapter `json:"chapters,omitempty"`
	Description  *string         `json:"description,omitempty"`
	Duration     *float32        `json:"duration,omitempty"`
	HlsUrl       *string         `json:"hls_url,omitempty"`
	Qualities    *string         `json:"qualities,omitempty"`
	Size         *int32          `json:"size,omitempty"`
	ThumbnailUrl *string         `json:"thumbnail_url,omitempty"`
	Title        *string         `json:"title,omitempty"`
}

// NewPlaylistItemMedia instantiates a new PlaylistItemMedia object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaylistItemMedia() *PlaylistItemMedia {
	this := PlaylistItemMedia{}
	return &this
}

// NewPlaylistItemMediaWithDefaults instantiates a new PlaylistItemMedia object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaylistItemMediaWithDefaults() *PlaylistItemMedia {
	this := PlaylistItemMedia{}
	return &this
}

// GetCaptions returns the Captions field value if set, zero value otherwise.
func (o *PlaylistItemMedia) GetCaptions() []MediaCaption {
	if o == nil || o.Captions == nil {
		var ret []MediaCaption
		return ret
	}
	return *o.Captions
}

// GetCaptionsOk returns a tuple with the Captions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItemMedia) GetCaptionsOk() (*[]MediaCaption, bool) {
	if o == nil || o.Captions == nil {
		return nil, false
	}
	return o.Captions, true
}

// HasCaptions returns a boolean if a field has been set.
func (o *PlaylistItemMedia) HasCaptions() bool {
	if o != nil && o.Captions != nil {
		return true
	}

	return false
}

// SetCaptions gets a reference to the given []MediaCaption and assigns it to the Captions field.
func (o *PlaylistItemMedia) SetCaptions(v []MediaCaption) {
	o.Captions = &v
}

// GetChapters returns the Chapters field value if set, zero value otherwise.
func (o *PlaylistItemMedia) GetChapters() []MediaChapter {
	if o == nil || o.Chapters == nil {
		var ret []MediaChapter
		return ret
	}
	return *o.Chapters
}

// GetChaptersOk returns a tuple with the Chapters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItemMedia) GetChaptersOk() (*[]MediaChapter, bool) {
	if o == nil || o.Chapters == nil {
		return nil, false
	}
	return o.Chapters, true
}

// HasChapters returns a boolean if a field has been set.
func (o *PlaylistItemMedia) HasChapters() bool {
	if o != nil && o.Chapters != nil {
		return true
	}

	return false
}

// SetChapters gets a reference to the given []MediaChapter and assigns it to the Chapters field.
func (o *PlaylistItemMedia) SetChapters(v []MediaChapter) {
	o.Chapters = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PlaylistItemMedia) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItemMedia) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PlaylistItemMedia) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PlaylistItemMedia) SetDescription(v string) {
	o.Description = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *PlaylistItemMedia) GetDuration() float32 {
	if o == nil || o.Duration == nil {
		var ret float32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItemMedia) GetDurationOk() (*float32, bool) {
	if o == nil || o.Duration == nil {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *PlaylistItemMedia) HasDuration() bool {
	if o != nil && o.Duration != nil {
		return true
	}

	return false
}

// SetDuration gets a reference to the given float32 and assigns it to the Duration field.
func (o *PlaylistItemMedia) SetDuration(v float32) {
	o.Duration = &v
}

// GetHlsUrl returns the HlsUrl field value if set, zero value otherwise.
func (o *PlaylistItemMedia) GetHlsUrl() string {
	if o == nil || o.HlsUrl == nil {
		var ret string
		return ret
	}
	return *o.HlsUrl
}

// GetHlsUrlOk returns a tuple with the HlsUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItemMedia) GetHlsUrlOk() (*string, bool) {
	if o == nil || o.HlsUrl == nil {
		return nil, false
	}
	return o.HlsUrl, true
}

// HasHlsUrl returns a boolean if a field has been set.
func (o *PlaylistItemMedia) HasHlsUrl() bool {
	if o != nil && o.HlsUrl != nil {
		return true
	}

	return false
}

// SetHlsUrl gets a reference to the given string and assigns it to the HlsUrl field.
func (o *PlaylistItemMedia) SetHlsUrl(v string) {
	o.HlsUrl = &v
}

// GetQualities returns the Qualities field value if set, zero value otherwise.
func (o *PlaylistItemMedia) GetQualities() string {
	if o == nil || o.Qualities == nil {
		var ret string
		return ret
	}
	return *o.Qualities
}

// GetQualitiesOk returns a tuple with the Qualities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItemMedia) GetQualitiesOk() (*string, bool) {
	if o == nil || o.Qualities == nil {
		return nil, false
	}
	return o.Qualities, true
}

// HasQualities returns a boolean if a field has been set.
func (o *PlaylistItemMedia) HasQualities() bool {
	if o != nil && o.Qualities != nil {
		return true
	}

	return false
}

// SetQualities gets a reference to the given string and assigns it to the Qualities field.
func (o *PlaylistItemMedia) SetQualities(v string) {
	o.Qualities = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *PlaylistItemMedia) GetSize() int32 {
	if o == nil || o.Size == nil {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItemMedia) GetSizeOk() (*int32, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *PlaylistItemMedia) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *PlaylistItemMedia) SetSize(v int32) {
	o.Size = &v
}

// GetThumbnailUrl returns the ThumbnailUrl field value if set, zero value otherwise.
func (o *PlaylistItemMedia) GetThumbnailUrl() string {
	if o == nil || o.ThumbnailUrl == nil {
		var ret string
		return ret
	}
	return *o.ThumbnailUrl
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItemMedia) GetThumbnailUrlOk() (*string, bool) {
	if o == nil || o.ThumbnailUrl == nil {
		return nil, false
	}
	return o.ThumbnailUrl, true
}

// HasThumbnailUrl returns a boolean if a field has been set.
func (o *PlaylistItemMedia) HasThumbnailUrl() bool {
	if o != nil && o.ThumbnailUrl != nil {
		return true
	}

	return false
}

// SetThumbnailUrl gets a reference to the given string and assigns it to the ThumbnailUrl field.
func (o *PlaylistItemMedia) SetThumbnailUrl(v string) {
	o.ThumbnailUrl = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *PlaylistItemMedia) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItemMedia) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *PlaylistItemMedia) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *PlaylistItemMedia) SetTitle(v string) {
	o.Title = &v
}

type NullablePlaylistItemMedia struct {
	value *PlaylistItemMedia
	isSet bool
}

func (v NullablePlaylistItemMedia) Get() *PlaylistItemMedia {
	return v.value
}

func (v *NullablePlaylistItemMedia) Set(val *PlaylistItemMedia) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaylistItemMedia) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaylistItemMedia) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaylistItemMedia(val *PlaylistItemMedia) *NullablePlaylistItemMedia {
	return &NullablePlaylistItemMedia{value: val, isSet: true}
}
