/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// AddMediaToPlaylistRequest struct for AddMediaToPlaylistRequest
type AddMediaToPlaylistRequest struct {
	MediaId         *string   `json:"media_id,omitempty"`
	OptionMediaIds  *[]string `json:"option_media_ids,omitempty"`
	OptionPlaylists *[]string `json:"option_playlists,omitempty"`
}

// NewAddMediaToPlaylistRequest instantiates a new AddMediaToPlaylistRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddMediaToPlaylistRequest() *AddMediaToPlaylistRequest {
	this := AddMediaToPlaylistRequest{}
	return &this
}

// NewAddMediaToPlaylistRequestWithDefaults instantiates a new AddMediaToPlaylistRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddMediaToPlaylistRequestWithDefaults() *AddMediaToPlaylistRequest {
	this := AddMediaToPlaylistRequest{}
	return &this
}

// GetMediaId returns the MediaId field value if set, zero value otherwise.
func (o *AddMediaToPlaylistRequest) GetMediaId() string {
	if o == nil || o.MediaId == nil {
		var ret string
		return ret
	}
	return *o.MediaId
}

// GetMediaIdOk returns a tuple with the MediaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddMediaToPlaylistRequest) GetMediaIdOk() (*string, bool) {
	if o == nil || o.MediaId == nil {
		return nil, false
	}
	return o.MediaId, true
}

// HasMediaId returns a boolean if a field has been set.
func (o *AddMediaToPlaylistRequest) HasMediaId() bool {
	if o != nil && o.MediaId != nil {
		return true
	}

	return false
}

// SetMediaId gets a reference to the given string and assigns it to the MediaId field.
func (o *AddMediaToPlaylistRequest) SetMediaId(v string) {
	o.MediaId = &v
}

// GetOptionMediaIds returns the OptionMediaIds field value if set, zero value otherwise.
func (o *AddMediaToPlaylistRequest) GetOptionMediaIds() []string {
	if o == nil || o.OptionMediaIds == nil {
		var ret []string
		return ret
	}
	return *o.OptionMediaIds
}

// GetOptionMediaIdsOk returns a tuple with the OptionMediaIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddMediaToPlaylistRequest) GetOptionMediaIdsOk() (*[]string, bool) {
	if o == nil || o.OptionMediaIds == nil {
		return nil, false
	}
	return o.OptionMediaIds, true
}

// HasOptionMediaIds returns a boolean if a field has been set.
func (o *AddMediaToPlaylistRequest) HasOptionMediaIds() bool {
	if o != nil && o.OptionMediaIds != nil {
		return true
	}

	return false
}

// SetOptionMediaIds gets a reference to the given []string and assigns it to the OptionMediaIds field.
func (o *AddMediaToPlaylistRequest) SetOptionMediaIds(v []string) {
	o.OptionMediaIds = &v
}

// GetOptionPlaylists returns the OptionPlaylists field value if set, zero value otherwise.
func (o *AddMediaToPlaylistRequest) GetOptionPlaylists() []string {
	if o == nil || o.OptionPlaylists == nil {
		var ret []string
		return ret
	}
	return *o.OptionPlaylists
}

// GetOptionPlaylistsOk returns a tuple with the OptionPlaylists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddMediaToPlaylistRequest) GetOptionPlaylistsOk() (*[]string, bool) {
	if o == nil || o.OptionPlaylists == nil {
		return nil, false
	}
	return o.OptionPlaylists, true
}

// HasOptionPlaylists returns a boolean if a field has been set.
func (o *AddMediaToPlaylistRequest) HasOptionPlaylists() bool {
	if o != nil && o.OptionPlaylists != nil {
		return true
	}

	return false
}

// SetOptionPlaylists gets a reference to the given []string and assigns it to the OptionPlaylists field.
func (o *AddMediaToPlaylistRequest) SetOptionPlaylists(v []string) {
	o.OptionPlaylists = &v
}

type NullableAddMediaToPlaylistRequest struct {
	value *AddMediaToPlaylistRequest
	isSet bool
}

func (v NullableAddMediaToPlaylistRequest) Get() *AddMediaToPlaylistRequest {
	return v.value
}

func (v *NullableAddMediaToPlaylistRequest) Set(val *AddMediaToPlaylistRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddMediaToPlaylistRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddMediaToPlaylistRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddMediaToPlaylistRequest(val *AddMediaToPlaylistRequest) *NullableAddMediaToPlaylistRequest {
	return &NullableAddMediaToPlaylistRequest{value: val, isSet: true}
}
