/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// ListPlaylistsResponse struct for ListPlaylistsResponse
type ListPlaylistsResponse struct {
	Data      *ListPlaylistsData `json:"data,omitempty"`
	RequestId *string            `json:"request_id,omitempty"`
	Status    *string            `json:"status,omitempty"`
}

// NewListPlaylistsResponse instantiates a new ListPlaylistsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPlaylistsResponse() *ListPlaylistsResponse {
	this := ListPlaylistsResponse{}
	return &this
}

// NewListPlaylistsResponseWithDefaults instantiates a new ListPlaylistsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPlaylistsResponseWithDefaults() *ListPlaylistsResponse {
	this := ListPlaylistsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListPlaylistsResponse) GetData() ListPlaylistsData {
	if o == nil || o.Data == nil {
		var ret ListPlaylistsData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsResponse) GetDataOk() (*ListPlaylistsData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListPlaylistsResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given ListPlaylistsData and assigns it to the Data field.
func (o *ListPlaylistsResponse) SetData(v ListPlaylistsData) {
	o.Data = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ListPlaylistsResponse) GetRequestId() string {
	if o == nil || o.RequestId == nil {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || o.RequestId == nil {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ListPlaylistsResponse) HasRequestId() bool {
	if o != nil && o.RequestId != nil {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ListPlaylistsResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ListPlaylistsResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ListPlaylistsResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ListPlaylistsResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableListPlaylistsResponse struct {
	value *ListPlaylistsResponse
	isSet bool
}

func (v NullableListPlaylistsResponse) Get() *ListPlaylistsResponse {
	return v.value
}

func (v *NullableListPlaylistsResponse) Set(val *ListPlaylistsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListPlaylistsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListPlaylistsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPlaylistsResponse(val *ListPlaylistsResponse) *NullableListPlaylistsResponse {
	return &NullableListPlaylistsResponse{value: val, isSet: true}
}
