/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// MetricsContext struct for MetricsContext
type MetricsContext struct {
	Aggregation *string       `json:"aggregation,omitempty"`
	Breakdown   *string       `json:"breakdown,omitempty"`
	Filter      *MetricFilter `json:"filter,omitempty"`
	Interval    *string       `json:"interval,omitempty"`
	Metric      *string       `json:"metric,omitempty"`
	TimeFrame   *TimeFrame    `json:"time_frame,omitempty"`
}

// NewMetricsContext instantiates a new MetricsContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricsContext() *MetricsContext {
	this := MetricsContext{}
	return &this
}

// NewMetricsContextWithDefaults instantiates a new MetricsContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricsContextWithDefaults() *MetricsContext {
	this := MetricsContext{}
	return &this
}

// GetAggregation returns the Aggregation field value if set, zero value otherwise.
func (o *MetricsContext) GetAggregation() string {
	if o == nil || o.Aggregation == nil {
		var ret string
		return ret
	}
	return *o.Aggregation
}

// GetAggregationOk returns a tuple with the Aggregation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsContext) GetAggregationOk() (*string, bool) {
	if o == nil || o.Aggregation == nil {
		return nil, false
	}
	return o.Aggregation, true
}

// HasAggregation returns a boolean if a field has been set.
func (o *MetricsContext) HasAggregation() bool {
	if o != nil && o.Aggregation != nil {
		return true
	}

	return false
}

// SetAggregation gets a reference to the given string and assigns it to the Aggregation field.
func (o *MetricsContext) SetAggregation(v string) {
	o.Aggregation = &v
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise.
func (o *MetricsContext) GetBreakdown() string {
	if o == nil || o.Breakdown == nil {
		var ret string
		return ret
	}
	return *o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsContext) GetBreakdownOk() (*string, bool) {
	if o == nil || o.Breakdown == nil {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *MetricsContext) HasBreakdown() bool {
	if o != nil && o.Breakdown != nil {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given string and assigns it to the Breakdown field.
func (o *MetricsContext) SetBreakdown(v string) {
	o.Breakdown = &v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *MetricsContext) GetFilter() MetricFilter {
	if o == nil || o.Filter == nil {
		var ret MetricFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsContext) GetFilterOk() (*MetricFilter, bool) {
	if o == nil || o.Filter == nil {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *MetricsContext) HasFilter() bool {
	if o != nil && o.Filter != nil {
		return true
	}

	return false
}

// SetFilter gets a reference to the given MetricFilter and assigns it to the Filter field.
func (o *MetricsContext) SetFilter(v MetricFilter) {
	o.Filter = &v
}

// GetInterval returns the Interval field value if set, zero value otherwise.
func (o *MetricsContext) GetInterval() string {
	if o == nil || o.Interval == nil {
		var ret string
		return ret
	}
	return *o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsContext) GetIntervalOk() (*string, bool) {
	if o == nil || o.Interval == nil {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *MetricsContext) HasInterval() bool {
	if o != nil && o.Interval != nil {
		return true
	}

	return false
}

// SetInterval gets a reference to the given string and assigns it to the Interval field.
func (o *MetricsContext) SetInterval(v string) {
	o.Interval = &v
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *MetricsContext) GetMetric() string {
	if o == nil || o.Metric == nil {
		var ret string
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsContext) GetMetricOk() (*string, bool) {
	if o == nil || o.Metric == nil {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *MetricsContext) HasMetric() bool {
	if o != nil && o.Metric != nil {
		return true
	}

	return false
}

// SetMetric gets a reference to the given string and assigns it to the Metric field.
func (o *MetricsContext) SetMetric(v string) {
	o.Metric = &v
}

// GetTimeFrame returns the TimeFrame field value if set, zero value otherwise.
func (o *MetricsContext) GetTimeFrame() TimeFrame {
	if o == nil || o.TimeFrame == nil {
		var ret TimeFrame
		return ret
	}
	return *o.TimeFrame
}

// GetTimeFrameOk returns a tuple with the TimeFrame field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsContext) GetTimeFrameOk() (*TimeFrame, bool) {
	if o == nil || o.TimeFrame == nil {
		return nil, false
	}
	return o.TimeFrame, true
}

// HasTimeFrame returns a boolean if a field has been set.
func (o *MetricsContext) HasTimeFrame() bool {
	if o != nil && o.TimeFrame != nil {
		return true
	}

	return false
}

// SetTimeFrame gets a reference to the given TimeFrame and assigns it to the TimeFrame field.
func (o *MetricsContext) SetTimeFrame(v TimeFrame) {
	o.TimeFrame = &v
}

type NullableMetricsContext struct {
	value *MetricsContext
	isSet bool
}

func (v NullableMetricsContext) Get() *MetricsContext {
	return v.value
}

func (v *NullableMetricsContext) Set(val *MetricsContext) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricsContext) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricsContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricsContext(val *MetricsContext) *NullableMetricsContext {
	return &NullableMetricsContext{value: val, isSet: true}
}
