/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// GetBreakdownMetricsResponse struct for GetBreakdownMetricsResponse
type GetBreakdownMetricsResponse struct {
	Context *MetricsContext `json:"context,omitempty"`
	Data    *[]MetricItem   `json:"data,omitempty"`
	Total   *int32          `json:"total,omitempty"`
}

// NewGetBreakdownMetricsResponse instantiates a new GetBreakdownMetricsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBreakdownMetricsResponse() *GetBreakdownMetricsResponse {
	this := GetBreakdownMetricsResponse{}
	return &this
}

// NewGetBreakdownMetricsResponseWithDefaults instantiates a new GetBreakdownMetricsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBreakdownMetricsResponseWithDefaults() *GetBreakdownMetricsResponse {
	this := GetBreakdownMetricsResponse{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *GetBreakdownMetricsResponse) GetContext() MetricsContext {
	if o == nil || o.Context == nil {
		var ret MetricsContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsResponse) GetContextOk() (*MetricsContext, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *GetBreakdownMetricsResponse) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given MetricsContext and assigns it to the Context field.
func (o *GetBreakdownMetricsResponse) SetContext(v MetricsContext) {
	o.Context = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetBreakdownMetricsResponse) GetData() []MetricItem {
	if o == nil || o.Data == nil {
		var ret []MetricItem
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsResponse) GetDataOk() (*[]MetricItem, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetBreakdownMetricsResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []MetricItem and assigns it to the Data field.
func (o *GetBreakdownMetricsResponse) SetData(v []MetricItem) {
	o.Data = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetBreakdownMetricsResponse) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBreakdownMetricsResponse) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetBreakdownMetricsResponse) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetBreakdownMetricsResponse) SetTotal(v int32) {
	o.Total = &v
}

type NullableGetBreakdownMetricsResponse struct {
	value *GetBreakdownMetricsResponse
	isSet bool
}

func (v NullableGetBreakdownMetricsResponse) Get() *GetBreakdownMetricsResponse {
	return v.value
}

func (v *NullableGetBreakdownMetricsResponse) Set(val *GetBreakdownMetricsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBreakdownMetricsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBreakdownMetricsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBreakdownMetricsResponse(val *GetBreakdownMetricsResponse) *NullableGetBreakdownMetricsResponse {
	return &NullableGetBreakdownMetricsResponse{value: val, isSet: true}
}
