/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// ListPlaylistsData struct for ListPlaylistsData
type ListPlaylistsData struct {
	Playlists *[]Playlist           `json:"playlists,omitempty"`
	Query     *ListPlaylistsRequest `json:"query,omitempty"`
	Total     *int64                `json:"total,omitempty"`
}

// NewListPlaylistsData instantiates a new ListPlaylistsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPlaylistsData() *ListPlaylistsData {
	this := ListPlaylistsData{}
	return &this
}

// NewListPlaylistsDataWithDefaults instantiates a new ListPlaylistsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPlaylistsDataWithDefaults() *ListPlaylistsData {
	this := ListPlaylistsData{}
	return &this
}

// GetPlaylists returns the Playlists field value if set, zero value otherwise.
func (o *ListPlaylistsData) GetPlaylists() []Playlist {
	if o == nil || o.Playlists == nil {
		var ret []Playlist
		return ret
	}
	return *o.Playlists
}

// GetPlaylistsOk returns a tuple with the Playlists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsData) GetPlaylistsOk() (*[]Playlist, bool) {
	if o == nil || o.Playlists == nil {
		return nil, false
	}
	return o.Playlists, true
}

// HasPlaylists returns a boolean if a field has been set.
func (o *ListPlaylistsData) HasPlaylists() bool {
	if o != nil && o.Playlists != nil {
		return true
	}

	return false
}

// SetPlaylists gets a reference to the given []Playlist and assigns it to the Playlists field.
func (o *ListPlaylistsData) SetPlaylists(v []Playlist) {
	o.Playlists = &v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *ListPlaylistsData) GetQuery() ListPlaylistsRequest {
	if o == nil || o.Query == nil {
		var ret ListPlaylistsRequest
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsData) GetQueryOk() (*ListPlaylistsRequest, bool) {
	if o == nil || o.Query == nil {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *ListPlaylistsData) HasQuery() bool {
	if o != nil && o.Query != nil {
		return true
	}

	return false
}

// SetQuery gets a reference to the given ListPlaylistsRequest and assigns it to the Query field.
func (o *ListPlaylistsData) SetQuery(v ListPlaylistsRequest) {
	o.Query = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ListPlaylistsData) GetTotal() int64 {
	if o == nil || o.Total == nil {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlaylistsData) GetTotalOk() (*int64, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ListPlaylistsData) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *ListPlaylistsData) SetTotal(v int64) {
	o.Total = &v
}

type NullableListPlaylistsData struct {
	value *ListPlaylistsData
	isSet bool
}

func (v NullableListPlaylistsData) Get() *ListPlaylistsData {
	return v.value
}

func (v *NullableListPlaylistsData) Set(val *ListPlaylistsData) {
	v.value = val
	v.isSet = true
}

func (v NullableListPlaylistsData) IsSet() bool {
	return v.isSet
}

func (v *NullableListPlaylistsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPlaylistsData(val *ListPlaylistsData) *NullableListPlaylistsData {
	return &NullableListPlaylistsData{value: val, isSet: true}
}
