/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// InternalControllersGetAggreatedMetricsMetricsRequest struct for InternalControllersGetAggreatedMetricsMetricsRequest
type InternalControllersGetAggreatedMetricsMetricsRequest struct {
	FilterBy *MetricFilter `json:"filter_by,omitempty"`
	From     *int32        `json:"from,omitempty"`
	To       *int32        `json:"to,omitempty"`
}

// NewInternalControllersGetAggreatedMetricsMetricsRequest instantiates a new InternalControllersGetAggreatedMetricsMetricsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalControllersGetAggreatedMetricsMetricsRequest() *InternalControllersGetAggreatedMetricsMetricsRequest {
	this := InternalControllersGetAggreatedMetricsMetricsRequest{}
	return &this
}

// NewInternalControllersGetAggreatedMetricsMetricsRequestWithDefaults instantiates a new InternalControllersGetAggreatedMetricsMetricsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalControllersGetAggreatedMetricsMetricsRequestWithDefaults() *InternalControllersGetAggreatedMetricsMetricsRequest {
	this := InternalControllersGetAggreatedMetricsMetricsRequest{}
	return &this
}

// GetFilterBy returns the FilterBy field value if set, zero value otherwise.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) GetFilterBy() MetricFilter {
	if o == nil || o.FilterBy == nil {
		var ret MetricFilter
		return ret
	}
	return *o.FilterBy
}

// GetFilterByOk returns a tuple with the FilterBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) GetFilterByOk() (*MetricFilter, bool) {
	if o == nil || o.FilterBy == nil {
		return nil, false
	}
	return o.FilterBy, true
}

// HasFilterBy returns a boolean if a field has been set.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) HasFilterBy() bool {
	if o != nil && o.FilterBy != nil {
		return true
	}

	return false
}

// SetFilterBy gets a reference to the given MetricFilter and assigns it to the FilterBy field.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) SetFilterBy(v MetricFilter) {
	o.FilterBy = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) GetFrom() int32 {
	if o == nil || o.From == nil {
		var ret int32
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) GetFromOk() (*int32, bool) {
	if o == nil || o.From == nil {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) HasFrom() bool {
	if o != nil && o.From != nil {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int32 and assigns it to the From field.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) SetFrom(v int32) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) GetTo() int32 {
	if o == nil || o.To == nil {
		var ret int32
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) GetToOk() (*int32, bool) {
	if o == nil || o.To == nil {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) HasTo() bool {
	if o != nil && o.To != nil {
		return true
	}

	return false
}

// SetTo gets a reference to the given int32 and assigns it to the To field.
func (o *InternalControllersGetAggreatedMetricsMetricsRequest) SetTo(v int32) {
	o.To = &v
}

type NullableInternalControllersGetAggreatedMetricsMetricsRequest struct {
	value *InternalControllersGetAggreatedMetricsMetricsRequest
	isSet bool
}

func (v NullableInternalControllersGetAggreatedMetricsMetricsRequest) Get() *InternalControllersGetAggreatedMetricsMetricsRequest {
	return v.value
}

func (v *NullableInternalControllersGetAggreatedMetricsMetricsRequest) Set(val *InternalControllersGetAggreatedMetricsMetricsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalControllersGetAggreatedMetricsMetricsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalControllersGetAggreatedMetricsMetricsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalControllersGetAggreatedMetricsMetricsRequest(val *InternalControllersGetAggreatedMetricsMetricsRequest) *NullableInternalControllersGetAggreatedMetricsMetricsRequest {
	return &NullableInternalControllersGetAggreatedMetricsMetricsRequest{value: val, isSet: true}
}
