/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// CreateMediaRequest struct for CreateMediaRequest
type CreateMediaRequest struct {
	Description     *string          `json:"description,omitempty"`
	IsPublic        *bool            `json:"is_public,omitempty"`
	Metadata        *[]Metadata      `json:"metadata,omitempty"`
	Qualities       *[]QualityConfig `json:"qualities,omitempty"`
	SegmentDuration *int32           `json:"segment_duration,omitempty"`
	Tags            *[]string        `json:"tags,omitempty"`
	Title           *string          `json:"title,omitempty"`
	Watermark       *VideoWatermark  `json:"watermark,omitempty"`
}

// NewCreateMediaRequest instantiates a new CreateMediaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMediaRequest() *CreateMediaRequest {
	this := CreateMediaRequest{}
	return &this
}

// NewCreateMediaRequestWithDefaults instantiates a new CreateMediaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMediaRequestWithDefaults() *CreateMediaRequest {
	this := CreateMediaRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateMediaRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMediaRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateMediaRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateMediaRequest) SetDescription(v string) {
	o.Description = &v
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *CreateMediaRequest) GetIsPublic() bool {
	if o == nil || o.IsPublic == nil {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMediaRequest) GetIsPublicOk() (*bool, bool) {
	if o == nil || o.IsPublic == nil {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *CreateMediaRequest) HasIsPublic() bool {
	if o != nil && o.IsPublic != nil {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *CreateMediaRequest) SetIsPublic(v bool) {
	o.IsPublic = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateMediaRequest) GetMetadata() []Metadata {
	if o == nil || o.Metadata == nil {
		var ret []Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMediaRequest) GetMetadataOk() (*[]Metadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateMediaRequest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []Metadata and assigns it to the Metadata field.
func (o *CreateMediaRequest) SetMetadata(v []Metadata) {
	o.Metadata = &v
}

// GetQualities returns the Qualities field value if set, zero value otherwise.
func (o *CreateMediaRequest) GetQualities() []QualityConfig {
	if o == nil || o.Qualities == nil {
		var ret []QualityConfig
		return ret
	}
	return *o.Qualities
}

// GetQualitiesOk returns a tuple with the Qualities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMediaRequest) GetQualitiesOk() (*[]QualityConfig, bool) {
	if o == nil || o.Qualities == nil {
		return nil, false
	}
	return o.Qualities, true
}

// HasQualities returns a boolean if a field has been set.
func (o *CreateMediaRequest) HasQualities() bool {
	if o != nil && o.Qualities != nil {
		return true
	}

	return false
}

// SetQualities gets a reference to the given []QualityConfig and assigns it to the Qualities field.
func (o *CreateMediaRequest) SetQualities(v []QualityConfig) {
	o.Qualities = &v
}

// GetSegmentDuration returns the SegmentDuration field value if set, zero value otherwise.
func (o *CreateMediaRequest) GetSegmentDuration() int32 {
	if o == nil || o.SegmentDuration == nil {
		var ret int32
		return ret
	}
	return *o.SegmentDuration
}

// GetSegmentDurationOk returns a tuple with the SegmentDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMediaRequest) GetSegmentDurationOk() (*int32, bool) {
	if o == nil || o.SegmentDuration == nil {
		return nil, false
	}
	return o.SegmentDuration, true
}

// HasSegmentDuration returns a boolean if a field has been set.
func (o *CreateMediaRequest) HasSegmentDuration() bool {
	if o != nil && o.SegmentDuration != nil {
		return true
	}

	return false
}

// SetSegmentDuration gets a reference to the given int32 and assigns it to the SegmentDuration field.
func (o *CreateMediaRequest) SetSegmentDuration(v int32) {
	o.SegmentDuration = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreateMediaRequest) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMediaRequest) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateMediaRequest) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CreateMediaRequest) SetTags(v []string) {
	o.Tags = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateMediaRequest) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMediaRequest) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateMediaRequest) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateMediaRequest) SetTitle(v string) {
	o.Title = &v
}

// GetWatermark returns the Watermark field value if set, zero value otherwise.
func (o *CreateMediaRequest) GetWatermark() VideoWatermark {
	if o == nil || o.Watermark == nil {
		var ret VideoWatermark
		return ret
	}
	return *o.Watermark
}

// GetWatermarkOk returns a tuple with the Watermark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMediaRequest) GetWatermarkOk() (*VideoWatermark, bool) {
	if o == nil || o.Watermark == nil {
		return nil, false
	}
	return o.Watermark, true
}

// HasWatermark returns a boolean if a field has been set.
func (o *CreateMediaRequest) HasWatermark() bool {
	if o != nil && o.Watermark != nil {
		return true
	}

	return false
}

// SetWatermark gets a reference to the given VideoWatermark and assigns it to the Watermark field.
func (o *CreateMediaRequest) SetWatermark(v VideoWatermark) {
	o.Watermark = &v
}

type NullableCreateMediaRequest struct {
	value *CreateMediaRequest
	isSet bool
}

func (v NullableCreateMediaRequest) Get() *CreateMediaRequest {
	return v.value
}

func (v *NullableCreateMediaRequest) Set(val *CreateMediaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMediaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMediaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMediaRequest(val *CreateMediaRequest) *NullableCreateMediaRequest {
	return &NullableCreateMediaRequest{value: val, isSet: true}
}
