/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// StreamUsageSummary struct for StreamUsageSummary
type StreamUsageSummary struct {
	DataTransferred    *float32          `json:"data_transferred,omitempty"`
	EndedAt            *string           `json:"ended_at,omitempty"`
	LiveStreamKeyId    *string           `json:"live_stream_key_id,omitempty"`
	RenditionBreakdown *[]RenditionUsage `json:"rendition_breakdown,omitempty"`
	StartedAt          *string           `json:"started_at,omitempty"`
	StreamId           *string           `json:"stream_id,omitempty"`
	TotalDurationMin   *float32          `json:"total_duration_min,omitempty"`
	TotalDurationMs    *int64            `json:"total_duration_ms,omitempty"`
	TotalSegments      *int64            `json:"total_segments,omitempty"`
	TotalStorageBytes  *int64            `json:"total_storage_bytes,omitempty"`
	UserId             *string           `json:"user_id,omitempty"`
}

// NewStreamUsageSummary instantiates a new StreamUsageSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamUsageSummary() *StreamUsageSummary {
	this := StreamUsageSummary{}
	return &this
}

// NewStreamUsageSummaryWithDefaults instantiates a new StreamUsageSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamUsageSummaryWithDefaults() *StreamUsageSummary {
	this := StreamUsageSummary{}
	return &this
}

// GetDataTransferred returns the DataTransferred field value if set, zero value otherwise.
func (o *StreamUsageSummary) GetDataTransferred() float32 {
	if o == nil || o.DataTransferred == nil {
		var ret float32
		return ret
	}
	return *o.DataTransferred
}

// GetDataTransferredOk returns a tuple with the DataTransferred field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamUsageSummary) GetDataTransferredOk() (*float32, bool) {
	if o == nil || o.DataTransferred == nil {
		return nil, false
	}
	return o.DataTransferred, true
}

// HasDataTransferred returns a boolean if a field has been set.
func (o *StreamUsageSummary) HasDataTransferred() bool {
	if o != nil && o.DataTransferred != nil {
		return true
	}

	return false
}

// SetDataTransferred gets a reference to the given float32 and assigns it to the DataTransferred field.
func (o *StreamUsageSummary) SetDataTransferred(v float32) {
	o.DataTransferred = &v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise.
func (o *StreamUsageSummary) GetEndedAt() string {
	if o == nil || o.EndedAt == nil {
		var ret string
		return ret
	}
	return *o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamUsageSummary) GetEndedAtOk() (*string, bool) {
	if o == nil || o.EndedAt == nil {
		return nil, false
	}
	return o.EndedAt, true
}

// HasEndedAt returns a boolean if a field has been set.
func (o *StreamUsageSummary) HasEndedAt() bool {
	if o != nil && o.EndedAt != nil {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given string and assigns it to the EndedAt field.
func (o *StreamUsageSummary) SetEndedAt(v string) {
	o.EndedAt = &v
}

// GetLiveStreamKeyId returns the LiveStreamKeyId field value if set, zero value otherwise.
func (o *StreamUsageSummary) GetLiveStreamKeyId() string {
	if o == nil || o.LiveStreamKeyId == nil {
		var ret string
		return ret
	}
	return *o.LiveStreamKeyId
}

// GetLiveStreamKeyIdOk returns a tuple with the LiveStreamKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamUsageSummary) GetLiveStreamKeyIdOk() (*string, bool) {
	if o == nil || o.LiveStreamKeyId == nil {
		return nil, false
	}
	return o.LiveStreamKeyId, true
}

// HasLiveStreamKeyId returns a boolean if a field has been set.
func (o *StreamUsageSummary) HasLiveStreamKeyId() bool {
	if o != nil && o.LiveStreamKeyId != nil {
		return true
	}

	return false
}

// SetLiveStreamKeyId gets a reference to the given string and assigns it to the LiveStreamKeyId field.
func (o *StreamUsageSummary) SetLiveStreamKeyId(v string) {
	o.LiveStreamKeyId = &v
}

// GetRenditionBreakdown returns the RenditionBreakdown field value if set, zero value otherwise.
func (o *StreamUsageSummary) GetRenditionBreakdown() []RenditionUsage {
	if o == nil || o.RenditionBreakdown == nil {
		var ret []RenditionUsage
		return ret
	}
	return *o.RenditionBreakdown
}

// GetRenditionBreakdownOk returns a tuple with the RenditionBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamUsageSummary) GetRenditionBreakdownOk() (*[]RenditionUsage, bool) {
	if o == nil || o.RenditionBreakdown == nil {
		return nil, false
	}
	return o.RenditionBreakdown, true
}

// HasRenditionBreakdown returns a boolean if a field has been set.
func (o *StreamUsageSummary) HasRenditionBreakdown() bool {
	if o != nil && o.RenditionBreakdown != nil {
		return true
	}

	return false
}

// SetRenditionBreakdown gets a reference to the given []RenditionUsage and assigns it to the RenditionBreakdown field.
func (o *StreamUsageSummary) SetRenditionBreakdown(v []RenditionUsage) {
	o.RenditionBreakdown = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *StreamUsageSummary) GetStartedAt() string {
	if o == nil || o.StartedAt == nil {
		var ret string
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamUsageSummary) GetStartedAtOk() (*string, bool) {
	if o == nil || o.StartedAt == nil {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *StreamUsageSummary) HasStartedAt() bool {
	if o != nil && o.StartedAt != nil {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given string and assigns it to the StartedAt field.
func (o *StreamUsageSummary) SetStartedAt(v string) {
	o.StartedAt = &v
}

// GetStreamId returns the StreamId field value if set, zero value otherwise.
func (o *StreamUsageSummary) GetStreamId() string {
	if o == nil || o.StreamId == nil {
		var ret string
		return ret
	}
	return *o.StreamId
}

// GetStreamIdOk returns a tuple with the StreamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamUsageSummary) GetStreamIdOk() (*string, bool) {
	if o == nil || o.StreamId == nil {
		return nil, false
	}
	return o.StreamId, true
}

// HasStreamId returns a boolean if a field has been set.
func (o *StreamUsageSummary) HasStreamId() bool {
	if o != nil && o.StreamId != nil {
		return true
	}

	return false
}

// SetStreamId gets a reference to the given string and assigns it to the StreamId field.
func (o *StreamUsageSummary) SetStreamId(v string) {
	o.StreamId = &v
}

// GetTotalDurationMin returns the TotalDurationMin field value if set, zero value otherwise.
func (o *StreamUsageSummary) GetTotalDurationMin() float32 {
	if o == nil || o.TotalDurationMin == nil {
		var ret float32
		return ret
	}
	return *o.TotalDurationMin
}

// GetTotalDurationMinOk returns a tuple with the TotalDurationMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamUsageSummary) GetTotalDurationMinOk() (*float32, bool) {
	if o == nil || o.TotalDurationMin == nil {
		return nil, false
	}
	return o.TotalDurationMin, true
}

// HasTotalDurationMin returns a boolean if a field has been set.
func (o *StreamUsageSummary) HasTotalDurationMin() bool {
	if o != nil && o.TotalDurationMin != nil {
		return true
	}

	return false
}

// SetTotalDurationMin gets a reference to the given float32 and assigns it to the TotalDurationMin field.
func (o *StreamUsageSummary) SetTotalDurationMin(v float32) {
	o.TotalDurationMin = &v
}

// GetTotalDurationMs returns the TotalDurationMs field value if set, zero value otherwise.
func (o *StreamUsageSummary) GetTotalDurationMs() int64 {
	if o == nil || o.TotalDurationMs == nil {
		var ret int64
		return ret
	}
	return *o.TotalDurationMs
}

// GetTotalDurationMsOk returns a tuple with the TotalDurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamUsageSummary) GetTotalDurationMsOk() (*int64, bool) {
	if o == nil || o.TotalDurationMs == nil {
		return nil, false
	}
	return o.TotalDurationMs, true
}

// HasTotalDurationMs returns a boolean if a field has been set.
func (o *StreamUsageSummary) HasTotalDurationMs() bool {
	if o != nil && o.TotalDurationMs != nil {
		return true
	}

	return false
}

// SetTotalDurationMs gets a reference to the given int64 and assigns it to the TotalDurationMs field.
func (o *StreamUsageSummary) SetTotalDurationMs(v int64) {
	o.TotalDurationMs = &v
}

// GetTotalSegments returns the TotalSegments field value if set, zero value otherwise.
func (o *StreamUsageSummary) GetTotalSegments() int64 {
	if o == nil || o.TotalSegments == nil {
		var ret int64
		return ret
	}
	return *o.TotalSegments
}

// GetTotalSegmentsOk returns a tuple with the TotalSegments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamUsageSummary) GetTotalSegmentsOk() (*int64, bool) {
	if o == nil || o.TotalSegments == nil {
		return nil, false
	}
	return o.TotalSegments, true
}

// HasTotalSegments returns a boolean if a field has been set.
func (o *StreamUsageSummary) HasTotalSegments() bool {
	if o != nil && o.TotalSegments != nil {
		return true
	}

	return false
}

// SetTotalSegments gets a reference to the given int64 and assigns it to the TotalSegments field.
func (o *StreamUsageSummary) SetTotalSegments(v int64) {
	o.TotalSegments = &v
}

// GetTotalStorageBytes returns the TotalStorageBytes field value if set, zero value otherwise.
func (o *StreamUsageSummary) GetTotalStorageBytes() int64 {
	if o == nil || o.TotalStorageBytes == nil {
		var ret int64
		return ret
	}
	return *o.TotalStorageBytes
}

// GetTotalStorageBytesOk returns a tuple with the TotalStorageBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamUsageSummary) GetTotalStorageBytesOk() (*int64, bool) {
	if o == nil || o.TotalStorageBytes == nil {
		return nil, false
	}
	return o.TotalStorageBytes, true
}

// HasTotalStorageBytes returns a boolean if a field has been set.
func (o *StreamUsageSummary) HasTotalStorageBytes() bool {
	if o != nil && o.TotalStorageBytes != nil {
		return true
	}

	return false
}

// SetTotalStorageBytes gets a reference to the given int64 and assigns it to the TotalStorageBytes field.
func (o *StreamUsageSummary) SetTotalStorageBytes(v int64) {
	o.TotalStorageBytes = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *StreamUsageSummary) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamUsageSummary) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *StreamUsageSummary) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *StreamUsageSummary) SetUserId(v string) {
	o.UserId = &v
}

type NullableStreamUsageSummary struct {
	value *StreamUsageSummary
	isSet bool
}

func (v NullableStreamUsageSummary) Get() *StreamUsageSummary {
	return v.value
}

func (v *NullableStreamUsageSummary) Set(val *StreamUsageSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamUsageSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamUsageSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamUsageSummary(val *StreamUsageSummary) *NullableStreamUsageSummary {
	return &NullableStreamUsageSummary{value: val, isSet: true}
}
