/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// ListThemesRequest struct for ListThemesRequest
type ListThemesRequest struct {
	Limit   *int32  `json:"limit,omitempty"`
	Offset  *int32  `json:"offset,omitempty"`
	OrderBy *string `json:"order_by,omitempty"`
	Search  *string `json:"search,omitempty"`
	SortBy  *string `json:"sort_by,omitempty"`
}

// NewListThemesRequest instantiates a new ListThemesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListThemesRequest() *ListThemesRequest {
	this := ListThemesRequest{}
	var limit int32 = 25
	this.Limit = &limit
	return &this
}

// NewListThemesRequestWithDefaults instantiates a new ListThemesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListThemesRequestWithDefaults() *ListThemesRequest {
	this := ListThemesRequest{}
	var limit int32 = 25
	this.Limit = &limit
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ListThemesRequest) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListThemesRequest) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ListThemesRequest) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *ListThemesRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *ListThemesRequest) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListThemesRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *ListThemesRequest) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *ListThemesRequest) SetOffset(v int32) {
	o.Offset = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *ListThemesRequest) GetOrderBy() string {
	if o == nil || o.OrderBy == nil {
		var ret string
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListThemesRequest) GetOrderByOk() (*string, bool) {
	if o == nil || o.OrderBy == nil {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *ListThemesRequest) HasOrderBy() bool {
	if o != nil && o.OrderBy != nil {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given string and assigns it to the OrderBy field.
func (o *ListThemesRequest) SetOrderBy(v string) {
	o.OrderBy = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *ListThemesRequest) GetSearch() string {
	if o == nil || o.Search == nil {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListThemesRequest) GetSearchOk() (*string, bool) {
	if o == nil || o.Search == nil {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *ListThemesRequest) HasSearch() bool {
	if o != nil && o.Search != nil {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *ListThemesRequest) SetSearch(v string) {
	o.Search = &v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *ListThemesRequest) GetSortBy() string {
	if o == nil || o.SortBy == nil {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListThemesRequest) GetSortByOk() (*string, bool) {
	if o == nil || o.SortBy == nil {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *ListThemesRequest) HasSortBy() bool {
	if o != nil && o.SortBy != nil {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *ListThemesRequest) SetSortBy(v string) {
	o.SortBy = &v
}

type NullableListThemesRequest struct {
	value *ListThemesRequest
	isSet bool
}

func (v NullableListThemesRequest) Get() *ListThemesRequest {
	return v.value
}

func (v *NullableListThemesRequest) Set(val *ListThemesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListThemesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListThemesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListThemesRequest(val *ListThemesRequest) *NullableListThemesRequest {
	return &NullableListThemesRequest{value: val, isSet: true}
}
