/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// AddPlayerThemesToVideoRequest struct for AddPlayerThemesToVideoRequest
type AddPlayerThemesToVideoRequest struct {
	MediaId       *string `json:"media_id,omitempty"`
	PlayerThemeId *string `json:"player_theme_id,omitempty"`
}

// NewAddPlayerThemesToVideoRequest instantiates a new AddPlayerThemesToVideoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddPlayerThemesToVideoRequest() *AddPlayerThemesToVideoRequest {
	this := AddPlayerThemesToVideoRequest{}
	return &this
}

// NewAddPlayerThemesToVideoRequestWithDefaults instantiates a new AddPlayerThemesToVideoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddPlayerThemesToVideoRequestWithDefaults() *AddPlayerThemesToVideoRequest {
	this := AddPlayerThemesToVideoRequest{}
	return &this
}

// GetMediaId returns the MediaId field value if set, zero value otherwise.
func (o *AddPlayerThemesToVideoRequest) GetMediaId() string {
	if o == nil || o.MediaId == nil {
		var ret string
		return ret
	}
	return *o.MediaId
}

// GetMediaIdOk returns a tuple with the MediaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddPlayerThemesToVideoRequest) GetMediaIdOk() (*string, bool) {
	if o == nil || o.MediaId == nil {
		return nil, false
	}
	return o.MediaId, true
}

// HasMediaId returns a boolean if a field has been set.
func (o *AddPlayerThemesToVideoRequest) HasMediaId() bool {
	if o != nil && o.MediaId != nil {
		return true
	}

	return false
}

// SetMediaId gets a reference to the given string and assigns it to the MediaId field.
func (o *AddPlayerThemesToVideoRequest) SetMediaId(v string) {
	o.MediaId = &v
}

// GetPlayerThemeId returns the PlayerThemeId field value if set, zero value otherwise.
func (o *AddPlayerThemesToVideoRequest) GetPlayerThemeId() string {
	if o == nil || o.PlayerThemeId == nil {
		var ret string
		return ret
	}
	return *o.PlayerThemeId
}

// GetPlayerThemeIdOk returns a tuple with the PlayerThemeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddPlayerThemesToVideoRequest) GetPlayerThemeIdOk() (*string, bool) {
	if o == nil || o.PlayerThemeId == nil {
		return nil, false
	}
	return o.PlayerThemeId, true
}

// HasPlayerThemeId returns a boolean if a field has been set.
func (o *AddPlayerThemesToVideoRequest) HasPlayerThemeId() bool {
	if o != nil && o.PlayerThemeId != nil {
		return true
	}

	return false
}

// SetPlayerThemeId gets a reference to the given string and assigns it to the PlayerThemeId field.
func (o *AddPlayerThemesToVideoRequest) SetPlayerThemeId(v string) {
	o.PlayerThemeId = &v
}

type NullableAddPlayerThemesToVideoRequest struct {
	value *AddPlayerThemesToVideoRequest
	isSet bool
}

func (v NullableAddPlayerThemesToVideoRequest) Get() *AddPlayerThemesToVideoRequest {
	return v.value
}

func (v *NullableAddPlayerThemesToVideoRequest) Set(val *AddPlayerThemesToVideoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddPlayerThemesToVideoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddPlayerThemesToVideoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddPlayerThemesToVideoRequest(val *AddPlayerThemesToVideoRequest) *NullableAddPlayerThemesToVideoRequest {
	return &NullableAddPlayerThemesToVideoRequest{value: val, isSet: true}
}
