/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// CreateMediaChapterData struct for CreateMediaChapterData
type CreateMediaChapterData struct {
	MediaChapter *MediaChapter `json:"media_chapter,omitempty"`
}

// NewCreateMediaChapterData instantiates a new CreateMediaChapterData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMediaChapterData() *CreateMediaChapterData {
	this := CreateMediaChapterData{}
	return &this
}

// NewCreateMediaChapterDataWithDefaults instantiates a new CreateMediaChapterData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMediaChapterDataWithDefaults() *CreateMediaChapterData {
	this := CreateMediaChapterData{}
	return &this
}

// GetMediaChapter returns the MediaChapter field value if set, zero value otherwise.
func (o *CreateMediaChapterData) GetMediaChapter() MediaChapter {
	if o == nil || o.MediaChapter == nil {
		var ret MediaChapter
		return ret
	}
	return *o.MediaChapter
}

// GetMediaChapterOk returns a tuple with the MediaChapter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMediaChapterData) GetMediaChapterOk() (*MediaChapter, bool) {
	if o == nil || o.MediaChapter == nil {
		return nil, false
	}
	return o.MediaChapter, true
}

// HasMediaChapter returns a boolean if a field has been set.
func (o *CreateMediaChapterData) HasMediaChapter() bool {
	if o != nil && o.MediaChapter != nil {
		return true
	}

	return false
}

// SetMediaChapter gets a reference to the given MediaChapter and assigns it to the MediaChapter field.
func (o *CreateMediaChapterData) SetMediaChapter(v MediaChapter) {
	o.MediaChapter = &v
}

type NullableCreateMediaChapterData struct {
	value *CreateMediaChapterData
	isSet bool
}

func (v NullableCreateMediaChapterData) Get() *CreateMediaChapterData {
	return v.value
}

func (v *NullableCreateMediaChapterData) Set(val *CreateMediaChapterData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMediaChapterData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMediaChapterData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMediaChapterData(val *CreateMediaChapterData) *NullableCreateMediaChapterData {
	return &NullableCreateMediaChapterData{value: val, isSet: true}
}
