/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// AggregatedMetricsResponse struct for AggregatedMetricsResponse
type AggregatedMetricsResponse struct {
	Data      *AggregatedMetricsData `json:"data,omitempty"`
	RequestId *string                `json:"request_id,omitempty"`
	Status    *string                `json:"status,omitempty"`
}

// NewAggregatedMetricsResponse instantiates a new AggregatedMetricsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregatedMetricsResponse() *AggregatedMetricsResponse {
	this := AggregatedMetricsResponse{}
	return &this
}

// NewAggregatedMetricsResponseWithDefaults instantiates a new AggregatedMetricsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregatedMetricsResponseWithDefaults() *AggregatedMetricsResponse {
	this := AggregatedMetricsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AggregatedMetricsResponse) GetData() AggregatedMetricsData {
	if o == nil || o.Data == nil {
		var ret AggregatedMetricsData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregatedMetricsResponse) GetDataOk() (*AggregatedMetricsData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AggregatedMetricsResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given AggregatedMetricsData and assigns it to the Data field.
func (o *AggregatedMetricsResponse) SetData(v AggregatedMetricsData) {
	o.Data = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *AggregatedMetricsResponse) GetRequestId() string {
	if o == nil || o.RequestId == nil {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregatedMetricsResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || o.RequestId == nil {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *AggregatedMetricsResponse) HasRequestId() bool {
	if o != nil && o.RequestId != nil {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *AggregatedMetricsResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AggregatedMetricsResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregatedMetricsResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AggregatedMetricsResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AggregatedMetricsResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableAggregatedMetricsResponse struct {
	value *AggregatedMetricsResponse
	isSet bool
}

func (v NullableAggregatedMetricsResponse) Get() *AggregatedMetricsResponse {
	return v.value
}

func (v *NullableAggregatedMetricsResponse) Set(val *AggregatedMetricsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregatedMetricsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregatedMetricsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregatedMetricsResponse(val *AggregatedMetricsResponse) *NullableAggregatedMetricsResponse {
	return &NullableAggregatedMetricsResponse{value: val, isSet: true}
}
