/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// RenameApiKeyRequest struct for RenameApiKeyRequest
type RenameApiKeyRequest struct {
	ApiKeyName *string `json:"api_key_name,omitempty"`
}

// NewRenameApiKeyRequest instantiates a new RenameApiKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenameApiKeyRequest() *RenameApiKeyRequest {
	this := RenameApiKeyRequest{}
	return &this
}

// NewRenameApiKeyRequestWithDefaults instantiates a new RenameApiKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenameApiKeyRequestWithDefaults() *RenameApiKeyRequest {
	this := RenameApiKeyRequest{}
	return &this
}

// GetApiKeyName returns the ApiKeyName field value if set, zero value otherwise.
func (o *RenameApiKeyRequest) GetApiKeyName() string {
	if o == nil || o.ApiKeyName == nil {
		var ret string
		return ret
	}
	return *o.ApiKeyName
}

// GetApiKeyNameOk returns a tuple with the ApiKeyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenameApiKeyRequest) GetApiKeyNameOk() (*string, bool) {
	if o == nil || o.ApiKeyName == nil {
		return nil, false
	}
	return o.ApiKeyName, true
}

// HasApiKeyName returns a boolean if a field has been set.
func (o *RenameApiKeyRequest) HasApiKeyName() bool {
	if o != nil && o.ApiKeyName != nil {
		return true
	}

	return false
}

// SetApiKeyName gets a reference to the given string and assigns it to the ApiKeyName field.
func (o *RenameApiKeyRequest) SetApiKeyName(v string) {
	o.ApiKeyName = &v
}

type NullableRenameApiKeyRequest struct {
	value *RenameApiKeyRequest
	isSet bool
}

func (v NullableRenameApiKeyRequest) Get() *RenameApiKeyRequest {
	return v.value
}

func (v *NullableRenameApiKeyRequest) Set(val *RenameApiKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRenameApiKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRenameApiKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenameApiKeyRequest(val *RenameApiKeyRequest) *NullableRenameApiKeyRequest {
	return &NullableRenameApiKeyRequest{value: val, isSet: true}
}
