/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// MeResponse struct for MeResponse
type MeResponse struct {
	Data      *MeData `json:"data,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
	Status    *string `json:"status,omitempty"`
}

// NewMeResponse instantiates a new MeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeResponse() *MeResponse {
	this := MeResponse{}
	return &this
}

// NewMeResponseWithDefaults instantiates a new MeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeResponseWithDefaults() *MeResponse {
	this := MeResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *MeResponse) GetData() MeData {
	if o == nil || o.Data == nil {
		var ret MeData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeResponse) GetDataOk() (*MeData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *MeResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given MeData and assigns it to the Data field.
func (o *MeResponse) SetData(v MeData) {
	o.Data = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *MeResponse) GetRequestId() string {
	if o == nil || o.RequestId == nil {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || o.RequestId == nil {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *MeResponse) HasRequestId() bool {
	if o != nil && o.RequestId != nil {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *MeResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *MeResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *MeResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *MeResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableMeResponse struct {
	value *MeResponse
	isSet bool
}

func (v NullableMeResponse) Get() *MeResponse {
	return v.value
}

func (v *NullableMeResponse) Set(val *MeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeResponse(val *MeResponse) *NullableMeResponse {
	return &NullableMeResponse{value: val, isSet: true}
}
