/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// GetMediaListResponse struct for GetMediaListResponse
type GetMediaListResponse struct {
	Data   *GetMediaListData `json:"data,omitempty"`
	Status *string           `json:"status,omitempty"`
}

// NewGetMediaListResponse instantiates a new GetMediaListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMediaListResponse() *GetMediaListResponse {
	this := GetMediaListResponse{}
	return &this
}

// NewGetMediaListResponseWithDefaults instantiates a new GetMediaListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMediaListResponseWithDefaults() *GetMediaListResponse {
	this := GetMediaListResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetMediaListResponse) GetData() GetMediaListData {
	if o == nil || o.Data == nil {
		var ret GetMediaListData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaListResponse) GetDataOk() (*GetMediaListData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetMediaListResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetMediaListData and assigns it to the Data field.
func (o *GetMediaListResponse) SetData(v GetMediaListData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetMediaListResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaListResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetMediaListResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetMediaListResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetMediaListResponse struct {
	value *GetMediaListResponse
	isSet bool
}

func (v NullableGetMediaListResponse) Get() *GetMediaListResponse {
	return v.value
}

func (v *NullableGetMediaListResponse) Set(val *GetMediaListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMediaListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMediaListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMediaListResponse(val *GetMediaListResponse) *NullableGetMediaListResponse {
	return &NullableGetMediaListResponse{value: val, isSet: true}
}
