/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// GetLiveStreamMediaPublicResponse struct for GetLiveStreamMediaPublicResponse
type GetLiveStreamMediaPublicResponse struct {
	Data   *LiveStreamMediaResponse `json:"data,omitempty"`
	Status *string                  `json:"status,omitempty"`
}

// NewGetLiveStreamMediaPublicResponse instantiates a new GetLiveStreamMediaPublicResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLiveStreamMediaPublicResponse() *GetLiveStreamMediaPublicResponse {
	this := GetLiveStreamMediaPublicResponse{}
	return &this
}

// NewGetLiveStreamMediaPublicResponseWithDefaults instantiates a new GetLiveStreamMediaPublicResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLiveStreamMediaPublicResponseWithDefaults() *GetLiveStreamMediaPublicResponse {
	this := GetLiveStreamMediaPublicResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetLiveStreamMediaPublicResponse) GetData() LiveStreamMediaResponse {
	if o == nil || o.Data == nil {
		var ret LiveStreamMediaResponse
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamMediaPublicResponse) GetDataOk() (*LiveStreamMediaResponse, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetLiveStreamMediaPublicResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given LiveStreamMediaResponse and assigns it to the Data field.
func (o *GetLiveStreamMediaPublicResponse) SetData(v LiveStreamMediaResponse) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetLiveStreamMediaPublicResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamMediaPublicResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetLiveStreamMediaPublicResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetLiveStreamMediaPublicResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetLiveStreamMediaPublicResponse struct {
	value *GetLiveStreamMediaPublicResponse
	isSet bool
}

func (v NullableGetLiveStreamMediaPublicResponse) Get() *GetLiveStreamMediaPublicResponse {
	return v.value
}

func (v *NullableGetLiveStreamMediaPublicResponse) Set(val *GetLiveStreamMediaPublicResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLiveStreamMediaPublicResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLiveStreamMediaPublicResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLiveStreamMediaPublicResponse(val *GetLiveStreamMediaPublicResponse) *NullableGetLiveStreamMediaPublicResponse {
	return &NullableGetLiveStreamMediaPublicResponse{value: val, isSet: true}
}
