/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// ListThemesData struct for ListThemesData
type ListThemesData struct {
	PlayerThemes *[]PlayerTheme     `json:"player_themes,omitempty"`
	Query        *ListThemesRequest `json:"query,omitempty"`
	Total        *int32             `json:"total,omitempty"`
}

// NewListThemesData instantiates a new ListThemesData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListThemesData() *ListThemesData {
	this := ListThemesData{}
	return &this
}

// NewListThemesDataWithDefaults instantiates a new ListThemesData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListThemesDataWithDefaults() *ListThemesData {
	this := ListThemesData{}
	return &this
}

// GetPlayerThemes returns the PlayerThemes field value if set, zero value otherwise.
func (o *ListThemesData) GetPlayerThemes() []PlayerTheme {
	if o == nil || o.PlayerThemes == nil {
		var ret []PlayerTheme
		return ret
	}
	return *o.PlayerThemes
}

// GetPlayerThemesOk returns a tuple with the PlayerThemes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListThemesData) GetPlayerThemesOk() (*[]PlayerTheme, bool) {
	if o == nil || o.PlayerThemes == nil {
		return nil, false
	}
	return o.PlayerThemes, true
}

// HasPlayerThemes returns a boolean if a field has been set.
func (o *ListThemesData) HasPlayerThemes() bool {
	if o != nil && o.PlayerThemes != nil {
		return true
	}

	return false
}

// SetPlayerThemes gets a reference to the given []PlayerTheme and assigns it to the PlayerThemes field.
func (o *ListThemesData) SetPlayerThemes(v []PlayerTheme) {
	o.PlayerThemes = &v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *ListThemesData) GetQuery() ListThemesRequest {
	if o == nil || o.Query == nil {
		var ret ListThemesRequest
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListThemesData) GetQueryOk() (*ListThemesRequest, bool) {
	if o == nil || o.Query == nil {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *ListThemesData) HasQuery() bool {
	if o != nil && o.Query != nil {
		return true
	}

	return false
}

// SetQuery gets a reference to the given ListThemesRequest and assigns it to the Query field.
func (o *ListThemesData) SetQuery(v ListThemesRequest) {
	o.Query = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ListThemesData) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListThemesData) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ListThemesData) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ListThemesData) SetTotal(v int32) {
	o.Total = &v
}

type NullableListThemesData struct {
	value *ListThemesData
	isSet bool
}

func (v NullableListThemesData) Get() *ListThemesData {
	return v.value
}

func (v *NullableListThemesData) Set(val *ListThemesData) {
	v.value = val
	v.isSet = true
}

func (v NullableListThemesData) IsSet() bool {
	return v.isSet
}

func (v *NullableListThemesData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListThemesData(val *ListThemesData) *NullableListThemesData {
	return &NullableListThemesData{value: val, isSet: true}
}
