/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// GetMediaDetailResponse struct for GetMediaDetailResponse
type GetMediaDetailResponse struct {
	Data   *Media  `json:"data,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewGetMediaDetailResponse instantiates a new GetMediaDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMediaDetailResponse() *GetMediaDetailResponse {
	this := GetMediaDetailResponse{}
	return &this
}

// NewGetMediaDetailResponseWithDefaults instantiates a new GetMediaDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMediaDetailResponseWithDefaults() *GetMediaDetailResponse {
	this := GetMediaDetailResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetMediaDetailResponse) GetData() Media {
	if o == nil || o.Data == nil {
		var ret Media
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaDetailResponse) GetDataOk() (*Media, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetMediaDetailResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given Media and assigns it to the Data field.
func (o *GetMediaDetailResponse) SetData(v Media) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetMediaDetailResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMediaDetailResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetMediaDetailResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetMediaDetailResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetMediaDetailResponse struct {
	value *GetMediaDetailResponse
	isSet bool
}

func (v NullableGetMediaDetailResponse) Get() *GetMediaDetailResponse {
	return v.value
}

func (v *NullableGetMediaDetailResponse) Set(val *GetMediaDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMediaDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMediaDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMediaDetailResponse(val *GetMediaDetailResponse) *NullableGetMediaDetailResponse {
	return &NullableGetMediaDetailResponse{value: val, isSet: true}
}
