/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

// PlayerThemeInput struct for PlayerThemeInput
type PlayerThemeInput struct {
	Controls  *Controls `json:"controls,omitempty"`
	IsDefault *bool     `json:"is_default,omitempty"`
	Name      *string   `json:"name,omitempty"`
	Theme     *Theme    `json:"theme,omitempty"`
}

// NewPlayerThemeInput instantiates a new PlayerThemeInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayerThemeInput() *PlayerThemeInput {
	this := PlayerThemeInput{}
	return &this
}

// NewPlayerThemeInputWithDefaults instantiates a new PlayerThemeInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayerThemeInputWithDefaults() *PlayerThemeInput {
	this := PlayerThemeInput{}
	return &this
}

// GetControls returns the Controls field value if set, zero value otherwise.
func (o *PlayerThemeInput) GetControls() Controls {
	if o == nil || o.Controls == nil {
		var ret Controls
		return ret
	}
	return *o.Controls
}

// GetControlsOk returns a tuple with the Controls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerThemeInput) GetControlsOk() (*Controls, bool) {
	if o == nil || o.Controls == nil {
		return nil, false
	}
	return o.Controls, true
}

// HasControls returns a boolean if a field has been set.
func (o *PlayerThemeInput) HasControls() bool {
	if o != nil && o.Controls != nil {
		return true
	}

	return false
}

// SetControls gets a reference to the given Controls and assigns it to the Controls field.
func (o *PlayerThemeInput) SetControls(v Controls) {
	o.Controls = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *PlayerThemeInput) GetIsDefault() bool {
	if o == nil || o.IsDefault == nil {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerThemeInput) GetIsDefaultOk() (*bool, bool) {
	if o == nil || o.IsDefault == nil {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *PlayerThemeInput) HasIsDefault() bool {
	if o != nil && o.IsDefault != nil {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *PlayerThemeInput) SetIsDefault(v bool) {
	o.IsDefault = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PlayerThemeInput) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerThemeInput) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PlayerThemeInput) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PlayerThemeInput) SetName(v string) {
	o.Name = &v
}

// GetTheme returns the Theme field value if set, zero value otherwise.
func (o *PlayerThemeInput) GetTheme() Theme {
	if o == nil || o.Theme == nil {
		var ret Theme
		return ret
	}
	return *o.Theme
}

// GetThemeOk returns a tuple with the Theme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayerThemeInput) GetThemeOk() (*Theme, bool) {
	if o == nil || o.Theme == nil {
		return nil, false
	}
	return o.Theme, true
}

// HasTheme returns a boolean if a field has been set.
func (o *PlayerThemeInput) HasTheme() bool {
	if o != nil && o.Theme != nil {
		return true
	}

	return false
}

// SetTheme gets a reference to the given Theme and assigns it to the Theme field.
func (o *PlayerThemeInput) SetTheme(v Theme) {
	o.Theme = &v
}

type NullablePlayerThemeInput struct {
	value *PlayerThemeInput
	isSet bool
}

func (v NullablePlayerThemeInput) Get() *PlayerThemeInput {
	return v.value
}

func (v *NullablePlayerThemeInput) Set(val *PlayerThemeInput) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayerThemeInput) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayerThemeInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayerThemeInput(val *PlayerThemeInput) *NullablePlayerThemeInput {
	return &NullablePlayerThemeInput{value: val, isSet: true}
}
