/*
 * AIOZ Stream API
 *
 * The AIOZ Stream API, as the generated SDK clients see it.
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
	"encoding/json"

	"fmt"
)

// ManifestType the model 'ManifestType'
type ManifestType string

// List of ManifestType
const (
	HighlightManifestProxy     ManifestType = "proxy"
	HighlightManifestWaveform  ManifestType = "waveform"
	HighlightManifestAudio     ManifestType = "audio"
	HighlightManifestThumbnail ManifestType = "thumbnail"
)

func (v *ManifestType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ManifestType(value)
	for _, existing := range []ManifestType{"proxy", "waveform", "audio", "thumbnail"} {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ManifestType", value)
}

// Ptr returns reference to ManifestType value
func (v ManifestType) Ptr() *ManifestType {
	return &v
}

type NullableManifestType struct {
	value *ManifestType
	isSet bool
}

func (v NullableManifestType) Get() *ManifestType {
	return v.value
}

func (v *NullableManifestType) Set(val *ManifestType) {
	v.value = val
	v.isSet = true
}

func (v NullableManifestType) IsSet() bool {
	return v.isSet
}

func (v *NullableManifestType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManifestType(val *ManifestType) *NullableManifestType {
	return &NullableManifestType{value: val, isSet: true}
}

func (v NullableManifestType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManifestType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
