/*
 * Aioz Stream API
 *
 * Aioz Stream Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiozstreamsdk

import (
//"encoding/json"
)

// MetricFilter struct for MetricFilter
type MetricFilter struct {
	Browsers    *[]string `json:"browsers,omitempty"`
	Continents  *[]string `json:"continents,omitempty"`
	Countries   *[]string `json:"countries,omitempty"`
	DeviceTypes *[]string `json:"device_types,omitempty"`
	MediaIds    *[]string `json:"media_ids,omitempty"`
	MediaType   *string   `json:"media_type,omitempty"`
	Os          *[]string `json:"os,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
}

// NewMetricFilter instantiates a new MetricFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricFilter() *MetricFilter {
	this := MetricFilter{}
	return &this
}

// NewMetricFilterWithDefaults instantiates a new MetricFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricFilterWithDefaults() *MetricFilter {
	this := MetricFilter{}
	return &this
}

// GetBrowsers returns the Browsers field value if set, zero value otherwise.
func (o *MetricFilter) GetBrowsers() []string {
	if o == nil || o.Browsers == nil {
		var ret []string
		return ret
	}
	return *o.Browsers
}

// GetBrowsersOk returns a tuple with the Browsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricFilter) GetBrowsersOk() (*[]string, bool) {
	if o == nil || o.Browsers == nil {
		return nil, false
	}
	return o.Browsers, true
}

// HasBrowsers returns a boolean if a field has been set.
func (o *MetricFilter) HasBrowsers() bool {
	if o != nil && o.Browsers != nil {
		return true
	}

	return false
}

// SetBrowsers gets a reference to the given []string and assigns it to the Browsers field.
func (o *MetricFilter) SetBrowsers(v []string) {
	o.Browsers = &v
}

// GetContinents returns the Continents field value if set, zero value otherwise.
func (o *MetricFilter) GetContinents() []string {
	if o == nil || o.Continents == nil {
		var ret []string
		return ret
	}
	return *o.Continents
}

// GetContinentsOk returns a tuple with the Continents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricFilter) GetContinentsOk() (*[]string, bool) {
	if o == nil || o.Continents == nil {
		return nil, false
	}
	return o.Continents, true
}

// HasContinents returns a boolean if a field has been set.
func (o *MetricFilter) HasContinents() bool {
	if o != nil && o.Continents != nil {
		return true
	}

	return false
}

// SetContinents gets a reference to the given []string and assigns it to the Continents field.
func (o *MetricFilter) SetContinents(v []string) {
	o.Continents = &v
}

// GetCountries returns the Countries field value if set, zero value otherwise.
func (o *MetricFilter) GetCountries() []string {
	if o == nil || o.Countries == nil {
		var ret []string
		return ret
	}
	return *o.Countries
}

// GetCountriesOk returns a tuple with the Countries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricFilter) GetCountriesOk() (*[]string, bool) {
	if o == nil || o.Countries == nil {
		return nil, false
	}
	return o.Countries, true
}

// HasCountries returns a boolean if a field has been set.
func (o *MetricFilter) HasCountries() bool {
	if o != nil && o.Countries != nil {
		return true
	}

	return false
}

// SetCountries gets a reference to the given []string and assigns it to the Countries field.
func (o *MetricFilter) SetCountries(v []string) {
	o.Countries = &v
}

// GetDeviceTypes returns the DeviceTypes field value if set, zero value otherwise.
func (o *MetricFilter) GetDeviceTypes() []string {
	if o == nil || o.DeviceTypes == nil {
		var ret []string
		return ret
	}
	return *o.DeviceTypes
}

// GetDeviceTypesOk returns a tuple with the DeviceTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricFilter) GetDeviceTypesOk() (*[]string, bool) {
	if o == nil || o.DeviceTypes == nil {
		return nil, false
	}
	return o.DeviceTypes, true
}

// HasDeviceTypes returns a boolean if a field has been set.
func (o *MetricFilter) HasDeviceTypes() bool {
	if o != nil && o.DeviceTypes != nil {
		return true
	}

	return false
}

// SetDeviceTypes gets a reference to the given []string and assigns it to the DeviceTypes field.
func (o *MetricFilter) SetDeviceTypes(v []string) {
	o.DeviceTypes = &v
}

// GetMediaIds returns the MediaIds field value if set, zero value otherwise.
func (o *MetricFilter) GetMediaIds() []string {
	if o == nil || o.MediaIds == nil {
		var ret []string
		return ret
	}
	return *o.MediaIds
}

// GetMediaIdsOk returns a tuple with the MediaIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricFilter) GetMediaIdsOk() (*[]string, bool) {
	if o == nil || o.MediaIds == nil {
		return nil, false
	}
	return o.MediaIds, true
}

// HasMediaIds returns a boolean if a field has been set.
func (o *MetricFilter) HasMediaIds() bool {
	if o != nil && o.MediaIds != nil {
		return true
	}

	return false
}

// SetMediaIds gets a reference to the given []string and assigns it to the MediaIds field.
func (o *MetricFilter) SetMediaIds(v []string) {
	o.MediaIds = &v
}

// GetMediaType returns the MediaType field value if set, zero value otherwise.
func (o *MetricFilter) GetMediaType() string {
	if o == nil || o.MediaType == nil {
		var ret string
		return ret
	}
	return *o.MediaType
}

// GetMediaTypeOk returns a tuple with the MediaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricFilter) GetMediaTypeOk() (*string, bool) {
	if o == nil || o.MediaType == nil {
		return nil, false
	}
	return o.MediaType, true
}

// HasMediaType returns a boolean if a field has been set.
func (o *MetricFilter) HasMediaType() bool {
	if o != nil && o.MediaType != nil {
		return true
	}

	return false
}

// SetMediaType gets a reference to the given string and assigns it to the MediaType field.
func (o *MetricFilter) SetMediaType(v string) {
	o.MediaType = &v
}

// GetOs returns the Os field value if set, zero value otherwise.
func (o *MetricFilter) GetOs() []string {
	if o == nil || o.Os == nil {
		var ret []string
		return ret
	}
	return *o.Os
}

// GetOsOk returns a tuple with the Os field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricFilter) GetOsOk() (*[]string, bool) {
	if o == nil || o.Os == nil {
		return nil, false
	}
	return o.Os, true
}

// HasOs returns a boolean if a field has been set.
func (o *MetricFilter) HasOs() bool {
	if o != nil && o.Os != nil {
		return true
	}

	return false
}

// SetOs gets a reference to the given []string and assigns it to the Os field.
func (o *MetricFilter) SetOs(v []string) {
	o.Os = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *MetricFilter) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricFilter) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *MetricFilter) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *MetricFilter) SetTags(v []string) {
	o.Tags = &v
}

type NullableMetricFilter struct {
	value *MetricFilter
	isSet bool
}

func (v NullableMetricFilter) Get() *MetricFilter {
	return v.value
}

func (v *NullableMetricFilter) Set(val *MetricFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricFilter(val *MetricFilter) *NullableMetricFilter {
	return &NullableMetricFilter{value: val, isSet: true}
}
